### ISSUE TITLE
24H format in week view ?

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#1]
Hi @haydenull 

I would like to say: great job! :clap: 
It's very useful, well thought out! 
A first question. Is it possible to display the "daily logs" in "week" view with the 24H format?

At the moment it’s english format (am/pm)

![image](https://user-images.githubusercontent.com/29939805/156928016-266166b2-1f03-4618-80ca-15cd2bed077b.png)

By the way, I realize that it's not 12pm but 12am (before 1pm) that would be right :thinking:

**Comment by haydenull** [comment]
1.1.0 version has been changed to 24 hours format, you can update it.

**Comment by bepolymathe** [comment]
Confirm it works. Thanks
