### ISSUE TITLE
[FR] Add headings support

### ISSUE THREAD

**Issue by danielnbalasoiu** [haydenull/logseq-plugin-agenda#10]
I just installed your plugin and I think it's a game-changer when it comes to using Logseq for planning tasks. Great work!👏

The current implementation supports [[Daily log]] it fails to display the tasks if add headings.

Example

OK
```
[[Daily log]]
- 09:00-09:30 coffe
- 10:00-10:15 walk the dog
```

Broken
```
## [[Daily log]]
- 09:00-09:30 coffe
- 10:00-10:15 walk the dog
```

Thank you!

**Comment by haydenull** [comment]
Version 1.3.1 adds support for heading, you can update it to try it.

**Comment by danielnbalasoiu** [comment]
Yes, it's working now!
Thank you! 🚀
