### ISSUE TITLE
Pomodoro's recorded time should be saved in markdown format

### ISSUE THREAD

**Issue by pushakargaikwad** [haydenull/logseq-plugin-agenda#100]
It appears that as of now Pomodoro's recorded time is stored only in the database.

It must be stored in a markdown file too. This will allow saving data in case of app reset.

_Suggestion:_
For Reference, Currently, logbook data is stored in a markdown file using the format
```
	  :LOGBOOK:
	  CLOCK: [2022-07-21 Thu 14:47:44]--[2022-07-21 Thu 15:13:17] =>  00:25:33
	  CLOCK: [2022-07-21 Thu 15:18:29]--[2022-07-21 Thu 15:40:50] =>  00:22:21
	  :END:
```
Either the Pomodoro timer can be stored with the above format as reference OR the data can be inserted directly in the above LOGBOOK entry

**Comment by haydenull** [comment]
Currently, sdk does not support controlling the logbook, and the logbook can only record time information, while Pomodoro also needs to record whether it is completed and interrupt recording. If the logbook can support comments in the future, it may be possible.

**Comment by pushakargaikwad** [comment]
Can this information be stored someway in markdown as backup? It will be a bummer losing all of it if we lose the DB data. 
A separate Pomodoro-logbook.md maybe where data is just appended. Users can be warned not to edit that file.

**Comment by haydenull** [comment]
Currently, the Pomodoro data is stored in Markdown file, I think you don't need to worry.

**Comment by pushakargaikwad** [comment]
I am currently using syncthing to sync between two machines. It would be helpful if you could provide documentation of how to sync the Pomodoro data.

**Comment by AnweshGangula** [comment]
@haydenull, This is how it is being store in Agenda3 right now. Is this the expected format or should it be store in a `:LOGBOOK:`?

```md
- [ ] Test Task >[🍅 1min](#agenda-pomo://?t=p-1700559048674-11)
```

**Comment by haydenull** [comment]
@AnweshGangula Agenda3 currently does not have a built-in Pomodoro, but you can use the task reminder plugin.
The time information will be recorded in the logbook, which can be recognized and edited by Agenda.

**Comment by AnweshGangula** [comment]
@haydenull, when I right click on any block in Logseq right now, it shows an option called "`Agenda: Start Pomodoro Timer`". Isnt this the built-in Pomodoro from Agenda?

![Logseq Agenda Pomodoro](https://github.com/haydenull/logseq-plugin-agenda/assets/22996896/0a1e43f4-7bfa-4d95-8c51-1927705a88c3)

**Comment by haydenull** [comment]
Yes, this is the build-in pomodoro of Agenda2. You can install task reminder plugin to use pomodoro for Agenda3.

**Comment by AnweshGangula** [comment]
I have installed the task-reminder plugin. But its not clear how it works and how to use it

**Comment by haydenull** [comment]
> When you change a task status to DOING or NOW and it matches a reminding condition, a reminding timer is set.

Just click the TODO tag.

<img width="833" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/823a1c2c-92a0-48c1-b009-6d3b9fe370dd">

**Comment by AnweshGangula** [comment]
Okay, I had to enable the below option in screenshot (`Whether reminding is on for all tasks by default`) option for the pomodoro to work with all tasks. And this does add the `:LOGBOOK:` information.

**But the `:LOGBOOK:` data doesn't show up in `Review` tab of the Agenda plugin.**

![Task Reminder Options](https://github.com/haydenull/logseq-plugin-agenda/assets/22996896/39fc7832-084f-4d1f-a14c-9f67dfa53436)

**Comment by haydenull** [comment]
Agenda3 currently doesn’t have review feature. But the logbook of the completed tasks can be displayed in the calendar.

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/d1b4fe6b-11d2-47d8-8dd9-934b355f559d)
