### ISSUE TITLE
事件时间是否可以支持其他方式

### ISSUE THREAD

**Issue by gsgqgyq** [haydenull/logseq-plugin-agenda#102]
例如支持块属性 `start:: 10:00 end:: 10:30`

**Comment by gsgqgyq** [comment]
试了下，不行。可以的话，同时支持时间和日期就更好了。

`start:: 2022-01-01 10:00`，`start:: 10:00`

**Comment by gsgqgyq** [comment]
同时一个发现了个bug，事件使用 `start:: 10:00 `，`end:: 10:30` 块属性时，打开 Journal → Timeline 页面时直接卡死

**Comment by haydenull** [comment]
> 试了下，不行。 ![截屏2022-07-27 23.31.43.png](https://camo.githubusercontent.com/b81c98163f77e7d28898e43d7915bf25daa96317e29d6680f1e895aad9daa77d/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f32372f574f7a6132347579724a644839366a2e706e67)，![截屏2022-07-27 23.38.58.png](https://camo.githubusercontent.com/05fdc4686c6163c233d1285c937172ec2d0b670ca8118f52cde5ed215ccd6afa/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f32372f796567764d68754158507761356b5a2e706e67)
> 
> 可以的话，同时支持时间和日期就更好了。 `start:: 2022-01-01 10:00`，`start:: 10:00`

看你笔记里是 7月7号，截图是 27号，可以看下 7号有没有这条记录。

`start:: 10:00` 这种形式没有日期，你是想默认今天？

**Comment by haydenull** [comment]
> 同时一个发现了个bug，事件使用 `start:: 10:00 `，`end:: 10:30` 块属性时，打开 Journal → Timeline 页面时直接卡死

这个看了下确实是bug，解析时间的时候出错了

**Comment by gsgqgyq** [comment]
> 看你笔记里是 7月7号，截图是 27号，可以看下 7号有没有这条记录。

不好意思，粗心了，`start:: 2022-01-01 10:00` 是可以正常解析的

> start:: 10:00 这种形式没有日期，你是想默认今天？

是的，不标明日期的情况下，默认今天。

**Comment by haydenull** [comment]
![image](https://user-images.githubusercontent.com/17695989/181655101-a51498f1-70fa-4dba-b395-1b2f365a2792.png)
在Journal中的任务，没有注明日期的话，默认就是journal那一天

**Comment by haydenull** [comment]
> 同时一个发现了个bug，事件使用 `start:: 10:00 `，`end:: 10:30` 块属性时，打开 Journal → Timeline 页面时直接卡死

2.7.0修复了这个问题，可以再试试
