### ISSUE TITLE
【功能请求】反向订阅

### ISSUE THREAD

**Issue by merak0514** [haydenull/logseq-plugin-agenda#103]
目前可以订阅其他日历软件的日程，是否可以实现反向订阅（例如在滴答清单中订阅logseq 的todo）呢？

非常cooool的插件，感谢作者。

**Comment by haydenull** [comment]
插件是纯前端的项目，目前还没有计划做后端，所以暂时不支持。

曲线的方法是将需要被订阅的事件发到 todoist。然后你可以在 todoist 查看，或者用喜欢的软件去订阅 todoist。

**Comment by merak0514** [comment]
那能不能加一个其他 todoist 自动写 journal 的功能呢？因为订阅其他日历这个看板就用不了了。
<img width="943" alt="image" src="https://user-images.githubusercontent.com/35158310/181406481-18c9da6c-c797-4856-8ff7-359abfe0d0e5.png">

**Comment by haydenull** [comment]
没太看懂，你是说把订阅日历自动写到每天的journal里吗？

目前是支持把todoist的任务拉取到journal的

**Comment by merak0514** [comment]
> 目前是支持把todoist的任务拉取到journal的

我希望的就是这个功能，不过滴答清单的订阅似乎会识别为日程而非 todo，并不会被自动写到 journal 里面。

<img width="962" alt="image" src="https://user-images.githubusercontent.com/35158310/181684608-7a61f31b-5a96-41a7-aada-e1f5d0d058a1.png">

**Comment by haydenull** [comment]
确实不支持，因为滴答没开放api,等以后滴答清单开放了插件会支持的。
其实我以前用的也是滴答清单，本来也是想先支持这个的。

**Comment by merak0514** [comment]
滴答清单开放的api 会把 todo 以日程的形式订阅，如果方便的话可以先加一个把 日程自动写 journey 的😃

**Comment by haydenull** [comment]
呃，有滴答的api文档吗，订阅日历这种形式跟开放api还是不一样的，无法获取任务变更，也不能推送新任务到滴答

**Comment by haydenull** [comment]
Agenda3 支持了这个功能，欢迎测试

**Comment by merak0514** [comment]
过两天试一试

**Comment by merak0514** [comment]
不好意思回复晚了，最近测试了一下，已经非常不错了，感谢作者！。不过我发现好像没法自动的 upload？还是说我没找到？

**Comment by haydenull** [comment]
> 不好意思回复晚了，最近测试了一下，已经非常不错了，感谢作者！。不过我发现好像没法自动的 upload？还是说我没找到？

确实没有自动 upload，主要是担心用户多个设备使用时冲突
