### ISSUE TITLE
Todoist ! 

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#104]
Hi @haydenull !

Thank you very much for this wonderful plugin. Integration with Todoist is great news when synchronization is direct. It works very well with the modification of the title.

Do you imagine other additions during synchronization ? The date ?  The description ?

It would be great !

And how you created a new task from logseq 🤔

**Comment by haydenull** [comment]
The current version supports the synchronization of task dates.
The synchronous description will be supported in the future.

You can create a task in logseq and them click `Agenda: Upload to todoist` from block context menu.
![image](https://user-images.githubusercontent.com/17695989/182049897-15d028bc-4873-4667-9113-f95f517bf470.png)

**Comment by bepolymathe** [comment]
That’s great ! Thanks !

**Comment by haydenull** [comment]
2.7.0 Support for specifying the location of todoist tasks.

![image](https://user-images.githubusercontent.com/17695989/186286333-fb8b329f-7645-4b66-bdcf-e778742b118a.png)
