### ISSUE TITLE
[todoist] sync todos in today journal note

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#107]
I am curious to better understand the use you imagine of synchronization between todoist and logseq. Currently if I import all my todo in my agenda file this has the effect of postponing to today all of my dateless todos (someday / maybe) in todoist...
 
Is this the expected behavior ?

**Comment by haydenull** [comment]
The new version adds the Logseq block position setting.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/17695989/197949390-28bbb448-501d-42b1-b296-6496a47b879b.png">
