### ISSUE TITLE
节假日的订阅只显示矩形头部？

### ISSUE THREAD

**Issue by Gitbreast** [haydenull/logseq-plugin-agenda#108]
如图，只显示一个竖杠，是有意为之还是bug？
icloud的订阅显示则没问题，是因为节假日的文字内容太长导致bug了吗？

![image](https://user-images.githubusercontent.com/96460796/183852574-b716e103-8396-45c7-9e43-0816a7d38f8a.png)
![image](https://user-images.githubusercontent.com/96460796/183852211-cd21f5ee-bebc-4055-9d07-612be7302b03.png)

**Comment by haydenull** [comment]
应该是个bug，下个版本会修复

**Comment by haydenull** [comment]
2.7.0修复了这个问题，可以再试试
