### ISSUE TITLE
无法在 Daily Log 页面显示任务

### ISSUE THREAD

**Issue by cynial** [haydenull/logseq-plugin-agenda#109]
比如这样设置后，按文档说明，应该可以在 Daily Log 页面显示时间段的，但是 Daily Log 页面总是一片空白

- [[Daily Log]]  
	- TODO 06:00-08:00 test

 ps：其他页面是正常的，Logseq 最新版本 0.8.0

**Comment by haydenull** [comment]
把 TODO 去掉就行了，DailyLog页面是展示间歇日记用的，不再收集任务了，任务可以到Calendar页面或者Dashboard去查看

**Comment by cynial** [comment]
@haydenull 有点奇怪，现在在 DailyLog 页面创建事项，会自动生成 TODO；然后手动去掉 TODO 的话，DailyLog 也不展示

**Comment by cynial** [comment]
> 把 TODO 去掉就行了，DailyLog页面是展示间歇日记用的，不再收集任务了，任务可以到Calendar页面或者Dashboard去查看

明白了，在 Calendar 切换成 Daily 或 Weekly，就能看到时间段了

**Comment by cynial** [comment]
间歇日记的使用可以举个例子吗？试了几种格式都不生效

- [[Dialy Log]]  
	- 16:26 test  

或 Dialy Log 页面下

- 16:35-17:22 吃饭  
- 16:35-18:22 睡觉  

都不生效

**Comment by Gitbreast** [comment]
> @haydenull 有点奇怪，现在在 DailyLog 页面创建事项，会自动生成 TODO；然后手动去掉 TODO 的话，DailyLog 也不展示。插件版本是 v2.6.7

确实出现同样的问题，估计是bug？

**Comment by haydenull** [comment]
刚刚试了下，0.8.0 logseq修改了api，查询返回的数据结构变了。
着急的话可以先用旧版的logseq，比如 0.7.8

插件下个版本会适配一下。

**Comment by haydenull** [comment]
2.7.0修复了这个问题，可以再试试
