### ISSUE TITLE
Ignore Tag指定后无法再次留空

### ISSUE THREAD

**Issue by Gitbreast** [haydenull/logseq-plugin-agenda#110]
Ignore Tag指定后无法清空，只能重置设置。

![image](https://user-images.githubusercontent.com/96460796/184205180-eb8733d6-10f0-4939-97f2-f0aec4ccef46.png)

**Comment by haydenull** [comment]
下个版本会加一个清除功能

**Comment by haydenull** [comment]
2.7.0修复了这个问题，可以再试试
