### ISSUE TITLE
bug | 设置 - project和custom calendar条目可拖动，影响选色

### ISSUE THREAD

**Issue by Gitbreast** [haydenull/logseq-plugin-agenda#111]
排查bug小能手，用project选色的时候发现每个条目整个可拖动，影响选色，custom calendar同理。
![image](https://user-images.githubusercontent.com/96460796/184292924-d5279cb8-22b2-4e10-b5d3-ca9dfcb9a445.png)

**Comment by haydenull** [comment]
恭喜你发现了隐藏功能：拖拽排序。
理论上最好是能在选颜色的时候禁止拖拽排序，但是看了下目前没什么好办法，需要研究下。

**Comment by Gitbreast** [comment]
> 恭喜你发现了隐藏功能：拖拽排序。 理论上最好是能在选颜色的时候禁止拖拽排序，但是看了下目前没什么好办法，需要研究下。

这里的排序原来会影响日历上的先后吗？实在没办法可以禁用拖拽，在后面做一对点按按钮代替，或是一个用于拖拽的抓手（可行吗）？
另，透明度条也不可调节，是故意为之还是出于兼容性的举措？

**Comment by haydenull** [comment]
排序会影响Dashboard和甘特图等的顺序。

透明度之前没支持，下个版本会加上。

拖拽这个其实不影响正常的颜色选择功能，等以后看看有没有办法禁用吧。
