### ISSUE TITLE
bug | agenda 2.7.0 iCloud订阅全天日程错误显示成跨天

### ISSUE THREAD

**Issue by Gitbreast** [haydenull/logseq-plugin-agenda#115]
![image](https://user-images.githubusercontent.com/96460796/186322980-5031af89-24cf-4069-ab38-b2371a1965c5.png)
![image](https://user-images.githubusercontent.com/96460796/186327231-cd5e322b-350d-4b2b-ad5e-a6c39054ce3e.png)![image](https://user-images.githubusercontent.com/96460796/186327291-87c6cf8d-122e-4fa8-98f8-fc29f46c5c7c.png)
1. 如图，更新2.7.0后，蓝色为iCloud的ics改成https头的订阅，全天日程识别显示成跨天，日内日程正常显示；
浅绿色日程为另一个二十四节气的ics订阅，全天日程也识别成了跨天。
`https://raw.githubusercontent.com/KaitoHH/24-jieqi-ics/master/23_solar_terms_2015-01-01_2050-12-31.ics`
上一版本（2.6.7？）二者均可以正常显示为一天日程。

2. 一些反馈。#109 关于Daily Log的修复，Daily Log下非TODO的Block可以正常显示了；
#108 ，#110 以及颜色里的透明度可以正常使用了。
3. 一个不影响使用的疑问。样式里的border不是指边框吗？目前border的颜色只影响全天日程的矩形头部，及覆盖非全天日程的小点颜色，是有意设计还是还待完善的部分？

**Comment by haydenull** [comment]
1. 可以试一下 2.7.1 版本还有没有问题

3. 目前就是这么设计的

**Comment by Gitbreast** [comment]
@haydenull 感谢修复，2.7.1可以正常显示了。
