### ISSUE TITLE
Access external calendars privately 

### ISSUE THREAD

**Issue by matosjoaops** [haydenull/logseq-plugin-agenda#119]
Hi @haydenull,

I've tried out the plugin and experimented with the subscription feature but unless I'm doing something wrong it seems that it's only possible to access the data from calendars that have been made public. Would it be possible to improve this so one could, for example, provide their login credentials and avoid making their calendars public?

Thanks in advance

**Comment by haydenull** [comment]
Sorry, this can not be done at present, each channel is not uniform in the way of authentication.

If you can ensure that the subscription link is not leaked, it is actually safe. The plugin does not collect information about your settings.

**Comment by matosjoaops** [comment]
Thank you for the feedback @haydenull
