### ISSUE TITLE
The [Fx] (query modal) button could use a tooltip

### ISSUE THREAD

**Issue by QWxleA** [haydenull/logseq-plugin-agenda#12]
The [Fx] (query modal) button is very small, and it's not obvious what it does. A tooltip with the text "Edit Calendar Queries" or "Edit Calendar saved searches" would be helpful.

Sorry, I don't know how to add a tooltip there.

**Comment by haydenull** [comment]
Thanks for your suggestion, I'll add Tooltip in the next version.

Also, if you're interested, take a look at the [ant design](https://ant.design/components/tooltip/#header) used in this project.

**Comment by QWxleA** [comment]
Thanks! I broke the UI several times trying, so maybe reading the docs is a good idea ;-)

**Comment by haydenull** [comment]
This tooltip can already be seen in version 1.7.0.

**Comment by QWxleA** [comment]
So very excellent, thanks!
