### ISSUE TITLE
Import and Sync Todoist Based Upon Search 

### ISSUE THREAD

**Issue by lutzenburg** [haydenull/logseq-plugin-agenda#122]
## Description

Enable sync based upon a filter instead of the current two options of all projects or a single project. 

## Background

One of the more power features of todoist is it's search syntax which is the basis for it's [filters](https://todoist.com/help/articles/introduction-to-filters). I use Todoist for personal and work purposes and have separate graphs for each. 

To enable me to take advantage of the todoist integration (which I am very grateful to see) I would need to be able to filter out all personal tasks. 

I currently have this done using a search similar to `##Work` to get the work project and all containing tasks. 

## Proposed changes

- Add a new option to the Todoist config to allow sync to be controlled based upon a filter
- If this option is set, apply the filter when fetching new tasks

## Caveats

When syncing new tasks back to todoist, this filter would not be applied, leaving the onus on the label or project set for that task being contained within the filter set (if that is required).

## Related issued

I believe this addition would addresss the following issue: #117

---

@haydenull I am happy to contribute this change myself. I have already had a poke around and given the your existing Todoist implementation believe it to be relatively simple (I have a working implementation already). 

Please let me know if you have any specific contribution guidelines you would like me to follow.

**Comment by haydenull** [comment]
Thank you very much, there is no contribution guide for the project yet, I can add one first if you need it.
