### ISSUE TITLE
resize calendar

### ISSUE THREAD

**Issue by hodanli** [haydenull/logseq-plugin-agenda#13]
can we have ability to resize the window. when i use wider screen it really helps. thanks for great plugin.

**Comment by haydenull** [comment]
Do you mean that a smaller sized calendar interface is needed on the big screen?

**Comment by hodanli** [comment]
yes. and when i use daily view i like it much smaller and like to resize accordingly

**Comment by haydenull** [comment]
I added a maximum width limit in version 1.7.0, and I'll consider the resize feature later.

**Comment by haydenull** [comment]
The 2.0 version has modified the layout and the size of the plug-in changes with the logseq app.
