### ISSUE TITLE
Show main UI hotkey conflict

### ISSUE THREAD

**Issue by yoyurec** [haydenull/logseq-plugin-agenda#133]
Plugin has default show hotkey `Ctrl+Shift+a` (https://github.com/haydenull/logseq-plugin-agenda/blob/main/src/main.tsx#L176), which is the same as default (and common used!) Logseq "Select all blocks" hotkey 😕

![image](https://user-images.githubusercontent.com/137919/194651236-b6a34e87-3d52-4598-9e6f-8d93a8c9c2a4.png)

Can it be changed to something else not occupied?

tnx for awesome plugin, BTW 💪

**Comment by yoyurec** [comment]
any updates here?

**Comment by haydenull** [comment]
This is indeed a question. Do you have any suggestions on what key should be used?

**Comment by yoyurec** [comment]
em... dunno ) any not from Logseq system list )
or disable it for now...

**Comment by haydenull** [comment]
Temporarily change the shortcut key to `ctrl + shift + s`

https://haydenull.github.io/logseq-plugin-agenda/other/command.html#keyboard-shortcuts

**Comment by yoyurec** [comment]
awesome! tnx

**Comment by ItsFated** [comment]
> Temporarily change the shortcut key to `ctrl + shift + s`， And let the user custom shortcut in the future.
> 
> https://haydenull.github.io/logseq-plugin-agenda/other/command.html#keyboard-shortcuts
How to customize shortcut?

**Comment by haydenull** [comment]
> How to customize shortcut?

Currently there is no way, we need to wait for Logseq official to provide the corresponding capability for plugins.
