### ISSUE TITLE
Feature request: A more flexible way to add task for project

### ISSUE THREAD

**Issue by coconutxyz** [haydenull/logseq-plugin-agenda#134]
This plugin single-handedly move me from obsidian to logseq because of the timeline / agenda / calendar and gantt view. There are no equivalent in obsidian despite having a lot more plugins

There is one suggestion that i would like to make - which is allowing task to be added to project from everywhere, not only in the project page, considering that logseq encourages dumping thoughts and notes quickly in journal page / everywhere. Something like block property (project:: [[PROJECT/SAMPLEPROJECT]]) or link / tag in the same line as task would work well imo

Thanks!

**Comment by haydenull** [comment]
```
TODO test
project:: [[projectName]]
```

There is currently support for adding tasks to a project using the project property in the journal.

**Comment by coconutxyz** [comment]
> ```
> TODO test
> project:: [[projectName]]
> ```
> 
> There is currently support for adding tasks to a project using the project property in the journal.

cant believe how i missed it! i can only identity start and end date from the documentation

**Comment by haydenull** [comment]
Yes, it is not mentioned in the documentation for now, I will add it in a later version.

**Comment by coconutxyz** [comment]
Thanks!

**Comment by blu3ch1m3ra** [comment]
I would like to add another statement to this issue.
It would be very nice if we can track the tasks with the properties of the project also in the children of the block.
For example

`- Meeting   11:00
    project:: [[Projekt/ABC]]
	- Teilnehmer  
		-  
	- Diskussion  
		-  
	- Todos  
		- DONE make something special 
		  SCHEDULED: <2022-10-14 Fri 17:00>  
		- TODO a very important task 
		- TODO another task`

It would be a very great feature, If I could see all this tasks in this meetinminutes in my project tasks overview.

**Comment by coconutxyz** [comment]
> I would like to add another statement to this issue. It would be very nice if we can track the tasks with the properties of the project also in the children of the block. For example
> 
> * Meeting   11:00
>   project:: [[Projekt/ABC]]
>   
>   * ## Attendees
>   * ## Discussion
>   * Todos
>     
>     * DONE make something special
>       SCHEDULED: <2022-10-14 Fri 17:00>
>     * TODO a very important task
>     * TODO another task
> 
> It would be a very great feature, If I could see all this tasks in this meetinminutes in my project tasks overview.
> 
> I replied, because I wasn't 100% sure if it's easier for you to track the issues in this threat rather then opening another one related to tasks in projects without a specific project page. If you like, I can open a seperate Issue for this feature request.

Haha are you me? I have been thinking about this, so far for each Todo items I have to update the property which is  eh..

**Comment by blu3ch1m3ra** [comment]
So can we reopen this issue as a feature request and see, what @haydenull thinks of this? I would love to see this feature. 
but as I‘m completely unfamiliar with TS I can’t implement this by myself and propose a pull request.
