### ISSUE TITLE
Pomodoro badge renders poorly

### ISSUE THREAD

**Issue by andremann** [haydenull/logseq-plugin-agenda#136]
It looks like the pomodoro badge displayed upon completion is trying to render a broken image.
<img width="408" alt="Screenshot 2022-10-14 at 11 46 44" src="https://user-images.githubusercontent.com/5096918/195817449-e65f410e-da5a-4e56-9c5b-ce6431c813de.png">

Also, it would be nice to start a pomodoro timer with a command and not only with right-click.

**Comment by haydenull** [comment]
It looks like this is caused by the theme, what theme are you using?

Agenda doesn't insert images here, but the Pomodoro badge is rendered using the link format, and it's possible that a theme or plugin will do something about the links.

**Comment by andremann** [comment]
Ah! I found the problem. 
It's not due to a theme I am currently using, since I have a `custom.css` with a couple of styles only.
It turns out that the plugin https://github.com/0x7b1/logseq-plugin-automatic-url-title tries to resolve your `agenda-pomo://` URI and fetch an icon, which cannot be found. I will open a ticket there.

**Comment by andremann** [comment]
BTW, is there a reason why the badge renders with a `>` char in front of it?
Can I remove it?

**Comment by haydenull** [comment]
This symbol is a token to help parse Pomodoro information. It cannot be deleted.

**Comment by andremann** [comment]
Ah, I got it. Pomodoros on the same block keep piling up and their info is encoded and concatenated with `&` in the link.
If I remove it, the popup window doesn't pick up the information at all :-(

**Comment by haydenull** [comment]
> Uhm... I see... It's a bit unfortunate as that char is a blockquote in Markdown, and it renders funny if the pomodoro badge appears on a different line, but I guess that's not how you meant to use the plugin. Is it used by the agenda dashboard when counting pomodoros? Couldn't it use the emoji as a special token instead? What happens if I accidentally erase it manually?

Markdown blockquote requires the `>` symbol to be at the beginning of a sentence. And `>` needs to be followed by a space. Generally, there is no conflict with the plugin's syntax.
