### ISSUE TITLE
Subscription Calendar feature CORS problem

### ISSUE THREAD

**Issue by yoyurec** [haydenull/logseq-plugin-agenda#14]
Trying to add Google calendar private iCal URL, but got error "Get Calendar Google data error
Error: Network Error"

![image](https://user-images.githubusercontent.com/137919/158061434-ab474d7d-7257-477b-a6fa-db4d455b2bee.png)

**Comment by haydenull** [comment]
Logseq's plugin runs in an iframe. 

The plugin downloaded from the Marketplace is run using lsp protocol loading.
<img width="920" alt="image" src="https://user-images.githubusercontent.com/17695989/158112356-901bbea7-4add-42f2-b503-577c48dea647.png">


When loading the local plug-in manually, the file protocol is used.
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/17695989/158112437-f44334d9-432b-4c28-ad56-0d97f807b38e.png">


The file protocol can successfully request Google Calendar's subscription URL.

Currently, it can only be solved by downloading the plugin from [release](https://github.com/haydenull/logseq-plugin-agenda/releases) and then manually loading.

**Comment by yoyurec** [comment]
interesting how https://github.com/sawhney17/logseq-calendars-plugin solves this problem.... it works with google cal

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/158181079-aa396611-0afa-4e82-aa84-579d96adb16e.png)

**Comment by haydenull** [comment]
You need to close the plugin downloaded from the Marketplace before opening the plugin that is loaded locally

![image](https://user-images.githubusercontent.com/17695989/158300625-8551a27f-18e1-4153-9d63-24edd56c6d9b.png)

**Comment by haydenull** [comment]
> interesting how https://github.com/sawhney17/logseq-calendars-plugin solves this problem.... it works with google cal

This plugin is loaded by the file protocol, I have already communicated this issue with logseq developers, and I will reply to you as soon as I get a reply.

**Comment by haydenull** [comment]
Version 1.9.4 solves this problem, welcome tria.

**Comment by yoyurec** [comment]
> Trying to add Google calendar private iCal URL, but got error "Get Calendar Google data error Error: Network Error"
> 
> ![image](https://user-images.githubusercontent.com/137919/158061434-ab474d7d-7257-477b-a6fa-db4d455b2bee.png)

updated in market to 1.9.4 - same error. it still uses lsp (((

**Comment by haydenull** [comment]
How about reinstalling after uninstalling.

**Comment by yoyurec** [comment]
hm. working! tnx!
