### ISSUE TITLE
TODO items in Logseq and in TODOIST should hyper link to each other.

### ISSUE THREAD

**Issue by WesHoward** [haydenull/logseq-plugin-agenda#140]
TODO items in Logseq and in TODOIST should hyper link to each other.

The title of the TODOIST task should be a link to the logseq page. Also acceptable would be a link in the task description back to the Logseq block.

The todoist task ID shown in Logseq should be a hyperlink to the URL for the todoist item. Todoist uses https://todoist.com/showTask?id=nnnnnnnn where nnnnnnnn is the ID shown so this should be an easy thing to assemble.

**Comment by haydenull** [comment]
> The title of the TODOIST task should be a link to the logseq page. Also acceptable would be a link in the task description back to the Logseq block.

Opening a specific block of logseq from outside requires a uuid, but the uuid changes after each reindex, and the plugin currently does not have the ability to fix the uuid of a block, so it cannot jump from todoist to logseq.

> The todoist task ID shown in Logseq should be a hyperlink to the URL for the todoist item

This feature can be added to a future release.
