### ISSUE TITLE
Review番茄钟时长在多次跨天完成的block统计上存在问题

### ISSUE THREAD

**Issue by dongtsi** [haydenull/logseq-plugin-agenda#144]
例子
Journal
    2022/10/25
        task 1 > 番茄钟  2022/10/25 25min% 2022/10/26 25min

此时在review面板中task1会随机显示为2022/10/25或2022/10/26，时长为50min

希望能分开两天统计，谢谢

**Comment by haydenull** [comment]
> 此时在review面板中task1会随机显示为2022/10/25或2022/10/26，时长为50min

Review 页面的 Date 显示的是任务的时间，与番茄钟无关。 你的意思是现在 Date 列数据不对吗？

**Comment by dongtsi** [comment]
嗯，比如10.25的任务，我在10.26用了番茄钟，**有时**会显示为10.26

**Comment by dongtsi** [comment]
> 你这个任务设置的是什么时间

就是在10.25的journal下创建的block

**Comment by haydenull** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/17695989/198229598-863aa048-22e2-4d50-b20d-b30830dc75f3.png">

<img width="818" alt="image" src="https://user-images.githubusercontent.com/17695989/198229930-49bb58da-5b76-405e-921f-65c630a8c6a0.png">


<img width="1267" alt="image" src="https://user-images.githubusercontent.com/17695989/198229790-44e0afd2-afa7-4305-8b9e-a4758afc10b5.png">

我试了下没复现，能发一下你那个任务的 block 吗？

另外 Review 的 Date 列显示的应该是时间段，你那边具体显示的是什么呢？

**Comment by dongtsi** [comment]
弄明白了，应该是我在10.26里引用了或者schedule了这个10.25的task，所以才会显示10.26，所以应该也不算bug，不好意思了

希望后续review统计时长的时候能根据番茄钟的时间（而不是task的时间），多谢啦！
