### ISSUE TITLE
Added option to take notes for each external calendar meetings 

### ISSUE THREAD

**Issue by kumareshr** [haydenull/logseq-plugin-agenda#145]
If we have option to take notes by clicking the meeting agenda then if we can refer back that will great away to keep the notes for meeting with agenda plugin. 

Google/Apple Calendar --> subscriptions --> meetings displayed in agenda plugin --> pull today meeting to journal --> select the ongoing meeting --> add notes as child block for future reference.

**Comment by haydenull** [comment]
The subscription calendar is not a real block in logseq, maybe you can use Todoist to create meeting tasks (Todoist can also sync to Google Calendar) and then sync to logseq.
