### ISSUE TITLE
[Bug] Bottom border spill over in Calender and Daily-log view

### ISSUE THREAD

**Issue by ycbrd** [haydenull/logseq-plugin-agenda#148]
首先非常感谢您做的插件，非常非常好用。希望您能留一个除buymeacoffee.com以外的捐献渠道，没有能用的卡。
我的问题是：缩放比例很大时，Calender 和 Daily-log view 底部内容会溢出无法看到。下图中界面已经滚动到了能滚动的最低处，10点及以后的内容就看不到了。
![image](https://user-images.githubusercontent.com/105804326/201355132-f6eb81dc-86a3-4c89-b2d2-3ca000a4b2fe.png)
我承认我系统缩放调太大了……但是像 Gantt 和 Timeline view 这样就很好啊：
![image](https://user-images.githubusercontent.com/105804326/201355187-02295d85-56ab-46e7-8e64-0593d2c5af6d.png)
希望它不难修复~再次感谢您！！！

**Comment by haydenull** [comment]
你这边调的缩放比例是多少呢，日历是用的开源第三方组件，所以可能确实有问题。

**Comment by haydenull** [comment]
你用的显示器是多少寸的，即使把 logseq 铺满屏幕也不能完整显示吗？

**Comment by ycbrd** [comment]
在这个缩放下，确实铺满也不能完整显示。但还是说， Gantt 和 Timeline view 就没事。
屏幕12.3英寸，显示比例3:2，分辨率2736x1824

**Comment by haydenull** [comment]
那可能确实是高度不够用，Gantt 是我自己写的，会自动适应。

你现在是 0 点到 24 点都要显示吗，或许可以把不常用的时间段去掉，这样说不定能好点。

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/17695989/203272772-e09d3def-cbd0-4cc3-87d4-708f1ea671d3.png">

**Comment by ycbrd** [comment]
您好，调整时间范围不能影响下边界位置。即使我设置一天只有20:00-24:00，竟然还是会溢出的。
![image](https://user-images.githubusercontent.com/105804326/203274224-fe6b9a59-6f16-466e-a14c-4f3ac9e3f389.png)

**Comment by ycbrd** [comment]
好的。
![image](https://user-images.githubusercontent.com/105804326/203277159-28639b6e-6752-42ca-812d-a412a124c2ec.png)
实际上使用周、二周和月视图也会溢出，Dailylog和Calender显然都如此。

**Comment by haydenull** [comment]
刚翻了下日历组件的代码，出现这个问题的原因是日历部分高度不足。

这个目前没什么好办法，只能期待 [Tui Calendar](https://ui.toast.com/tui-calendar) 能优化了。

**Comment by ycbrd** [comment]
好的，谢谢您

**Comment by haydenull** [comment]
Agenda3 换了日历组件，可以试试

**Comment by ycbrd** [comment]
感谢更新，对Agenda 3我没有遇到最大化窗口仍溢出屏幕的问题。不过backlog宽度似乎不变，如果手动调小窗口，没有收起backlog，图标按钮可能会和backlog重叠。当然，这不是什么问题了，内容可显示全，而且收起后不会有影响。
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/105804326/2c926e67-bd44-4e96-a50b-58671015728a)
