### ISSUE TITLE
[Feature] Modify Schedule // Option to keep the duration fixed when modifying start time

### ISSUE THREAD

**Issue by e-zz** [haydenull/logseq-plugin-agenda#149]
Thanks for this amazing plugin.
And here is one small feature that might be quite handy sometimes. We know some events or tasks always consume fixed amount of time. So maybe we could make good use of this and be a little bit more lazy 🤣

Say, we already have a meeting for two hours in our agenda, but now we have to adjust its starting date (or time). In this case, it helps if there's a button to **lock the time span** like
<img src="https://user-images.githubusercontent.com/37920155/201417359-53abe98d-c2f0-4d03-8089-87e9606677e4.png" width="200" />

One can manually change the starting date, while the ending date will be set automatically by the plugin since the time spent is already known.  One simple example
<img src="https://user-images.githubusercontent.com/37920155/201417649-3072dfcd-086a-459a-a651-aeaf2df03f65.png" width="255" />

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.

**Comment by e-zz** [comment]
> Agenda3 has a brand new calendar, you can give it a try.

Great, it looks awesome!
