### ISSUE TITLE
Long calendar item popup is cutted

### ISSUE THREAD

**Issue by yoyurec** [haydenull/logseq-plugin-agenda#15]
When block has a lot of **State** records there is no possibility to see link "Navigate to block"
Scrollbar request! ))
![image](https://user-images.githubusercontent.com/137919/158075531-cc0680b7-38b1-4197-98d3-56d932b9e738.png)

**Comment by haydenull** [comment]
Version 1.8.1 added a height limit.

> The original journalDateFormatter configuration required the user to read the dayjs document to fill in correctly, Version 1.8.1 removes the journalDateFormatter setting. Instead, I got it from logseq on my own, which unfortunately affected the original date parsing. If you get the error 'Use 'yyyyy' instead of 'YYYY' (in 'YYYYMMDD') for formatting', please click the fx button in the settings to change all YYYYMMDD to yyyyMMdd

**Comment by yoyurec** [comment]
confirmed, works well! tnx
