### ISSUE TITLE
Agenda and task list view not ordered by time

### ISSUE THREAD

**Issue by krillin666** [haydenull/logseq-plugin-agenda#150]
Hey !

I've noticed that when the tasks are displayed in the agenda view or the task list they are ordered by projects/calendars and then by time.
So in my case, I see all the task ordered by time of one of my subscription calendars and **after** those events I see the tasks ordered by time for another project.

Thank you!

**Comment by haydenull** [comment]
Today's tasks are currently sorted by start time, and do not differentiate between projects, do you have an example?

<img width="310" alt="image" src="https://user-images.githubusercontent.com/17695989/203265658-ccab0c5a-7843-4a61-ae04-11d5358350c6.png">
