### ISSUE TITLE
是否可以实现任务状态切换为DOING/Now时自动开始番茄钟？

### ISSUE THREAD

**Issue by byheaven** [haydenull/logseq-plugin-agenda#154]
如果不可以的话，希望能有更便捷的方式例如快捷键能够开始番茄。另外就是番茄的时间记录结果是否可以在多个设备同步呢？谢谢！

**Comment by byheaven** [comment]
或者说，是否可以实现每次当agenda开始一个番茄钟的时候，相应任务就可以自动修改为DOING/NOW状态，然后番茄钟中断或结束则变为TODO/LATER状态。这样的好处是自带的Logbook也能记录相对应的时间信息，方便后续通过query table来统计更详细的时间花费。谢谢！

**Comment by haydenull** [comment]
番茄钟的数据都是直接写到 markdown 文件里的，和普通的笔记一样没什么区别，可以随意同步。

agenda 有提供番茄钟数据的汇总页，就是那个 review 页面。

至于快捷启动，是有考虑给 todo 加一个小按钮触发，不过还需要测试一下是否可行。（由于番茄钟需要与任务关联，所以单纯快捷键无法启动。至于任务状态切换触发，目前 sdk 没有监听这个的 api，也不太好实现。）

**Comment by byheaven** [comment]
谢谢详细的回复！启动番茄钟时，是否可以通过直接修改该任务的文本内容来实现任务状态切换？比如直接删除TODO，增加DOING？

**Comment by haydenull** [comment]
可以做到修改文本，但是这种修改能否正常触发 logbook 就得再测一下了

**Comment by byheaven** [comment]
这个是可以的，我试过，从LATER到NOW和反过来都是可以的。

**Comment by haydenull** [comment]
2.13.0 在侧边栏增加了一个按钮，点击即可启动番茄钟。

<img width="368" alt="image" src="https://user-images.githubusercontent.com/17695989/206170076-eb7302a5-7703-4fc1-b1f9-94695a324270.png">

**Comment by sunzy** [comment]
@haydenull  大佬，请教一下——在Calendar里能根据任务的番茄钟时间/LOGBOOK 来进行显示吗？——我的诉求就是看一天内各个时间段都做了什么事

**Comment by haydenull** [comment]
这个暂时不行，不过这个功能在计划内，以后会有一个番茄钟的数据分析模块

**Comment by haydenull** [comment]
Agenda3 使用 logbook 来记录时间，可以配合 task reminder 插件实现番茄钟功能，同时日历支持显示 logbook
