### ISSUE TITLE
Unable to synch with todoist

### ISSUE THREAD

**Issue by WesHoward** [haydenull/logseq-plugin-agenda#155]
Since the weekend I am unable to synch todoist in either direction. I am getting the following error.

I deleted and readded my API key from todoist and no change.

Sync Error
message: This API endpoint is no longer available.

Please refer to our documentation to upgrade your client to use the latest API version: https://developer.todoist.com/sync/v9/#migrating-from-v8

Please check whether the task has been deleted or whether the todoist-id is correct

**Comment by WesHoward** [comment]
well today it works! Is there a way to capture debug info about this if it happens again?

**Comment by haydenull** [comment]
The previous error was reminding developers to upgrade the todoist SDK, this should be a one-time reminder.

The next version of agenda will upgrade the SDK.
