### ISSUE TITLE
在agenda中设置任务时间会导致系统schedule消失

### ISSUE THREAD

**Issue by byheaven** [haydenull/logseq-plugin-agenda#156]
例如某任务：
- TODO test
SCHEDULED: <2022-12-01 Thu 10:00 .+1d>

在agenda中会出现在相应日历10:00-11:00位置(设置默认时长为1h)，此时如果通过拖动将时长变更为10:00-12:00，则原来block中的schedule信息就没有了。

期望的结果：在agenda修改任务的时长或时间段，会相应更新schedule或deadline中的字段(上述例子中由于起始时间没变，因此保留原来的字段。如果在agenda中将时间变为14:00-16:00，则修改schedule内容，Logseq也是支持识别文本修改schedule字段后内容的)

好处：可以借助Logseq本身的schedule或deadline信息实现循环任务，并且在agenda中的更改可以同步。

**Comment by haydenull** [comment]
目前是偷懒的实现，修改后统一使用 agenda 自定义的时间格式。

不过也有计划支持原有时间的格式不变。

**Comment by haydenull** [comment]
Agenda3 使用原生 SCHEDULED，应该不会再有这个问题了，可以试试
