### ISSUE TITLE
Got error when updated to v1.8.1

### ISSUE THREAD

**Issue by fortunehan** [haydenull/logseq-plugin-agenda#16]
Hi,
Please help to check.
After I updated to latest version, when I open the plugin, got below error.
![image](https://user-images.githubusercontent.com/9983619/158087750-e1c2f7ca-097d-4ee1-9000-794ad4cc26ec.png)

Macbook Pro 12.2.1
Logseq 0.6.2

**Comment by haydenull** [comment]
I'm sorry for that.

> The original journalDateFormatter configuration required the user to read the dayjs document to fill in correctly, Version 1.8.1 removes the journalDateFormatter setting. Instead, I got it from logseq on my own, which unfortunately affected the original date parsing. If you get the error 'Use 'yyyyy' instead of 'YYYY' (in 'YYYYMMDD') for formatting', please click the fx button in the settings to change all YYYYMMDD to yyyyMMdd

**Comment by fortunehan** [comment]
thanks for your reply
