### ISSUE TITLE
Daily Log 不显示全天任务

### ISSUE THREAD

**Issue by JoeQiao7** [haydenull/logseq-plugin-agenda#162]
![image](https://user-images.githubusercontent.com/104958016/208118938-db384d32-037b-42d4-aa5a-c43b02f85a13.png)
![image](https://user-images.githubusercontent.com/104958016/208119034-d0ccca21-b42b-4de5-9d39-2b08809277e1.png)

**Comment by haydenull** [comment]
不带时间戳的日志确实是不会显示的。

Daily Log 页是查看平时随手记录用的（没有时间戳也就没有意义了），要查看任务的话用日历页就可以。

后续这个页面会加入时间分析，到时候就能更清楚地分辨任务和日志的不同了
