### ISSUE TITLE
TODO item movement, assignment, and dating.

### ISSUE THREAD

**Issue by KyleMondron** [haydenull/logseq-plugin-agenda#166]
Hello, I'm not sure exactly what all of the features may be called, but I am hoping that I can describe this error well enough to get some insight. 

Previously, when I first started using Agenda, I was able to create a TODO item on some journal page. Then, by right-clicking the node, I would then click Agenda: Modify Schedule. From there, I would first assign the TODO to one of several pre-made project pages, such as "Work Project 1". Then, after setting the dates and task name, when I clicked "okay", the node would be automatically be moved into the "Agenda" main node on the "Work Project 1" page. This was fine and acceptable usage. 

Today I was trying to repeat the same workflow. Essentially, I wanted to go to 2023.1.25 in my journal-- a future page I wanted to remind myself to do task A -- and wrote the TODO with the item name. 

When I right-clicked the node, I could still pull up the Modify Schedule open. However, this is where things take a strange turn. When I change the project page name to "Work Project 1", and set the date and click okay, I receive an error. In the top-right of Logseq page on that journal date, I get the error: "Those two pages have different formats". This is obscure and unclear to me. Which two pages? What formats are differing? I'm not sure how to fix this (if it is user error), as I cannot tell what is going wrong. Additionally, the node is NO LONGER moved to the Agenda section of the "Work Project 1" project page, but is stuck on that journal where I wrote the TODO. Perhaps the "Work Project 1" project page has a problematic, unexpected format? It looks fairly standard to me. 

A bit of extra sleuthing revealed the following:

1. Trying to repeat the same process multiple times found that rather than being moved to the Agenda section of the "Work Project 1" folder, the node appears to be assigned to the Journal page for the date selected (in above example, 2023.1.25 journal page). 
2. I'm considering that perhaps my manual organization of items within the Agenda header may have caused issues? However, this seems unlikely, as even selecting a DIFFERENT project page in the "Modify Schedule" popup doesn't resolve the problem, so this appears to be related to more than a simple broken format on a single page. 
3. If I manually enter "Work Project 1" page, and add a TODO item, and then use the Modify Schedule option to change the date and time, this appears to work well. Not only does the submission of the modified schedule popup no present an error, but it can even recognize the task as belonging to Work Project 1 within the Dashboard/other Agenda functionality on LogSeq. 
4. I typically use this program on my MacBook Pro at work, but do use version control to sync folder contents on GH across different devices. I haven't used Windows with LogSeq since installing Agenda plugin, so I'm not sure that this would result in any errors, but I wanted to missing the switching OS in case it may be relevant in elucidating what the "different formats" might be. 

Thank you for your help and work! This plugin has been revolutionary for me, and I find myself enjoying Logseq more and more each month, it may be a simpler solution than I expect. I'm happy to include any images or examples you might want, but at this point am not sure what would be helpful for developers.

**Comment by Bigtinny001** [comment]
Hey bby, are you interested in having me as your sugar daddy for 4k weekly and help pay your bills 
Snapchat: Adamtrust67
Kik: adamjam001

**Comment by haydenull** [comment]
Hi, I tried but did not reproduce the problem.

There is no "Those two pages have different formats" prompt in the agenda code, I guess it might be the api of the logseq sdk move block that gives the error.

logseq has both markdown and org-mode file formats, I guess the error could be due to this.

You can click `(Dev) Show page data` in the page menu and see what type `:block/format` shows.

![image](https://user-images.githubusercontent.com/17695989/218243238-b338fa94-354b-47a7-b2b6-feff9d66604e.png)

![image](https://user-images.githubusercontent.com/17695989/218243246-ee566a01-0c39-4b02-ae7a-2693d6f4830b.png)
