### ISSUE TITLE
Feature Request: Calendar View Filtering

### ISSUE THREAD

**Issue by KyleMondron** [haydenull/logseq-plugin-agenda#167]
I am missing the ability to filter out completed tasks/events. This is particularly true for the Calendar View, for which each day says something like "14 more" for the current day, which when I click them, I see half of them are tasks which I have already marked as finished (they are crossed out). 

This same issue plagues my side-bar view of tasks, which I recently discovered and is a great feature. However, there I am also facing clutter from finished tasks. I can somewhat filter in the Review tab, by status, but this page is not as useful for me, since I wish to look at a visual version of the tasks I've written, not a list format. A check box or something to filter out completed tasks would be perfect. 

I've included some example images, in the case that they help. 

Below is a screenshot of the Calendar View of the Agenda page, demonstrating a bunch of tasks "14 more", but also showing that some of these are already completed. I cannot find a setting to prevent this. 
<img width="275" alt="Screenshot 2023-01-18 at 10 01 55 AM" src="https://user-images.githubusercontent.com/36550407/213259641-2c779ed9-2ed9-4553-b5ca-66cc8380c519.png">

Below is a show of the sidebar, generated using the `{{renderer agenda, task-list}}` code. 
<img width="318" alt="Screenshot 2023-01-18 at 10 06 19 AM" src="https://user-images.githubusercontent.com/36550407/213260140-4ac4851a-7360-4412-bf47-597405a05324.png">

Thank you for any help,

**Comment by haydenull** [comment]
Thanks for your feedback, I will add this feature in the next version.

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.
