### ISSUE TITLE
【功能请求】能否在Dashboard页面添加“未定时任务“的显示和管理

### ISSUE THREAD

**Issue by msjsc001** [haydenull/logseq-plugin-agenda#168]
开发者您好，
能否在Dashboard页面添加一个**所有未完成任务**的显示和管理，目前Dashboard页面只能显示出 **“定过时的任务”** ，包括在Review也不能搜索出“未定时的任务”， **“未定时的任务”** 如果没有任何显示在日程管理上就缺了一个必要项，很不方便（Logseq自身要用高级搜索才能找到这些未定时的TODO和DOING,对一般用户门槛也是很高）。

**Comment by haydenull** [comment]
是有考虑在在一个地方显示未安排时间的任务

暂时只能在项目详情里看

**Comment by msjsc001** [comment]
谢谢

**Comment by haydenull** [comment]
Agenda3 新增了 Backlog，这里显示的是所有没有时间的任务
