### ISSUE TITLE
Conflict with the Tabs plugin

### ISSUE THREAD

**Issue by ryepesg** [haydenull/logseq-plugin-agenda#169]
When using the Agenda with the Tabs plugin (https://github.com/pengx17/logseq-plugin-tabs), the shortcut to change to the next or previous tabs doesn't work.

Related issue: https://github.com/pengx17/logseq-plugin-tabs/issues/73

**Comment by haydenull** [comment]
I tested `ctrl` + `tab` and it works fine, what keys are you using on your side?

**Comment by yoyurec** [comment]
ryepesg means "when using Tabs+AwesomeUI+Agenda", and click Agenda (AweomeUI makes it not fullscreen, so tabs are visible),  and then trying to switch them via hotkey...

it's AwesomeUI related https://github.com/yoyurec/logseq-awesome-ui/issues/42, so can be closed...

**Comment by ryepesg** [comment]
Thank you very much for the context @yoyurec, will close this issue here then
