### ISSUE TITLE
Query Exec Error

### ISSUE THREAD

**Issue by hodanli** [haydenull/logseq-plugin-agenda#17]
when i click the plugin icon, i get the error in the image.

![image](https://user-images.githubusercontent.com/6535865/158196897-30b4ebf7-9c0d-449b-9f10-cc5d3e908523.png)

**Comment by haydenull** [comment]
I'm sorry for that.

>The original journalDateFormatter configuration required the user to read the dayjs document to fill in correctly, Version 1.8.1 removes the journalDateFormatter setting. Instead, I got it from logseq on my own, which unfortunately affected the original date parsing. If you get the error 'Use 'yyyyy' instead of 'YYYY' (in 'YYYYMMDD') for formatting', please click the fx button in the settings to change all YYYYMMDD to yyyyMMdd

**Comment by haydenull** [comment]
Hopefully your issue has been resolved, welcome to reopen if you still have questions.
