### ISSUE TITLE
Dragging in Calendar view doesn't change "Scheduled Date"

### ISSUE THREAD

**Issue by joelmontoy** [haydenull/logseq-plugin-agenda#172]
Journal tasks with a "Scheduled Date" are shown in the scheduled day, even if they are in the journal of another day. And that's perfect.
However, when you drag and drop this task to another day, the task is moved to the journal of that day but the scheduled date doesn't change. This means that when you open the calendar again, the task is back to the scheduled date, thus the dragging has not changed its location in the calendar.
I would expect that the scheduled date is changed instead of moving the task to another day's journal.
When a task has no scheduled date, then it's perfect the current behaviour of the task being moved to another journal.
Great plugin, by the way!!

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.
