### ISSUE TITLE
Agenda opens with overview of one project

### ISSUE THREAD

**Issue by matthjes** [haydenull/logseq-plugin-agenda#174]
Hi,

I have multiple projects defined, however, whenever I open the agenda I only see a summary page for one project (a page with a small sidebar with entries "List", "Calendar", "Gantt", "Timeline". I have to click on the dashboard button again to see the actual dashboard, with a summary of all projects, the completion graph, and the timeline.

Is there a setting that prevents opening the summary for only one project and that just shows the dashboard?

**Comment by haydenull** [comment]
The plugin will now detect the current page before opening, and if the current page matches one of the projects you have set in the configuration, it will automatically navigate to the detail page of that project. However, you can still open the plugin from any other page to show the plugin dashboard. This should make it more convenient and efficient for users who frequently work with specific projects.

**Comment by SlamSlask** [comment]
Hi,
My question kinda relates to this issue 
The only way I have found to have the plugin sort a new "/todo" into the correct project is to make the "/todo" directly on the page relating to the project

If I add it to the page using "#Project name" /todo "name of task" in directly in the journal the all my /todo is added to the journal project

Is there any way to also make the # dictate which project a "/todo" is connected too?

Hope my question makes sense

**Comment by haydenull** [comment]
Agenda3 supports custom filters, you can give it a try.
