### ISSUE TITLE
Tasks can be moved to "All day" but not the other way around

### ISSUE THREAD

**Issue by ryepesg** [haydenull/logseq-plugin-agenda#176]
In the calendar view, I can not drag an "All day" task into a specific starting hour so I can make it fit easily the rest of my scheduled tasks for the day.

The opposite workflow works though, if I move a task into the region in the past, it will be moved back to be am "All day" task (with the Overdue flame icon):

<img width="223" alt="image" src="https://user-images.githubusercontent.com/10557463/221052273-87786688-df1c-41d3-be97-2f339287a2dc.png">

For additional context:
- I am trying to replicate the workflow I was using with https://akiflow.com/ where it is very easy to schedule a list of tasks into time blocks:
https://akiflow.com/wp-content/themes/wp-bootstrap-starter/assets/images/homepage-v3/time-blocking-1.webm

**Comment by haydenull** [comment]
Sorry, the calendar used by Agenda is from the open source component https://ui.toast.com/tui-calendar, which currently does not support your requirement. Agenda will integrate it as soon as it is supported.

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.
