### ISSUE TITLE
include scheduled tasks

### ISSUE THREAD

**Issue by demorsick** [haydenull/logseq-plugin-agenda#177]
Is it possible to include tasks that are already been scheduled inside some other pages in the agenda?
ex:
[school]:
-[homework]:
   --math 2/2/22
   --.....
-[projects]:
   --arduino project 2/12/22
   
   
   because i can only see tasks that are on the journal page

**Comment by haydenull** [comment]
I'm sorry to inform you that currently the only way to specify a project for a todo is by using the block property. If a block property is not specified, the page will be considered as the project. 

However, I will take note of this requirement and implement it when there is a suitable implementation approach.

**Comment by haydenull** [comment]
Agenda3 supports custom filters, you can give it a try.
