### ISSUE TITLE
Feature request：从google calendar获取事项

### ISSUE THREAD

**Issue by linjunhe** [haydenull/logseq-plugin-agenda#178]
有没有可能从Google日历获取事项到对应的Daily log？这样平时用手机时可以直接在google calendar上记录，而打开logseq点一下就能同步到logseq

目前可以订阅日历，但是并没有对应当天的日记下并没有记录

**Comment by haydenull** [comment]
暂时还不行，有个曲线的方法是使用 todoist，Google Calendar 同步 todoist，logseq 也与 todoist 同步
