### ISSUE TITLE
How to subscribe a Apple Calendar?

### ISSUE THREAD

**Issue by fortunehan** [haydenull/logseq-plugin-agenda#18]
May I know how to subscribe a Apple Calendar? Have tried the url webcal://p24-caldav.icloud.com/published/xxxx , but got error, not valid url.

**Comment by haydenull** [comment]
Just replace `webcal` to `https`.

But Apple Calendar also has CORS limit, you can see this [issue](https://github.com/haydenull/logseq-plugin-agenda/issues/14#issue-1167580550).

I will get back to you as soon as this issue progresses.

**Comment by haydenull** [comment]
Version 1.9.4 solves this problem, welcome trial.

**Comment by haydenull** [comment]
welcome to reopen issue if you still have questions.
