### ISSUE TITLE
插件无法显示

### ISSUE THREAD

**Issue by wufubo** [haydenull/logseq-plugin-agenda#181]
1.下载插件后提示快捷键冲突
![问题01](https://user-images.githubusercontent.com/31535195/222630632-e855a8ba-60b2-490d-8b3d-b92c172b0e26.png)
2.无法点开agenda插件，请问如何解决
![问题02](https://user-images.githubusercontent.com/31535195/222630657-1eab9ebf-4fd1-480b-8017-02c54c636c93.png)

**Comment by haydenull** [comment]
快捷键冲突可能是新版本 logseq 的问题，重启下应用试试？

插件白屏，可以打开控制台看看有什么报错吗

**Comment by martin-kakazu** [comment]
I'm having the same problem, tried uninstalling and installing the plugin, but it only added more error messages. And the "Agenda: ..." menu buttons gets duplicated each time

![image](https://user-images.githubusercontent.com/98295812/223133961-68cd962d-3701-4fde-9cc9-6de7db470031.png)

**Comment by haydenull** [comment]
@martin-kakazu  This is a bug in the new version of logseq, you just need to restart logseq and it should be fixed.

**Comment by wufubo** [comment]
> 

我清除了缓存之后，再重新安装插件就解决了，谢谢
