### ISSUE TITLE
dashboard无法显示新添加的Project页面中的任务

### ISSUE THREAD

**Issue by Soce1lo** [haydenull/logseq-plugin-agenda#186]
logseq 0.8.18beta
我将一个新页面添加到project后，dashboard没有正常显示我在这个新页面中添加的任务。具体见下图
![QQ20230316-132707@2x](https://user-images.githubusercontent.com/53263452/225523881-cd0291b4-78c8-4b07-9633-30c9404f59bf.jpg)
task list同样没有显示新任务
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/53263452/225524034-a93aecf3-f22a-45c5-b673-a53c8fbd3f0b.png">
另外，在添加新porject后，点击agenda按钮进入菜单界面后会直接显示
<img width="459" alt="image" src="https://user-images.githubusercontent.com/53263452/225524251-0d9f6b00-1abd-46cb-a7f1-b33f7a3c6727.png">
而不是默认的dashboard界面

**Comment by haydenull** [comment]
因为这几个任务没有指定日期，所以没有显示侧边栏没有显示

当页面被添加到 project 后，打开插件时会默认进入到项目详情的页面，这个是 feature。。。。。

**Comment by Soce1lo** [comment]
> 因为这几个任务没有指定日期，所以没有显示侧边栏没有显示
> 
> 当页面被添加到 project 后，打开插件时会默认进入到项目详情的页面，这个是 feature。。。。。

原来是这样，真是抱歉没有认真阅读使用说明书，相当然的用自己的逻辑来推测使用方法。。。
我原以为agenda会自动检测当前的日期，看来是我肤浅了。

**Comment by haydenull** [comment]
> > 因为这几个任务没有指定日期，所以没有显示侧边栏没有显示
> > 当页面被添加到 project 后，打开插件时会默认进入到项目详情的页面，这个是 feature。。。。。
> 
> 原来是这样，真是抱歉没有认真阅读使用说明书，相当然的用自己的逻辑来推测使用方法。。。 我原以为agenda会自动检测当前的日期，看来是我肤浅了。

没关系，如果是日记页面，是会默认使用日记的日期的，普通的页面就没有默认日期了
