### ISSUE TITLE
能否直接读取任务里的日期标签来替代SCHEDULED属性

### ISSUE THREAD

**Issue by zxming** [haydenull/logseq-plugin-agenda#19]
当前任务的一般写法是如下的格式，没有单独配置SCHEDULED属性：
TODO 任务描述 [[2022-03-16]] 
这种方式输入更方便，在使用 Logseq 的 Journals 时也方便查看当天关联的任务。

以上，能否读取这种格式的日期呢？

**Comment by haydenull** [comment]
你可以 新建一个自定义日历配置如下图：

![image](https://user-images.githubusercontent.com/17695989/158709738-8d46528c-5b92-49bd-a894-97299556d663.png)

script部分：
```clojure

[:find (pull
  ?block
  [:block/uuid
    :block/parent
    :block/left
    :block/collapsed?
    :block/format
    :block/_refs
    :block/path-refs
    :block/tags
    :block/content
    :block/marker
    :block/priority
    :block/properties
    :block/pre-block?
    :block/scheduled
    :block/deadline
    :block/repeated?
    :block/created-at
    :block/updated-at
    :block/file
    :block/heading-level
    {:block/refs
    [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])
:where
[?block :block/marker ?marker]
[?rp :block/journal? true]
[?block :block/refs ?rp]
[(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]]
```

需要注意的是这个script只针对 `TODO 任务描述 [[2022-03-16]]`，如果这里其他双链或者标签，就会读取时间失败，例如
`TODO 任务描述 [[2022-03-16]] [[test]]` `TODO 任务描述 [[2022-03-16]] #test`

因为这些和日期标签一样都是block的refs，而他们的顺序不固定，我们配置的scheduleStart则是取的第二个ref，可能出错。

**Comment by zxming** [comment]
你好，我用上述脚本能成功读取  `TODO 任务描述 [[2022-03-16]]` 这种不包含其他标签的任务，并匹配到正确的日期。
对其他包含标签或双链的任务，时间识别成今天了。
我确实大部分任务都是带有标签或双链的，不知道有什么方式可以解决这个问题？
我看结果中的 refs 数组中只有日期标签才有 journal-day，如果可以让未匹配上的不识别成今天，是否就可以通过配置多个 query 来把 refs 1~N 都取出来？

**Comment by zxming** [comment]
另外发现，通过该方式添加到日历上的任务，点击 `Navigate To Block` 无反应

**Comment by haydenull** [comment]
```clojure

[:find (pull
  ?block
  [:block/uuid
    :block/parent
    :db/id
    :block/left
    :block/collapsed?
    :block/format
    :block/_refs
    :block/path-refs
    :block/tags
    :block/content
    :block/marker
    :block/priority
    :block/properties
    :block/pre-block?
    :block/scheduled
    :block/deadline
    :block/repeated?
    :block/created-at
    :block/updated-at
    :block/file
    :block/heading-level
    {:block/page
    [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}
    {:block/refs
    [:block/journal-day]}])
:where
[?block :block/marker ?marker]
[?rp :block/journal? true]
[?block :block/refs ?rp]
[(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]]
```

![image](https://user-images.githubusercontent.com/17695989/158911592-c67e42cf-bbe7-4561-ade6-74bf6b48415e.png)

研究了下datascript，现在只查询 ref 的 journal-day 属性就行了，没有这个属性的 ref 会被过滤掉。配合把Schedule Start 改一下。

另一个不能跳转的问题，需要在查询语句里加上对应的 `:db/id` `:block/page`, 你可以用上边这个配置再试试。

现在的隐患就是一个block里写了多个日期，只会读其中一个，不过我想这种 case 应该不常见。

**Comment by zxming** [comment]
非常感谢，使用最新代码已成功解决之前的两个问题。
再提几个小建议：
1. 当前插件的 Dark 主题颜色不能与 Logseq 的主题匹配，个人感觉有点太黑了，如果能直接同步相同的颜色更好。
2. 当前在各个日历视图下任务都固定显示为一行，但对于习惯看周和双周计划来说，一行文本显示的内容太有限，希望能配置为类似 Kanban 的模式，显示2行或多行。
3. 当前插件用于显示已配置日期或时间的任务非常好，是否能考虑在侧边增加一列待办任务池，用于展示所有未关联日期的未完成任务？这样能成为一个完整的任务管理插件。如果未来能支持直接在插件上进行任务操作和内容编辑就更好了。

**Comment by haydenull** [comment]
1. 暗色模式这个目前 logseq 没有开放主题色给插件，后期会考虑开放这块css出来给需要的人自己定制。
2. 因为日历组件用的tui calendar,需要调研下那边能不能支持。
3. 这个是有计划的，会有面板收集所有待办。至于在日历中创建和编辑，这个正在开发，但是这个功能会有一定限制，初期版本的实习是符合一定规则的事件才支持编辑。

**Comment by zxming** [comment]
感谢开发者  持续关注 👍🏻
