### ISSUE TITLE
Daily Log不显示？

### ISSUE THREAD

**Issue by blackwint3r** [haydenull/logseq-plugin-agenda#192]
插件（v2.15.0）和logseq（0.9.1）都更新到最新版了。
设置应该没问题，
journal中的写法也应该没问题，
但是daily log视图是空白的

![image](https://user-images.githubusercontent.com/22995118/231077338-36e5b250-612e-4f8e-ab14-d72d36e64b91.png)
![image](https://user-images.githubusercontent.com/22995118/231077662-a8c162bc-37d2-4196-9352-a79c3ce7a8cc.png)
![image](https://user-images.githubusercontent.com/22995118/231077434-8865faea-eef0-4b68-bc9f-26351b80831a.png)

**Comment by haydenull** [comment]
测了下是 Daily Log 配置下有两个空 tag 引起的，你可以随便填两个，或者等我明天发个新版本解决这个问题

**Comment by haydenull** [comment]
2.15.1 版本可以再试试

**Comment by blackwint3r** [comment]
问题解决了！ 谢谢 😊
