### ISSUE TITLE
[功能请求] 将project和tag的 页面元数据中color属性的值作为颜色的默认值

### ISSUE THREAD

**Issue by blackwint3r** [haydenull/logseq-plugin-agenda#194]
一个小提议，在设置project和 daily-log tag的颜色的时候，能否将其相应page的color属性的值作为颜色的默认值。
这样有一个好处是和 Awesome Props 插件兼容。而且这么做也感觉是比较通用的方案，比如可以对颜色做query。

在awesome props插件中，用page的元数据来设置page的颜色和图标，设置了之后是这样的：
<img width="257" alt="image" src="https://user-images.githubusercontent.com/22995118/231638527-6a8f6900-b592-4ce8-b8c8-0dc905303776.png">

现在 添加了daily log标签和project的时候或者改颜色的时候，在页面的元属性中设置一遍颜色，在daily log和project设置界面还要再设置一遍相同的颜色，有点不方便。
当然也没有非常不方便，所以只是小提议😄

**Comment by haydenull** [comment]
🤩 感觉这个思路不错，我最近也是遇到了，在多个设备上使用时，重新配置一遍 daily log 的 tag 很痛苦，等研究下这个插件

**Comment by blackwint3r** [comment]
是的，不仅不用在配置里设定颜色，也不用在配置里手动添加daily log tag和project，而且可以简化给todo设定project的过程。提一下我的想法：

在我的笔记中，所有的project页面都有 type:: #project 的属性，所有daily log 中的tag都有 type:: #activity的属性。 所以给todo设project在实现上可以简化为，如果一个todo项目打了hash tag，并且那个tag的type属性值是project，那么这个todo就属于这个project，并且用相应的color来显示。daily log同理。（这样也避免了一个daily log项目有多个tag，都有颜色，选哪个的问题：就是只看type是activity的tag）
（题外话，awesome props插件对type属性也有很好的处理，比如它的类型的“实例”可以继承 类型页面中 的icon和color，也可以被实例自己的icon和color所覆盖。 它的“type”这个属性名允许自定义。）

例子：

<img width="503" alt="Screenshot 2023-04-13 at 17 23 36" src="https://user-images.githubusercontent.com/22995118/231716603-db233d45-2a10-4391-b595-cfaba6ecb223.png">
---
<img width="503" alt="Screenshot 2023-04-13 at 17 23 55" src="https://user-images.githubusercontent.com/22995118/231716663-44c9e162-34e4-403c-99be-91c3ea085917.png">



只是我的一点想法，也许你有更好的设计😊

**Comment by haydenull** [comment]
你的标签颜色是 Awesome Props 插件加上的吗，我给 page 加了 color 属性，但是对应的 tag 还是没变色。是需要再装 Awesome 系列的其他插件来满足么

**Comment by blackwint3r** [comment]
抱歉我记错了，是同作者的另一个插件 [Awesome Link](https://github.com/yoyurec/logseq-awesome-links)

> 你的标签颜色是 Awesome Props 插件加上的吗，我给 page 加了 color 属性，但是对应的 tag 还是没变色。是需要再装 Awesome 系列的其他插件来满足么

**Comment by haydenull** [comment]
Agenda3 现在支持使用 page 的 agenda-color 属性了，可以试试

**Comment by kimi0230** [comment]
> Agenda3 现在支持使用 page 的 agenda-color 属性了，可以试试

请问是否可以在同一个page中的各别的todo中, 加入不同颜色呢?
谢谢！

**Comment by haydenull** [comment]
> 请问是否可以在同一个page中的各别的todo中, 加入不同颜色呢? 谢谢！

@kimi0230 这个功能可以用 Filter 实现，Filter 可以自定义 query 查询想要的任意 todo，然后给 filter 设置颜色就可以了 https://www.notion.so/haydenut/0de652cd8d5b46518c4522b0e3f6f0e0#b6a40f6cffec4137acf6c5b8b91e599f

**Comment by Lightup1** [comment]
如果习惯将TODO都放在journal页面，能否让TODO再agenda日历中显示该TODO的tag对应的颜色呢？filter看起来可以实现，但是实际使用的时候发现，只有当你选中显示这个tag的filter的时候才会显示颜色。在显示所有TODO的时候还是只显示journal页面的颜色。

**Comment by haydenull** [comment]
@Lightup1 可以做一个兜底的 Filter，比如我这里有一个 Others，会收集所有的 TODO。然后一直使用 Filter 模式就可以了。
![CleanShot 2024-01-29 at 19 11 07](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/d3a01e67-9c78-4d92-bf4c-47692d8d1999)
