### ISSUE TITLE
logseq更新0.9.2后，daily log中不显示过去的任务

### ISSUE THREAD

**Issue by wangyu407** [haydenull/logseq-plugin-agenda#195]
[[daily log]]
   1:00-3:00 xxx

现在在daily log 视图中不显示xxx了

**Comment by haydenull** [comment]
辛苦提供下插件版本以及 daily log 的配置。

可以试试更新插件到 2.15.1

**Comment by wangyu407** [comment]
插件是2.15.1，logseq是0.9.2。系统是mac Monterey 12.6。
另外，+add tags点击时，无反应
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/115890166/232300901-d6642c33-d0bd-48ad-ac2c-5264a544ddba.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/115890166/232301041-384c6694-a452-42e1-ab9c-22c54ffdda9f.png">

**Comment by haydenull** [comment]
这个是不是因为日历视图里没有一点到三点？

另外格式应该是 01:00-03:00 前面得补个 0

设置里的 Calendar View 里，可以设置 Time Grid, 就是这里时间轴的长度

**Comment by wangyu407** [comment]
您说的补一个0的我试过了，没有用。在我更新Logseq到0.9.2之前，是没问题的，更新之后这个问题就出现了。不仅是今天的没有显示，过去的也不显示。
时间轴的长度，是0 - 24 h。也没有问题。

**Comment by haydenull** [comment]
呃，有点奇怪，我这没复现出来。

方便发一下原始配置文件吗，在插件页选择 open settings（重要的 key 之类的隐私信息可以隐藏一下）。
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/17695989/232349697-0f7daf5d-e1ab-4fca-8e58-68a0124dfe8b.png">

**Comment by wangyu407** [comment]
我把agenda卸载之后重新安装，问题解决了。。。很奇怪，是因为logseq更新导致的吗

**Comment by haydenull** [comment]
2.15.0 版本有个 bug，会导致 daily log 不显示，在 2.15.1 版本修复了，有可能是更新插件后没加载成功，需要重启下才应用新版本吧。之前的有个 issue 提了这个问题 https://github.com/haydenull/logseq-plugin-agenda/issues/192

**Comment by wangyu407** [comment]
好的，感谢。

**Comment by wangyu407** [comment]
发现一个bug，当在设置中将homepage改为daily log时，daily log就不会显示了。卸载插件重新装，可解决此问题
