### ISSUE TITLE
切换calendar的tab之前的数据会莫名其妙清空无法同步

### ISSUE THREAD

**Issue by bernie-shi** [haydenull/logseq-plugin-agenda#196]
在calendar页面输入一些日程，但是切换到gantt或者其他tab后，之前录入的数据就不见了，重新进入才会存在

**Comment by haydenull** [comment]
这个应该属于已知问题，目前只是在打开插件的时候查询了一次任务。在插件里新建任务之后需要等到第二次打开插件时才能看到。这个确实需要优化一下。

**Comment by haydenull** [comment]
Agenda3 现在会实时更新全局状态了，可以试试
