### ISSUE TITLE
基于#195问题

### ISSUE THREAD

**Issue by wangyu407** [haydenull/logseq-plugin-agenda#199]
基于#195问题，我发现导致出现此问题的原因是在设置中将首页显示设置从dashboard更改为其他任意页面，均会导致daily log的清空

**Comment by haydenull** [comment]
有详细的操作步骤吗，我测了下没能复现。

另外请问你的 logseq 版本，插件版本，以及操作系统版本是什么

**Comment by wangyu407** [comment]
<img width="202" alt="image" src="https://user-images.githubusercontent.com/115890166/234159709-392e138c-e4b2-4785-aff2-89893498037b.png">
<img width="224" alt="image" src="https://user-images.githubusercontent.com/115890166/234159760-dbc1e1c9-911f-4731-9335-917003e89642.png">
<img width="976" alt="image" src="https://user-images.githubusercontent.com/115890166/234159853-a4ddd81f-2a47-4eb3-a380-938b4374eed5.png">
<img width="785" alt="image" src="https://user-images.githubusercontent.com/115890166/234159904-f3cf590d-d276-4106-932b-c4478380e1a3.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/115890166/234159925-d656839a-25e2-4f46-a678-6ad2a6dcf7f3.png">
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/115890166/234159973-3f8b7aa7-16fd-4c7d-8968-25edb6749db9.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/115890166/234160002-127905aa-5545-46ed-bd34-82719fa4ca9b.png">
========================
卸载，重新安装
=====================
<img width="813" alt="image" src="https://user-images.githubusercontent.com/115890166/234160196-c728b8c9-5ade-4582-9e40-65786d774255.png">

**Comment by Qiwei-Zhao** [comment]
好像只要进行任何设置都会导致daily log不显示，已经尝试：更改log颜色；订阅日历；更改agenda主题颜色。

**Comment by Lance0901** [comment]
我有相同的問題，修改語言後Daliy log無法顯示，之後使用restore也無法回復，重新卸載安裝後才能顯示，但是訂閱日曆、新增新的Project都會造成同樣的問題
logseg 0.9.4
agenda v2.15.2
Window10 21H2

**Comment by wangyu407** [comment]
@haydenull  这个问题好像仍然存在。

**Comment by haydenull** [comment]
daily log 的配置是什么样的呢

**Comment by wangyu407** [comment]
您好！请参考#195和#199上面提供的信息吧。

**Comment by haydenull** [comment]
> 您好！请参考#195和#199上面提供的信息吧。

似乎这两个 issue 都没详细的 daily log 配置，我这边主要是想看看是否是更新 hoempage 后导致 daily log 设置出错

**Comment by wangyu407** [comment]
<img width="369" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/115890166/48413c5d-46c5-4697-ac6d-f57549a362b7">

**Comment by haydenull** [comment]
> <img alt="image" width="369" src="https://user-images.githubusercontent.com/115890166/253449045-48413c5d-46c5-4697-ac6d-f57549a362b7.png">
现在这个配置能正常显示 daily log 日历吗，我看上边的反馈是切换 homepage 到其他的页面触发了 bug

**Comment by wangyu407** [comment]
现在是可以的。我再发一个出现Bug后的配置。。咦，我卸载agenda之后再重装，这个Bug被修复了。。现在Homepage切换到其他页面，daily log没有问题了

**Comment by haydenull** [comment]
好的，那再观察一下吧，我这边也试试能不能复现
