### ISSUE TITLE
Have the ability to choose the default duration of an event that does not have an end time

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#2]
Hi @haydenull 

I noticed that if I add an event in my "daily log" without giving it an end time, it appears with 30 minutes of duration by default. It would be very useful to be able to customize this parameter. 

```
[[daily logs]]
 - 15:00-16:00 Test
 - 16:15 Test without end
```

**Comment by haydenull** [comment]
Good idea, I am planning to add this feature.

**Comment by haydenull** [comment]
1.4.0 already supports custom duration.

**Comment by haydenull** [comment]
Due to no reply for a long time, I will close this issue, please reopen it if there is any problem.
