### ISSUE TITLE
Nextcloud subscription error

### ISSUE THREAD

**Issue by krillin666** [haydenull/logseq-plugin-agenda#20]
Hey @haydenull , thank you so much for this amazing and useful plugin !

I'm on 1.9.4 and using a subscription link from my personal Nextcloud instance. If I open this link on the web, it prompts for the download of an *ics* file, just like a Google Calendar link works.

The error on the notification window in Logseq is the following: `Parse Calendar Personal data error
TypeError: Cannot read properties of undefined (reading 'value')`

Inspecting the DEV console, I see these errors:
![image](https://user-images.githubusercontent.com/60305303/158639815-34ec81fe-2bf2-4367-a085-81b2dfdee605.png)

FYI, I have recurring events in this calendar, if it matters.

**Comment by haydenull** [comment]
My guess is that there was an error reading the event summary or dtstart.
Can you give me a subscription address or ics file where private information is hidden?

**Comment by krillin666** [comment]
Sent you a PM. Thank you for your time !

**Comment by haydenull** [comment]
The URL you gave me seems to display correctly.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/17695989/158798881-1de70c17-ca0a-4383-b92d-456eeec6e2b4.png">

**Comment by krillin666** [comment]
Ok very weird, it is also displaying correctly for me with this test 
calendar I created. However, my other to Personal and Work calendars are 
not giving the same error. I'll send you my work calendar so you can 
test please.

Thank you !

**Comment by haydenull** [comment]
1.9.5 version solves this problem.

I have already send the wrong calendar event to your mailbox.
