### ISSUE TITLE
Event is set to "All Day" when creating an agenda from calendar page using drag and drop

### ISSUE THREAD

**Issue by abadfr** [haydenull/logseq-plugin-agenda#200]
Hi! Thanks for making this calendar plugin! I just wanted to report what I think is a bug.

In the calendar page, if I create an event when dragging, what I think should happen is that the event will be set on the time I dragged over (in this case, 4-7am)
![image](https://user-images.githubusercontent.com/33151589/233734621-57493fc4-519c-4d4f-8b64-2c1bbd05d80f.png)

but when the "Modify Schedule" pops in, "All day" is set to Yes.
![image](https://user-images.githubusercontent.com/33151589/233734365-556d42a8-dd53-4dae-95c3-26d445303150.png)

and the time only appears if I manually set "All day" to "No"
![image](https://user-images.githubusercontent.com/33151589/233734744-41aaa812-1216-4305-8317-4bff889f4ae8.png)

**Comment by denys-klymenko-sigma** [comment]
I have the same issue

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.

**Comment by abadfr** [comment]
The new calendar is amazing, thank you!
