### ISSUE TITLE
Referenced TODOs label:feature-request

### ISSUE THREAD

**Issue by coballester** [haydenull/logseq-plugin-agenda#201]
In some situations, I write tasks in the journal as references to TODO tasks contained in projects (pages).
For instance, a task may appear in today's journal as ((6453b20a-0XX-4fss3-07c4-da6dddd2cd98)). This allows me to tick the task in the journal or in the project, as I wish.
Currently these journal tasks do not appear in the Agenda calendar, since they are simply references.

**Comment by haydenull** [comment]
The task is not displayed in the calendar because there is no specific date.

Since the task may be referenced by multiple pages, it is not suitable to use referencing page as a date.

For your situation, you can specify a date in the task block or move the task to the journal.
