### ISSUE TITLE
Daily Log 什么任务都没有显示

### ISSUE THREAD

**Issue by sa33sa** [haydenull/logseq-plugin-agenda#204]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Daily Log 什么任务都没有显示
已尝试过各种方式，
带时间戳的记录、待办、完成，都没显示
已经更新到最新版v2.15.2

### Reproduce the Bug

记录Daily log 后，在Daily log 页面查看，没有看到记录

### Screenshots

<img width="1366" alt="QQ20230516-112030@2x" src="https://github.com/haydenull/logseq-plugin-agenda/assets/21238081/d6d19a83-9f1d-4822-8a97-648f67384880">
<img width="256" alt="QQ20230516-111936@2x" src="https://github.com/haydenull/logseq-plugin-agenda/assets/21238081/5dabbbf7-adb2-41a5-a9ce-c2642d2ce7f8">

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
可以贴一下插件设置吗，在这里可以找到。注意隐藏下敏感信息，如果有的话
<img width="1235" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/c3639323-ea14-4495-8dfd-8a926f04913c">

**Comment by sa33sa** [comment]
> 可以贴一下插件设置吗，在这里可以找到。注意隐藏下敏感信息，如果有的话 <img alt="image" width="1235" src="https://user-images.githubusercontent.com/17695989/238822505-c3639323-ea14-4495-8dfd-8a926f04913c.png">
{
  "disabled": false,
  "theme": "auto",
  "defaultView": "month",
  "weekStartDay": 1,
  "defaultDuration": {
    "value": 0.5,
    "unit": "h"
  },
  "calendarList": [],
  "subscriptionList": [
    {
      "url": "https://www.shuyz.com/githubfiles/china-holiday-calender/master/holidayCal.ics",
      "id": "节假日",
      "bgColor": "rgba(231, 197, 177, 1)",
      "textColor": "#333333",
      "enabled": true,
      "borderColor": "rgba(231, 197, 177, 1)"
    },
    {
      "url": "",
      "id": "滴答清单",
      "enabled": true,
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)"
    }
  ],
  "initialized": true,
  "logKey": {
    "id": "Daily Log",
    "bgColor": "rgba(192, 202, 51, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(192, 202, 51, 1)",
    "enabled": true
  },
  "projectList": [
    {
      "id": "PJ calendar",
      "bgColor": "rgba(253, 219, 137, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(253, 219, 137, 1)",
      "enabled": true
    },
    {
      "id": "P&R",
      "bgColor": "rgba(151, 218, 251, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(151, 218, 251, 1)",
      "enabled": true
    },
    {
      "id": "UnderlyingStructure",
      "bgColor": "rgba(215, 201, 248, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(215, 201, 248, 1)",
      "enabled": true
    },
    {
      "id": "滴答清单完成",
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)",
      "enabled": true
    },
    {
      "id": "PJ-超跌均线集中便捷选股",
      "bgColor": "rgba(240, 147, 0, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(240, 147, 0, 1)",
      "enabled": true
    }
  ],
  "lightThemeType": "green",
  "homePage": "calendar",
  "ignoreTag": null,
  "journal": {
    "id": "Journal",
    "bgColor": "rgba(140, 227, 194, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(140, 227, 194, 1)",
    "query": [
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/deadline)]\n(not [(missing? $ ?block :block/scheduled)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/scheduled)]\n(not [(missing? $ ?block :block/deadline)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "deadline",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull\n?block\n[:block/uuid\n  :db/id\n  :block/parent\n  :block/left\n  :block/collapsed?\n  :block/format\n  :block/_refs\n  :block/path-refs\n  :block/tags\n  :block/content\n  :block/marker\n  :block/priority\n  :block/properties\n  :block/pre-block?\n  :block/scheduled\n  :block/deadline\n  :block/repeated?\n  :block/created-at\n  :block/updated-at\n  :block/file\n  :block/heading-level\n  {:block/page\n  [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])\n:where\n[?block :block/page ?page]\n[?page :block/journal? true]\n[?block :block/marker ?marker]\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]\n[(missing? $ ?block :block/scheduled)]\n[(missing? $ ?block :block/deadline)]]\n        ",
        "scheduleStart": "page.journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull\n  ?block\n  [:block/uuid\n    :block/parent\n    :db/id\n    :block/left\n    :block/collapsed?\n    :block/format\n    :block/_refs\n    :block/path-refs\n    :block/tags\n    :block/content\n    :block/marker\n    :block/priority\n    :block/properties\n    :block/pre-block?\n    :block/scheduled\n    :block/deadline\n    :block/repeated?\n    :block/created-at\n    :block/updated-at\n    :block/file\n    :block/heading-level\n    {:block/page\n      [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}\n    {:block/refs\n      [:block/journal-day]}])\n  :where\n  [?block :block/marker ?marker]\n  [?rp :block/journal? true]\n  [?block :block/refs ?rp]\n  [(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "refs[0].journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?rp :block/name \"milestone\"]\n[?block :block/scheduled]\n[?block :block/refs ?rp]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": true,
        "queryType": "advanced"
      }
    ],
    "enabled": true
  },
  "weekHourStart": 9,
  "weekHourEnd": 24,
  "pomodoro": {
    "pomodoro": 25,
    "shortBreak": 5,
    "longBreak": 15,
    "longBreakInterval": 4,
    "commonPomodoros": [
      10,
      15,
      20,
      25,
      40
    ]
  },
  "todoist": {},
  "dailyLogTagList": 1,
  "language": "en",
  "openai": {
    "apiBaseUrl": "https://api.openai.com"
  }
}
{
  "disabled": false,
  "theme": "auto",
  "defaultView": "month",
  "weekStartDay": 1,
  "defaultDuration": {
    "value": 0.5,
    "unit": "h"
  },
  "calendarList": [],
  "subscriptionList": [
    {
      "url": "https://www.shuyz.com/githubfiles/china-holiday-calender/master/holidayCal.ics",
      "id": "节假日",
      "bgColor": "rgba(231, 197, 177, 1)",
      "textColor": "#333333",
      "enabled": true,
      "borderColor": "rgba(231, 197, 177, 1)"
    },
    {
      "url": "",
      "id": "滴答清单",
      "enabled": true,
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)"
    }
  ],
  "initialized": true,
  "logKey": {
    "id": "Daily Log",
    "bgColor": "rgba(192, 202, 51, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(192, 202, 51, 1)",
    "enabled": true
  },
  "projectList": [
    {
      "id": "PJ calendar",
      "bgColor": "rgba(253, 219, 137, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(253, 219, 137, 1)",
      "enabled": true
    },
    {
      "id": "P&R",
      "bgColor": "rgba(151, 218, 251, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(151, 218, 251, 1)",
      "enabled": true
    },
    {
      "id": "UnderlyingStructure",
      "bgColor": "rgba(215, 201, 248, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(215, 201, 248, 1)",
      "enabled": true
    },
    {
      "id": "滴答清单完成",
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)",
      "enabled": true
    },
    {
      "id": "PJ-炒股软件学习",
      "bgColor": "rgba(240, 147, 0, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(240, 147, 0, 1)",
      "enabled": true
    },
    {
      "id": "PJ-热31便捷选股",
      "bgColor": "rgba(240, 147, 0, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(240, 147, 0, 1)",
      "enabled": true
    },
    {
      "id": "PJ-超跌均线集中便捷选股",
      "bgColor": "rgba(240, 147, 0, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(240, 147, 0, 1)",
      "enabled": true
    },
    {
      "id": "PJ-AI工具学习应用",
      "bgColor": "#b8e986",
      "textColor": "#4a4a4a",
      "borderColor": "#047857",
      "enabled": true
    },
    {
      "id": "PJ-晓城天地房屋出租",
      "bgColor": "#b8e986",
      "textColor": "#4a4a4a",
      "borderColor": "#047857",
      "enabled": true
    }
  ],
  "lightThemeType": "green",
  "homePage": "calendar",
  "ignoreTag": null,
  "journal": {
    "id": "Journal",
    "bgColor": "rgba(140, 227, 194, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(140, 227, 194, 1)",
    "query": [
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/deadline)]\n(not [(missing? $ ?block :block/scheduled)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/scheduled)]\n(not [(missing? $ ?block :block/deadline)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "deadline",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull\n?block\n[:block/uuid\n  :db/id\n  :block/parent\n  :block/left\n  :block/collapsed?\n  :block/format\n  :block/_refs\n  :block/path-refs\n  :block/tags\n  :block/content\n  :block/marker\n  :block/priority\n  :block/properties\n  :block/pre-block?\n  :block/scheduled\n  :block/deadline\n  :block/repeated?\n  :block/created-at\n  :block/updated-at\n  :block/file\n  :block/heading-level\n  {:block/page\n  [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])\n:where\n[?block :block/page ?page]\n[?page :block/journal? true]\n[?block :block/marker ?marker]\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]\n[(missing? $ ?block :block/scheduled)]\n[(missing? $ ?block :block/deadline)]]\n        ",
        "scheduleStart": "page.journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull\n  ?block\n  [:block/uuid\n    :block/parent\n    :db/id\n    :block/left\n    :block/collapsed?\n    :block/format\n    :block/_refs\n    :block/path-refs\n    :block/tags\n    :block/content\n    :block/marker\n    :block/priority\n    :block/properties\n    :block/pre-block?\n    :block/scheduled\n    :block/deadline\n    :block/repeated?\n    :block/created-at\n    :block/updated-at\n    :block/file\n    :block/heading-level\n    {:block/page\n      [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}\n    {:block/refs\n      [:block/journal-day]}])\n  :where\n  [?block :block/marker ?marker]\n  [?rp :block/journal? true]\n  [?block :block/refs ?rp]\n  [(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "refs[0].journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?rp :block/name \"milestone\"]\n[?block :block/scheduled]\n[?block :block/refs ?rp]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": true,
        "queryType": "advanced"
      }
    ],
    "enabled": true
  },
  "weekHourStart": 9,
  "weekHourEnd": 24,
  "pomodoro": {
    "pomodoro": 25,
    "shortBreak": 5,
    "longBreak": 15,
    "longBreakInterval": 4,
    "commonPomodoros": [
      10,
      15,
      20,
      25,
      40
    ]
  },
  "todoist": {},
  "dailyLogTagList": 1,
  "language": "en",
  "openai": {
    "apiBaseUrl": "https://api.openai.com"
  }
}

麻烦帮忙看看啦，谢谢啦，这个插件太🐂啦

**Comment by sa33sa** [comment]
> 可以贴一下插件设置吗，在这里可以找到。注意隐藏下敏感信息，如果有的话 <img alt="image" width="1235" src="https://user-images.githubusercontent.com/17695989/238822505-c3639323-ea14-4495-8dfd-8a926f04913c.png">

{
  "disabled": false,
  "theme": "auto",
  "defaultView": "month",
  "weekStartDay": 1,
  "defaultDuration": {
    "value": 0.5,
    "unit": "h"
  },
  "calendarList": [],
  "subscriptionList": [
    {
      "url": "https://www.shuyz.com/githubfiles/china-holiday-calender/master/holidayCal.ics",
      "id": "节假日",
      "bgColor": "rgba(231, 197, 177, 1)",
      "textColor": "#333333",
      "enabled": true,
      "borderColor": "rgba(231, 197, 177, 1)"
    },
    {
      "url": "https://dida365.com/pub/calendar/feeds/ynvskrycrqot/basic.ics",
      "id": "滴答清单",
      "enabled": true,
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)"
    }
  ],
  "initialized": true,
  "logKey": {
    "id": "Daily Log",
    "bgColor": "rgba(192, 202, 51, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(192, 202, 51, 1)",
    "enabled": true
  },
  "projectList": [
    {
      "id": "PJ calendar",
      "bgColor": "rgba(253, 219, 137, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(253, 219, 137, 1)",
      "enabled": true
    },
    {
      "id": "P&R",
      "bgColor": "rgba(151, 218, 251, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(151, 218, 251, 1)",
      "enabled": true
    },
    {
      "id": "UnderlyingStructure",
      "bgColor": "rgba(215, 201, 248, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(215, 201, 248, 1)",
      "enabled": true
    },
    {
      "id": "滴答清单完成",
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)",
      "enabled": true
    },
    {
      "id": "PJ-超跌均线集中便捷选股",
      "bgColor": "rgba(240, 147, 0, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(240, 147, 0, 1)",
      "enabled": true
    }
  ],
  "lightThemeType": "green",
  "homePage": "calendar",
  "ignoreTag": null,
  "journal": {
    "id": "Journal",
    "bgColor": "rgba(140, 227, 194, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(140, 227, 194, 1)",
    "query": [
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/deadline)]\n(not [(missing? $ ?block :block/scheduled)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/scheduled)]\n(not [(missing? $ ?block :block/deadline)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "deadline",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull\n?block\n[:block/uuid\n  :db/id\n  :block/parent\n  :block/left\n  :block/collapsed?\n  :block/format\n  :block/_refs\n  :block/path-refs\n  :block/tags\n  :block/content\n  :block/marker\n  :block/priority\n  :block/properties\n  :block/pre-block?\n  :block/scheduled\n  :block/deadline\n  :block/repeated?\n  :block/created-at\n  :block/updated-at\n  :block/file\n  :block/heading-level\n  {:block/page\n  [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])\n:where\n[?block :block/page ?page]\n[?page :block/journal? true]\n[?block :block/marker ?marker]\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]\n[(missing? $ ?block :block/scheduled)]\n[(missing? $ ?block :block/deadline)]]\n        ",
        "scheduleStart": "page.journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull\n  ?block\n  [:block/uuid\n    :block/parent\n    :db/id\n    :block/left\n    :block/collapsed?\n    :block/format\n    :block/_refs\n    :block/path-refs\n    :block/tags\n    :block/content\n    :block/marker\n    :block/priority\n    :block/properties\n    :block/pre-block?\n    :block/scheduled\n    :block/deadline\n    :block/repeated?\n    :block/created-at\n    :block/updated-at\n    :block/file\n    :block/heading-level\n    {:block/page\n      [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}\n    {:block/refs\n      [:block/journal-day]}])\n  :where\n  [?block :block/marker ?marker]\n  [?rp :block/journal? true]\n  [?block :block/refs ?rp]\n  [(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "refs[0].journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?rp :block/name \"milestone\"]\n[?block :block/scheduled]\n[?block :block/refs ?rp]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": true,
        "queryType": "advanced"
      }
    ],
    "enabled": true
  },
  "weekHourStart": 9,
  "weekHourEnd": 24,
  "pomodoro": {
    "pomodoro": 25,
    "shortBreak": 5,
    "longBreak": 15,
    "longBreakInterval": 4,
    "commonPomodoros": [
      10,
      15,
      20,
      25,
      40
    ]
  },
  "todoist": {},
  "dailyLogTagList": 1,
  "language": "en",
  "openai": {
    "apiBaseUrl": "https://api.openai.com"
  }
}

麻烦帮忙看看啦，谢谢🙏啦，这个插件太🐂啦

**Comment by sa33sa** [comment]
> 可以贴一下插件设置吗，在这里可以找到。注意隐藏下敏感信息，如果有的话 <img alt="image" width="1235" src="https://user-images.githubusercontent.com/17695989/238822505-c3639323-ea14-4495-8dfd-8a926f04913c.png">

{
  "disabled": false,
  "theme": "auto",
  "defaultView": "month",
  "weekStartDay": 1,
  "defaultDuration": {
    "value": 0.5,
    "unit": "h"
  },
  "calendarList": [],
  "subscriptionList": [
    {
      "url": "https://www.shuyz.com/githubfiles/china-holiday-calender/master/holidayCal.ics",
      "id": "节假日",
      "bgColor": "rgba(231, 197, 177, 1)",
      "textColor": "#333333",
      "enabled": true,
      "borderColor": "rgba(231, 197, 177, 1)"
    },
    {
      "url": "",
      "id": "滴答清单",
      "enabled": true,
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)"
    }
  ],
  "initialized": true,
  "logKey": {
    "id": "Daily Log",
    "bgColor": "rgba(192, 202, 51, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(192, 202, 51, 1)",
    "enabled": true
  },
  "projectList": [
    {
      "id": "PJ calendar",
      "bgColor": "rgba(253, 219, 137, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(253, 219, 137, 1)",
      "enabled": true
    },
    {
      "id": "P&R",
      "bgColor": "rgba(151, 218, 251, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(151, 218, 251, 1)",
      "enabled": true
    },
    {
      "id": "UnderlyingStructure",
      "bgColor": "rgba(215, 201, 248, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(215, 201, 248, 1)",
      "enabled": true
    },
    {
      "id": "滴答清单完成",
      "bgColor": "rgba(183, 214, 253, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(183, 214, 253, 1)",
      "enabled": true
    },
    {
      "id": "PJ-超跌均线集中便捷选股",
      "bgColor": "rgba(240, 147, 0, 1)",
      "textColor": "#333333",
      "borderColor": "rgba(240, 147, 0, 1)",
      "enabled": true
    }
  ],
  "lightThemeType": "green",
  "homePage": "calendar",
  "ignoreTag": null,
  "journal": {
    "id": "Journal",
    "bgColor": "rgba(140, 227, 194, 1)",
    "textColor": "#333333",
    "borderColor": "rgba(140, 227, 194, 1)",
    "query": [
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/deadline)]\n(not [(missing? $ ?block :block/scheduled)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?block :block/marker ?marker]\n[(missing? $ ?block :block/scheduled)]\n(not [(missing? $ ?block :block/deadline)])\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "deadline",
        "dateFormatter": "yyyyMMdd",
        "queryType": "advanced",
        "isMilestone": false
      },
      {
        "script": "\n[:find (pull\n?block\n[:block/uuid\n  :db/id\n  :block/parent\n  :block/left\n  :block/collapsed?\n  :block/format\n  :block/_refs\n  :block/path-refs\n  :block/tags\n  :block/content\n  :block/marker\n  :block/priority\n  :block/properties\n  :block/pre-block?\n  :block/scheduled\n  :block/deadline\n  :block/repeated?\n  :block/created-at\n  :block/updated-at\n  :block/file\n  :block/heading-level\n  {:block/page\n  [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])\n:where\n[?block :block/page ?page]\n[?page :block/journal? true]\n[?block :block/marker ?marker]\n[(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]\n[(missing? $ ?block :block/scheduled)]\n[(missing? $ ?block :block/deadline)]]\n        ",
        "scheduleStart": "page.journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull\n  ?block\n  [:block/uuid\n    :block/parent\n    :db/id\n    :block/left\n    :block/collapsed?\n    :block/format\n    :block/_refs\n    :block/path-refs\n    :block/tags\n    :block/content\n    :block/marker\n    :block/priority\n    :block/properties\n    :block/pre-block?\n    :block/scheduled\n    :block/deadline\n    :block/repeated?\n    :block/created-at\n    :block/updated-at\n    :block/file\n    :block/heading-level\n    {:block/page\n      [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}\n    {:block/refs\n      [:block/journal-day]}])\n  :where\n  [?block :block/marker ?marker]\n  [?rp :block/journal? true]\n  [?block :block/refs ?rp]\n  [(contains? #{\"TODO\" \"DOING\" \"NOW\" \"LATER\" \"WAITING\" \"DONE\"} ?marker)]]\n        ",
        "scheduleStart": "refs[0].journal-day",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": false,
        "queryType": "advanced"
      },
      {
        "script": "\n[:find (pull ?block [*])\n:where\n[?rp :block/name \"milestone\"]\n[?block :block/scheduled]\n[?block :block/refs ?rp]]\n        ",
        "scheduleStart": "scheduled",
        "dateFormatter": "yyyyMMdd",
        "isMilestone": true,
        "queryType": "advanced"
      }
    ],
    "enabled": true
  },
  "weekHourStart": 9,
  "weekHourEnd": 24,
  "pomodoro": {
    "pomodoro": 25,
    "shortBreak": 5,
    "longBreak": 15,
    "longBreakInterval": 4,
    "commonPomodoros": [
      10,
      15,
      20,
      25,
      40
    ]
  },
  "todoist": {},
  "dailyLogTagList": 1,
  "language": "en",
  "openai": {
    "apiBaseUrl": "https://api.openai.com"
  }
}


麻烦帮忙看看啦，🙏谢谢啦，这个插件太🐂啦

**Comment by sa33sa** [comment]
> 可以贴一下插件设置吗，在这里可以找到。注意隐藏下敏感信息，如果有的话 <img alt="image" width="1235" src="https://user-images.githubusercontent.com/17695989/238822505-c3639323-ea14-4495-8dfd-8a926f04913c.png">

我试了下，在另一台电脑的v2.13.0 版本上是正常显示的，可能电脑问题或者版本问题？

**Comment by sa33sa** [comment]
> 可以贴一下插件设置吗，在这里可以找到。注意隐藏下敏感信息，如果有的话 <img alt="image" width="1235" src="https://user-images.githubusercontent.com/17695989/238822505-c3639323-ea14-4495-8dfd-8a926f04913c.png">

试了一下，v2.13.0 版本 daily log在我的两台mac上可用，但是最新版本用不了

**Comment by haydenull** [comment]
我现在在外面，着急的话可以

"dailyLogTagList": 1,

把这一行删掉试试。目测是daily log tag设置的是出了点问题。

**Comment by sa33sa** [comment]
> 我现在在外面，着急的话可以
> 
> "dailyLogTagList": 1,
> 
> 把这一行删掉试试。目测是daily log tag设置的时候出了点问题。

不急，现在我安装回v2.13.0 版本，已经都正常使用，谢谢啦

**Comment by sa33sa** [comment]
> 我现在在外面，着急的话可以
> 
> "dailyLogTagList": 1,
> 
> 把这一行删掉试试。目测是daily log tag设置的时候出了点问题。

试了下是从2.14.0版本开始后，不显示的

**Comment by haydenull** [comment]
v2.15.3 应该可以了，可以再试试
