### ISSUE TITLE
0.9.9版中新的UI设计导致无法点击agenda图标

### ISSUE THREAD

**Issue by artemith** [haydenull/logseq-plugin-agenda#207]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

0.9.9版的logseq中更新了UI设计，可以隐藏标题栏。隐藏标题栏后，无法点击agenda图标
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/14881525/d30fc4d6-d26e-4968-a8cd-9a5bb9379cae)

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/14881525/5f857697-9862-41ca-ab3c-a1463e505663)

### Reproduce the Bug

1. 关闭标题栏
2. 在任务前的点上点击右键，选择Agenda: Start Pomodoro Timer
3. 尝试点击Agenda的时间图标

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Version 2.15.4 has fixed this issue, you can give it another try.
