### ISSUE TITLE
在可视化calendar中拖拽、拉伸或缩短任务的时长会导致页面向下滚动，并使得页面最下方不可见

### ISSUE THREAD

**Issue by dongtsi** [haydenull/logseq-plugin-agenda#209]
在calendar中拖拽、拉伸或缩短任务的时长会导致页面向下滚动，并使得页面最下方不可见

换句话说，多次操作会导致23:00-0:00这段时间不可见

刷新（重新进入calendar）可以解决这个问题

windows desktop client v0.9.8
Agenda v2.15.4

**Comment by haydenull** [comment]
是在周视图中拖动任务导致 23 点到 0 点时间轴消失吗？我这边试了下没复现，可以发个录屏么

**Comment by dongtsi** [comment]
好的，不是消失，是显示不出来了：
![test](https://github.com/haydenull/logseq-plugin-agenda/assets/43784905/f2c97638-f914-451c-92c8-f9f6e36145f5)

**Comment by haydenull** [comment]
Agenda3 使用了新的日历组件，可以试试

**Comment by dongtsi** [comment]
谢谢！
