### ISSUE TITLE
Feature Request: Add Repeat Functionality in Schedule

### ISSUE THREAD

**Issue by michaelmyc** [haydenull/logseq-plugin-agenda#210]
Currently, the `/schedule` functionality built into Logseq can allow user to repeat todo items, but using the `/schedule` block means the Agenda plugin will assign the default duration to the task. Is it possible to add "repeat every x" functionality to the scheduling function for Agenda?

**Comment by haydenull** [comment]
The recurring tasks are planned, but I haven't figured out how to make them compatible with the format of logseq itself yet.

**Comment by michaelmyc** [comment]
Glad to know that this feature is planned. 

Can you elaborate on what you mean by "make them compatible with the format of logseq itself"? 

Also, I think one thing that is easy to miss is that the calendar, timeline, and gantt views need to show the recurring tasks correctly (dynamic generation based on rules).

**Comment by haydenull** [comment]
Logseq's schedule has repeat function, and I need to research what sets it apart from Todoist.

<img width="662" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/3c7f2ea1-1465-4598-a2e1-3098a012806a">

**Comment by michaelmyc** [comment]
I see. I haven't used Todoist in a long time so I don't think I can contribute to that. 

My understanding of the Logseq repeat functionality is that it is just a regular task with modified behavior on finishing the task. Rather than setting the task to "DONE", it will change the scheduled time to the next iteration. It even disregards the current date, so if I have a task scheduled to 3 weeks later that repeats every week, and I can finish the task now and the scheduled time will be pushed 1 week later to 4 weeks.

**Comment by haydenull** [comment]
Agenda3 supports recurring tasks, you can give it a try.

**Comment by haydenull** [comment]
Currently, you can use logseq scheduled.

<img width="545" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/52792d1d-dc24-4286-8683-efa5cf1d0f18">
