### ISSUE TITLE
在设置里选择语言为中文，并没有切换到中文界面

### ISSUE THREAD

**Issue by xu-zhiyong** [haydenull/logseq-plugin-agenda#213]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

logseq 9.10
agenda 2.15.4

在agenda的设置里basic选项卡中看到了 language 选项，选中了中文，但界面并没有切换到中文。是我对这个功能理解错误吗？ 

### Reproduce the Bug

1、点击 设置 图标
2、选择 basic 选项卡
3、选择language右侧下拉框，选中中文

### Screenshots

<img width="786" alt="微信截图_20230628123016" src="https://github.com/haydenull/logseq-plugin-agenda/assets/13957712/1891cebb-3a40-44fd-9db5-628b69c67cf8">

### Environment Information

logseq 9.10
agenda 2.15.4

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
是插件的问题，是有计划做中文版的，但是还没完成。目前这个设置只会影响到用 openai 接口创建任务时候使用的语言

**Comment by xu-zhiyong** [comment]
> 
谢谢回复，非常期待。虽然英文也不难，我喜欢中文菜单对齐后的美感。

**Comment by xu-zhiyong** [comment]
问题解决。
