### ISSUE TITLE
Feature Request: Select subset of tasks from journal

### ISSUE THREAD

**Issue by mcopik** [haydenull/logseq-plugin-agenda#216]
Hi!

As I proposed [earlier in issue #158](https://github.com/haydenull/logseq-plugin-agenda/issues/158#issuecomment-1368023609), the Agenda plugin could be much more useful for people "gathering" tasks in journal pages. There, we have "daily" tasks, often with explicit time allocation, and "future" tasks that are gathered under meeting and project-specific notes in the form of a daily log. Currently, all tasks from a journal page are gathered by the plugin and assigned to the calendar with the journal's page day unless they are explicitly scheduled. It would have been great to take a subset of them.

For example, Agenda is very difficult to introduce into your daily workflow if you have one or two years of TODOs in "daily log", and many of them might be "zombies".

Would such an extension be possible?

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/720619/01ca3f4e-92dd-4a88-8ed4-82d691388313)

**Comment by haydenull** [comment]
Currently, the plugin supports ignoring tasks with specific tag. Do you think this can meet your needs?

<img width="1069" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/875a4d4b-dc83-4a6d-a0dc-1002d2266608">


<img width="557" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/1f9dd375-d4a3-4601-a387-eda7c5a4d49c">

**Comment by mcopik** [comment]
@haydenull Thanks, this helps! It's not ideal since I might have to tag all TODOs separately, but it's a great improvement.

Ideally, we could look if the parent block is tagged with the ignore tag. [Looking at the code](https://github.com/haydenull/logseq-plugin-agenda/blob/2977810df16da956afc7155ad724b98dce82294f/src/util/events.ts#L193), we could modify the query to look for parents as well. Do you think it would be a useful addition to the plugin?

**Comment by haydenull** [comment]
I think this idea is great, and perhaps it can also be used to implement subtask functionality.

**Comment by haydenull** [comment]
Agenda3 supports custom filters, you can give it a try.

**Comment by mcopik** [comment]
@haydenull Do you have an example of using that somewhere? I couldn't find it in the documentation.

I tried providing the following query: `{{query [[ignore-agenda]] }}`, but it seems to have no effect.

**Comment by haydenull** [comment]
@mcopik here is the document

[document](https://www.notion.so/haydenut/English-fd47d1843e654f5485a07ef4935ed365#3551ed1a690e4e8695aa7cb30d290ffe)
