### ISSUE TITLE
Feature request: Include all todo's from namespace

### ISSUE THREAD

**Issue by fl-la** [haydenull/logseq-plugin-agenda#217]
Hi,
(it might that I oversee something already existing)
it might be pretty useful if there is an option to include all todo's from a namespace. 
E.g. having the namespace N with subpages N/M and N/O. I often add todo's in N/M and N/O, but not in N. I would to see all the todos in the agenda plugin setting the project to N instead of creating two projects for N/M and N/O.
@haydenull

**Comment by haydenull** [comment]
May I ask what is your use case like?

For me, it is necessary to distinguish between the task of N/M and N/O, because they belong to different project.

**Comment by fl-la** [comment]
Understood.

An example: I have aaaa lot of paper to review. I like to keep stuff together, so I add TODOs within the page where I summarize the paper (with other plugins). All papers are within the namespace 'paper', so it looks like paper/paper1, paper/paper2 and so on.
I would be neat to have an option to summarize all todo's from the namespace into one project. 
I saw the config file where you defined queries for the journal. Is the plugin somehow overwriting settings if I add a query to that project including all TODOs from the namespace?

**Comment by haydenull** [comment]
Agenda indeed has the functionality of a custom calendar, which allows you to write your own query to define search rules.

**Comment by fl-la** [comment]
I saw this. But this is only active for calendars, is it? I mean, there is nothing in the project-view regarding this?
