### ISSUE TITLE
Wrong presentation for events crossing midnight

### ISSUE THREAD

**Issue by jh-xu** [haydenull/logseq-plugin-agenda#218]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Thank you so much for the nice plugin! I am using it everyday and love it very much!

I find it does not handle the events crossing midnight correctly.

First, a todo like "TODO 23:00-01:00 something", is over due in the calendar which is wrong.
Second, such an event in the Daily Log, is placed at the end of the day in the calendar correctly but some time is missing. Additionally, it shows negative 22 hours for this event in the 'Day' view in the Daily Log for this event. 

### Reproduce the Bug

1. Go the journal page for today
2. Inside the Daily log block, create an event block: TODO 23:00-01:00 something #my_project
3. Go to Agenda calendar, it shows overdue
4. Go to Setting/Daily Log, include tag 'my_project'
5. Go to Daily Log/Calendar, it is at the end of day but the time range is wrong
6. Go to Daily Log/Day, it is a negative hour for this project

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
The task design for journal is not indeed span multiple days, as the are only applicable for the current day.  Other regular tasks can support spanning across multiple days.
