### ISSUE TITLE
希望增加筛选器快速切换条件

### ISSUE THREAD

**Issue by SeyeeL** [haydenull/logseq-plugin-agenda#22]
![image](https://user-images.githubusercontent.com/71479570/159127270-b4b33b32-764b-4528-b19d-d900ac5ca424.png)
目前的路径好像要先点设置再切换

**Comment by haydenull** [comment]
你这边对哪些筛选项有快捷操作的需求呢

**Comment by SeyeeL** [comment]
想了一下创建日历本身已经有筛选条件了，我还没有尝试不同日历的筛选结果里有共同事件会怎么展示。大概就是有一个下拉框可以像视图切换一样直接切换展示条件。

因为有时候想只看milestones有时候想看daily log 以后我可能还会做书单影单日历，可以快速切换视图

**Comment by haydenull** [comment]
不同日历里相同的事件，理论上都会在日历视图中出现。
我理解你是想要快速控制某个日历显示或隐藏？

**Comment by SeyeeL** [comment]
是的，因为目前得去设置里调整，想在首页就有下拉框选择

**Comment by haydenull** [comment]
1.12.0 增加了侧边栏快速显隐日历
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/17695989/159690966-9e9ea8fa-a572-40d2-b7af-0934814a1e29.png">

**Comment by SeyeeL** [comment]
这速度超强啊！！！快贴coffee

**Comment by haydenull** [comment]
感谢，readme里已经贴上了
