### ISSUE TITLE
Logseq agenda no longer working in showing TODO and tasks

### ISSUE THREAD

**Issue by SiaoInspired** [haydenull/logseq-plugin-agenda#222]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Logseq agenda no longer working in showing TODO and tasks

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/129584378/eec7ac35-5a98-4dda-8a9c-87bada1f8658)

### Reproduce the Bug

open logseq agenda
no task or TODO shown

### Environment Information

Logseq version is 
        versionCode 66
        versionName "0.9.13"
        
        Desktop

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
May I ask if the task has been unable display all along, or is this a recent issue?

**Comment by SiaoInspired** [comment]
First of all thank you for creating this very useful app

Secondly to answer your question. This is very recent issue

**Comment by haydenull** [comment]
I think there might be a problem with the plugin configuration. You can try reseting it or you can remove any sensitive information from the configuration and send it to me for testing.

<img width="1568" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/011ec717-1d39-46b2-b889-ad3472c8970e">

**Comment by SiaoInspired** [comment]
I restored defaults many times. 

How do I send it to you? What should I do to assist you

**Comment by haydenull** [comment]
You can send it to my email: hayden.chen.dev@gmail.com

Find the configuration file from the installed plugins, and it should be a json file.
<img width="1288" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/60b0ef85-2a5c-4674-a70c-fac5ac3897ec">

**Comment by SiaoInspired** [comment]
Hi. I uninstalled logseq and reinstalled it ... It worked again. 

I will still send you the json

The before and after
