### ISSUE TITLE
Feature!! - show the todo under the project that is referenced.

### ISSUE THREAD

**Issue by BxDorn** [haydenull/logseq-plugin-agenda#224]
So everything i do starts in the journal, would be great to be able to create a TODO in the journal and either reference the project with [[projectA]] or with a '/' command (maybe /agenda-project)  and the TODO would not show in journal but rather show under the project in agenda.

**Comment by haydenull** [comment]
Maybe you can try project property, the document is [here](https://haydenull.github.io/logseq-plugin-agenda/introduction/events.html#journal-page-only)

<img width="769" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/94dfa372-0eb5-4c92-8966-cab54192cdc3">

**Comment by herrwusel** [comment]
@haydenull Thanks for the hint.

I would like to add – while there is a solution to this problem – that listing every TODO under a reference would be a very convenient way to manage projects TODOs.
