### ISSUE TITLE
How can past events be kept in the calendar without marking them Done?

### ISSUE THREAD

**Issue by pmqa** [haydenull/logseq-plugin-agenda#226]
Hello everyone,

Currently an event only gets added to the calendar if it's a todo, later, now type of tag. This is not a problem, the real problem is that if we don't mark these todo tags as done they'll be removed from the calendar view and be put on the top of the calendar. How can we keep them in their right time slot for past reference and organization?

<img width="598" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/8832333/076e4ad5-3501-47b0-9974-54e213471589">

Is there a way to solve this?

Thanks very much! This is an incredible plugin 🥇

**Comment by haydenull** [comment]
In my opinion, there are three situations for overdue tasks.

- If this task doesn't need to be completed, then I will set it as CANCELED.
- If this task needs to be completed at an uncertain time in the future, I will remove its time information and put it into backlog.
- If this task needs to be completed in the near future, then I will rescheduled it.

If a task has been overdue for a long time, It's likely not important or at least dose not require immediate attention.

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.
