### ISSUE TITLE
如何同时or方便的同步多个project到不同的页面呢

### ISSUE THREAD

**Issue by yaobik** [haydenull/logseq-plugin-agenda#227]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

rt

### Reproduce the Bug

要么是同步所有任务到一个页面,但是无法区分project
要么只能一次同步一个project

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
你是想查询今天的所有任务吗？或许可以看看侧边栏功能
