### ISSUE TITLE
希望增加甘特视图

### ISSUE THREAD

**Issue by SeyeeL** [haydenull/logseq-plugin-agenda#23]
比较方便看milestone

**Comment by haydenull** [comment]
现在milestone会有单独的小旗子图标，是需要在日历中更加醒目吗？

**Comment by SeyeeL** [comment]
甘特视图比较有那种时间轴流动的感觉，比如拉一年的重点关键词之类的

**Comment by haydenull** [comment]
像这样的时间轴怎么样呢？把日历中的 milestone 收集到一起展示到时间轴上。甘特图感觉有点太重了，大概搜了下还没找到好用的开源组件。
https://github.com/prabhuignoto/react-chrono

**Comment by SeyeeL** [comment]
这种看起来也不错，而且我就可以推荐给我一个想做历史时间轴的朋友了哈哈哈哈，不过到时候做成了可不可以设置横向和纵向，比如我就喜欢横向的~感谢~

**Comment by haydenull** [comment]
支持横向的

这个有新进展我会再 issue 里同步你

**Comment by SeyeeL** [comment]
太好了，谢谢

**Comment by haydenull** [comment]
1.14.0版本增加了甘特图视图

文档在这里https://haydenull.github.io/logseq-plugin-agenda/zh/views/gantt.html#简洁模式
