### ISSUE TITLE
Why remove open-ai related features?

### ISSUE THREAD

**Issue by dongtsi** [haydenull/logseq-plugin-agenda#233]
请问为什么要取消gpt编译任务的功能？（真的很好用 🤣

**Comment by haydenull** [comment]
主要原因是当时在做输入弹窗的改版，感觉这个功能当时设计的不太好，经常会有错误，所以给下了。旧版本的安装包还在 release 里可以找到。

Agenda3 还后续会想办法提高这方面的使用体验，到时候会再加回来的。
