### ISSUE TITLE
Show error

### ISSUE THREAD

**Issue by Lzzzs** [haydenull/logseq-plugin-agenda#234]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I type the **“Agenda: Insert Today's Task”** command, there is a problem with the typography of the pop-up box

<img width="979" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/74575471/fd48bc6b-cf0d-4c17-a740-2c5ef9ccb415">

### Reproduce the Bug

When I type the **“Agenda: Insert Today's Task”** command, there is a problem with the typography of the pop-up box

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
version 2.17.2 has been released, you can have a try.
