### ISSUE TITLE
when you link google calendar, show some bug

### ISSUE THREAD

**Issue by jellzone** [haydenull/logseq-plugin-agenda#235]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

please see the picture

Parse Calendar Google Cal data error
ParserError: invalid line (no token ";" or ":") "<!DOCTYPE html>"

### Reproduce the Bug

1. open subscription
2. fill in Google calendar
3. switch open button

### Screenshots

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/5356500/0726182b-3803-46b2-be10-08a31cd0ce01)

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Could you please provide a example link? There might be some special syntax that hasn't been adapted.

**Comment by drmandel01** [comment]
I am having the same issue (same error, as well). If you need additional information, please let me know.

**Comment by haydenull** [comment]
> I am having the same issue (same error, as well). If you need additional information, please let me know.

@drmandel01 Did you set the calendar to public? This is the [document](https://haydenull.github.io/logseq-plugin-agenda/settings/subscription.html#google-calendar)

**Comment by drmandel01** [comment]
Thanks for the link to the Google Calendar docs. I needed to paste the correct link (Public address in iCal format) into your settings.  Work very well. Thanks for all the hard work.
