### ISSUE TITLE
A feature request to support display the content of block reference 

### ISSUE THREAD

**Issue by fortunehan** [haydenull/logseq-plugin-agenda#24]
Hi haydenull,

Could I raise a feature request to support display the content of block reference? 
Currently, it just display the id of block reference in the calendar view.

**Comment by haydenull** [comment]
May I know how do you generally use block reference in your calendar?

**Comment by fortunehan** [comment]
Let me take an example. 
I have some goals blocks in other page, then I did something to one goal, I just copy its block reference to journal.

17:20 ((asdxxxxxx))

**Comment by haydenull** [comment]
Version 1.11.0 supports displaying the contents of the first block reference.

If there is a problem you can reopen the issue.
