### ISSUE TITLE
Feature request: 'MAKE RECURRING' functionality.

### ISSUE THREAD

**Issue by leicesterbrown** [haydenull/logseq-plugin-agenda#241]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

See pic. An awesome, and basic feature that would vastly improve use-ability is setting recurring, same-name tasks, via selection of days in calendar. 
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/149297816/c33cbc6b-5818-4246-8089-501cc73e3008)

### Reproduce the Bug

1. Go to the plugin
2. Select several days
3. Click one of them
4. Try to create the tasks
5. Get the error of not being able to.

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
You can switch another project

**Comment by haydenull** [comment]
In addition, Agenda3 supports native recurring tasks in logseq and is currently being tested.

This is [thedocument](https://haydenut.notion.site/Agenda3-ef115e277c864de3b2679d6bda0e6376).
