### ISSUE TITLE
Is this plugin capable of notifications? If not - why?

### ISSUE THREAD

**Issue by leicesterbrown** [haydenull/logseq-plugin-agenda#242]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Trying to figure out if the plugin can trigger audio/visual notifications, which is very important in scheduling/calendar software. Is this hard to do with LogSeq for some reason?

### Reproduce the Bug

1. Use plugin
2. Not find notification functionality.

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
I think it would be best to have server support for notifications. If we implement it on the client side, the notification feature will become unavailable when users close Logseq.

Agenda3 supports subscription by third-party software, perhaps subscribing with a third-party calendar app and using that app for more suitable notifications.
