### ISSUE TITLE
cannot set allDay=false in Agenda v3.0 through v2.x calendar view

### ISSUE THREAD

**Issue by dongtsi** [haydenull/logseq-plugin-agenda#243]
大佬好，关于v3.0, 有两个问题
1. bug：在3.0版本里，我在使用旧的（之前的2.x版本）日历视图上双击创建任务时，似乎无法把allDay=false（即使我选择了all day->No）
2. feature: 现在3.0和2.x的日历视图不一致，能不能把之前2.x中通过agenda schedule（#agenda://?start=xxx&end=xxx）而不是logseq SCHEDULE的也都显示在3.0的日历视图上？我之前所有的task都是通过agenda schedule的，现在在3.0的日历视图上都消失了qaq...

**Comment by haydenull** [comment]
1. 测试了一下以下选项是正常的，你那边具体是怎么操作的呢
<img width="557" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/20e27396-3fd1-499a-9c1f-dc5319297c9f">
<img width="412" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/8bd0cdf7-d3d7-438e-8e29-6c00c33bf22f">

2. 暂时不会了，Agenda3 会尽量使用 logseq 的原生语法，不过如果有需求我这边可以加个功能把 Agenda2 的自定义格式替换成 Scheduled

**Comment by dongtsi** [comment]
1. 我这边也复现不出来这个问题了，打扰了
2. 如果可以的话，那太感谢了

**Comment by dongtsi** [comment]
Hi，我能复现出1的bug了，在非jounral的其他页面下创建任务就会出现这个问题：
这里我创建了一个其他页面的任务，选择allDay=false:
![1](https://github.com/haydenull/logseq-plugin-agenda/assets/43784905/c1dd81ae-2d18-48f5-9679-c70feeb70e34)
但是最后还是显示在Allday里：
![2](https://github.com/haydenull/logseq-plugin-agenda/assets/43784905/1bf93b9c-6888-4de8-a643-6f5eec7441ae)

这条block对应的是 `TODO Test Project >[2023-11-20](#agenda://?start=1700442000000&end=1700443800000)`
这个在之前的版本中应该是 `TODO Test Project >[2023-11-20 9:00-9:30](#agenda://?start=1700442000000&end=1700443800000&allDay=false)`吧？

（#245 这里遇到的好像也是这个问题）

**Comment by haydenull** [comment]
可以试一下 3.3.0 版本

**Comment by dongtsi** [comment]
可以了，感谢！
