### ISSUE TITLE
Does plugin have issues with changed Journal date-format?

### ISSUE THREAD

**Issue by Rolograaf** [haydenull/logseq-plugin-agenda#245]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I use non standard dateformat:
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/6130902/92fa4f93-b533-4f14-a352-aa4d44b27f8c)

Setting start/end times is unreliable, will somtimes disappear, not show up, have to repeat setting it. Add another date to schedule block with /datepicker to show up in calendarview.

Is this issue related with my date-format?

Also setting the start/end times will still show as "All Day" en not on the correct day-timeline, see appointment 14:15-15:00
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/6130902/4cd571c9-d385-4c82-a4b4-de547bb99b8b)

### Reproduce the Bug

Enter Event with start/end times repeatedly untill it somewhat works

### Environment Information

Windows 10, App version v3.1.0 but using version 2 in effect since at work I cannot use HTTP API server, I think they closed the ports for security.

### Additional Context

Sorry I am not smart enough to make PR

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
3.x has two versions: plugin and web. The plugin version does not require an API server.

You can find the supported date formats for version 2.x in this [document](https://haydenull.github.io/logseq-plugin-agenda/introduction/events.html#no-ability-to-specify-times). I hope it can help you.
