### ISSUE TITLE
The new Agenda view closes itself a big part of Agenda's pomodoro timer

### ISSUE THREAD

**Issue by 0nxku** [haydenull/logseq-plugin-agenda#247]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The new Agenda view closes itself a big part of Agenda's pomodoro timer.

### Reproduce the Bug

1. Open the new Agenda view (Agenda beta), then you can close it.
2. Try to start Agenda's pomodoro timer.
3. The new view will be opened, and it will eclipse the pomodoro window.
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/150351410/6050dabf-6260-42d1-bdc5-bcb8e4e31251)

### Environment Information

Agenda 3.10.

### Additional Context

How to fix:
Open the old Agenda view, then close it and the pomodoro timer will be initiated normally.
But if you open the pomodoro timer while being in the old Agenda view it will be combined with a page you previously have opened.
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/150351410/0b54f8d4-f12e-48f6-bbe5-4beaf2aff147)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Sorry, it is not recommended to use Pomodoro with Agenda3 as Agenda3 cannot recognize the existing Pomodoro information.

Agedna3 uses logseq’s native timelog to record task time. You can use [Task Reminder plugin](https://github.com/sethyuan/logseq-plugin-task-reminder).

**Comment by 0nxku** [comment]
So it is generally not recommended to use Agenda v. 3 with Agenda v. 2?

If so, do you plan to add Agenda's v. 2 functions to Agenda v. 3?

**Comment by haydenull** [comment]
Yes, we hope that everyone can gradually transition to using Agenda3. Some of the features in Agenda2 will be migrated to version 3, while the remaining ones will be separated into new plugins.
