### ISSUE TITLE
Since the update 3.2 the agenda doesn't work 

### ISSUE THREAD

**Issue by ForPsych** [haydenull/logseq-plugin-agenda#248]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I have started Logseq and after the update the quick access to agenda on my Logseq (the icon star) is not longer in the bar and it seems it isn't running at all as I cannot access the calendar, nor anything. 

Thank you 

### Reproduce the Bug

1. I updated agenda from 3.1 to 3.2 
2. The icon for access the agenda is gone after. 
3. The agenda is intalled
4. I restarted Logseq. Nothing happens.
5. When I click on previous dates and times nothing happens. 

### Screenshots

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/114888942/10c4b521-6df6-4cd0-b1c0-f91773f20564)

### Environment Information

Windows 10, Logseq 0.9.20, Agenda 3.2

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Only the pinned icon will be displayed on toolbar. You can take a look.

<img width="266" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/d3346aad-b043-4da8-8e24-c4947c26c31d">

**Comment by ForPsych** [comment]
Hi Hayde,

Yes, that didn’t appeared until later in the afternoon. Maybe it was a conflict that fixed itself.

Thank you so much for your answer and your amazing contribution.

Have a great weekend!



Guadalupe
