### ISSUE TITLE
🙏求教：请问怎样在日历界面只显示[[📆今日计划]]底下的

### ISSUE THREAD

**Issue by sa33sa** [haydenull/logseq-plugin-agenda#250]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

我希望在日历界面能只显示[[📆今日计划]]底下的待办事项。
[[📆今日计划]]分布在journal页面里
我现在设置了project 页面 [[📆今日计划]]，还有custom query。但是所有待办都集中在一天。
我该怎样设置让待办显示在jounal 对应的日期❓
怎样让待办事项的顺序和内容页面一致❓

### Reproduce the Bug

[[📆今日计划]]分布在journal页面里
我现在设置了project 页面 [[📆今日计划]]，还有custom query。但是所有待办都集中在一天。

### Screenshots

![31F17CBA5C07A6A1D63915BEBD38B7C4](https://github.com/haydenull/logseq-plugin-agenda/assets/21238081/db7ad6f2-8a4b-4329-bb34-0bc526673186)

<img width="1037" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/21238081/54339e0d-caa2-4fb7-a14f-8c28b36987c4">

<img width="696" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/21238081/b68665fd-46ce-4412-884f-f518f41e1600">

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
<img width="969" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/2aeda3e1-c890-4a5a-b3ce-312fc72a7862">
可以试试 schedule start 设置为 `page.journalDay`

你这个错误原因应该是 simple query refs 没有返回详细数据，插件里有个播放按钮，点击会执行 query 并在控制台打印结果：
<img width="1217" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/297beb72-15e8-44a3-a575-6ca17ddb980b">

**Comment by haydenull** [comment]
可以试试将 schedule start 设置为 `page.journalDay`，Date Formatter 设置为 `yyyyMMdd`

Agenda 插件提供了播放按钮，点击会在控制台打印 query 结果，看起来 simple query 没有返回 refs 里的详细信息，只有一个 id
<img width="1215" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/f7f41e82-13bb-4e15-be5c-e0db206d4695">

**Comment by sa33sa** [comment]
> 可以试试将 schedule start 设置为 `page.journalDay`，Date Formatter 设置为 `yyyyMMdd`
> 
> Agenda 插件提供了播放按钮，点击会在控制台打印 query 结果，看起来 simple query 没有返回 refs 里的详细信息，只有一个 id <img alt="image" width="1215" src="https://user-images.githubusercontent.com/17695989/282681364-f7f41e82-13bb-4e15-be5c-e0db206d4695.png">

十分感谢🙏，现在任务都显示了。
另外请教下：
❓请问是否可以让日历界面的任务排序和journal 页面内容里的一致？因为排序体现了重要程度。现在是不一致的
❓ 能否调整内容大小，让月历界面的每日任务能显示3个，现在只能显示两个。因为希望能够一眼概览，本月每日对最重要的任务的完成执行情况

**Comment by haydenull** [comment]
1. 排序这个目前做不到，logseq 任务有优先级标签 ABC 可以试试
2. 这个目前也不行，你可以使用双周视图，这样能展示多一点。另外 Agend3 日历的展示内容会更多一些，不过 Agenda3 并不支持自定义 query 的日历

**Comment by sa33sa** [comment]
> 1. 排序这个目前做不到，logseq 任务有优先级标签 ABC 可以试试
> 2. 这个目前也不行，你可以使用双周视图，这样能展示多一点。另外 Agend3 日历的展示内容会更多一些，不过 Agenda3 并不支持自定义 query 的日历

谢谢
