### ISSUE TITLE
Themeing

### ISSUE THREAD

**Issue by turtaf** [haydenull/logseq-plugin-agenda#251]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I use dark theme in logseq and it would be nice if Agenda3 could inherit the theme as Agenda2 did

### Reproduce the Bug

Open Agenda3

### Environment Information

Logseq 0.9.20
Monokai Theme

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by heinwol** [comment]
Sorry for redundant info, but I personally would love to have (even a very simple) dark theme. I quite like agenda3, it's a big step forward compared to agenda2. Still, having all your desktop and apps (including logseq itself) dark themed and agenda3 supporting only light theme is... painful. Anyway, thanks for cool work you're doing, just hope this feature will arrive one day~

**Comment by haydenull** [comment]
Thank you for your feedback. This feature is currently in our development plan, but due to a high volume of other requirements, it will take some time to implement.

**Comment by shlomi-dr** [comment]
One more vote for dark theme for Agenda3. Thank you for this awesome plugin!!

**Comment by haydenull** [comment]
Version 3.10.1 has added support for dark mode adaptation, you can give it a try.
