### ISSUE TITLE
Cannot upload calendar with v3.6.0/1

### ISSUE THREAD

**Issue by dongtsi** [haydenull/logseq-plugin-agenda#254]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Cannot upload the calendar to GitHub repo with v3.6.0/1
I've checked with v3.3.0 and succeed  

### Reproduce the Bug

clicked upload icon

### Screenshots

The red dot upon the uploading icon keeps flashing but cannot successfully upload.

### Environment Information

lastest Logseq 
win 10 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
You can update to 3.6.2, which will display error message for easier troubleshooting.

Or you can open console to view network error messages.
<img width="856" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/a6a52371-499e-48fb-ba61-71291ed47122">

**Comment by dongtsi** [comment]
Great! Here is my error message:
> Upload failed
> Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by haydenull** [comment]
what version is the web? Can you please paste the output of the console?


![image](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/9dab1847-d68c-44c5-8bda-451c2985dab1)
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/3199f22e-b05c-4cf5-be65-44fc6e7640e4)

**Comment by dongtsi** [comment]
Sure, the version is v3.6.2
Here is the error:
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/43784905/969eee1d-d58c-4c1f-953e-d3c60edb633c)
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/43784905/6b3015e4-9482-4238-8f96-6f661146baa8)

**Comment by haydenull** [comment]
Please make sure that the screenshot includes RequestHeader and ResponseHeader.

By the way, may I ask if you are using Google Chrome browser and what version it is?

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/4e4a3d8d-d200-432a-93d3-c72eec1effd3)

**Comment by dongtsi** [comment]
latest version of Chrome. I've tried Edge, but same problem

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/43784905/4f5add13-d64d-4b37-a8ad-2263446a2a4b)

**Comment by haydenull** [comment]
It seems like Access-Control-Allow-Origin is missing.

One possibility is that the file content contains special characters, causing encoding failure on the server.

Can you create a simple test graph in logssq and then try again?

Or, if there is no sensitive information in the task, you can send me the detailed information.

<img width="589" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/6fe2ec7a-e3c8-426a-887b-a08411afddcd">

**Comment by dongtsi** [comment]
I created a test graph, and seems the failure is caused by the mixture of {English characters, 中文, and agenda 2 Pomodoro} in the task name. 🤣

Here is an example causing the uploading failure:
```
DONE [#A] a完成哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈 >[2023-11-16](#agenda://?start=1700064000000&end=1700150399999) >[🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅 380min](#agenda-pomo://?t=f-1700211726539-900%2Cf-1700215367246-2700%2Cf-1700226411808-3300%2Cf-1700229807172-900%2Cf-1700374688086-3300%2Cf-1700378031331-2100%2Cf-1700380148443-1500%2Cf-1700381928620-2100%2Cf-1700388385967-1500%2Cf-1700389894819-900%2Cf-1700395400879-900%2Cf-1700396309975-900%2Cf-1700397214163-900%2Cf-1700398117379-900)
SCHEDULED: <2023-11-19 Sun>
```
---

**But this one succeeds**: 
```
DONE [#A] a完成哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈 >[2023-11-16](#agenda://?start=1700064000000&end=1700150399999) >[🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅🍅 380min](#agenda-pomo://?t=f-1700211726539-900%2Cf-1700215367246-2700%2Cf-1700226411808-3300%2Cf-1700229807172-900%2Cf-1700374688086-3300%2Cf-1700378031331-2100%2Cf-1700380148443-1500%2Cf-1700381928620-2100%2Cf-1700388385967-1500%2Cf-1700389894819-900%2Cf-1700395400879-900%2Cf-1700396309975-900%2Cf-1700397214163-900%2Cf-1700398117379-900)
SCHEDULED: <2023-11-19 Sun>
```

**Comment by haydenull** [comment]
This issue occurs when generating an ics file, where the title will be wrapped at the 75th character. If an emoji happens to be at that position, it will result in an illegal character.

I have already submitted a PR to [ics](https://github.com/adamgibbons/ics). Once they fix it, the issue will be resolved.

https://github.com/adamgibbons/ics/issues/257

**Comment by dongtsi** [comment]
Much appreciated!
