### ISSUE TITLE
Week start day option

### ISSUE THREAD

**Issue by sharonv** [haydenull/logseq-plugin-agenda#255]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

There is no way to define that my work week starts on Sunday. is there an option (even in config) for that? thanks!

### Reproduce the Bug

1. Go to Agenda 3 > Calendar > week. Week and all week calculations start on Monday only.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
‌‌‌‌‌‌‌Version [3.11.0](https://github.com/haydenull/logseq-plugin-agenda/releases/tag/v3.11.0) supports this feature.
