### ISSUE TITLE
How to pull todo in todoist to logseq

### ISSUE THREAD

**Issue by RobertCheng-956** [haydenull/logseq-plugin-agenda#256]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello! I just see the agenda can pull todos from todoist to logseq, but I don't know how to do it. And I don't find it in the documentation, so I just wrote this question. Could you tell me how can I do so or where can I learn to do so.
Thanks!

### Reproduce the Bug

After I copy the api tokens to logseq, I can update the todo to todoist, but I don't know how to pull todo from todoist to logseq.

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
This is the feature of Agenda2. Here is the document:

https://haydenull.github.io/logseq-plugin-agenda/settings/todoist.html

**Comment by RobertCheng-956** [comment]
I saw this documentation. I don't know whether I should copy this api as the following pic:
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/44940678/76c8f2fd-e685-4e85-aa29-bb45df6304b2)
Or api tokens as the following pic:
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/44940678/bd399742-d7c5-4f2c-8e31-554bbf22d1b7)
I've tried both api, but both of them cannot pull todos in todoist to logseq(should I press some button in logseq or do anything else to pull todos?)

**Comment by haydenull** [comment]
Click this button, and paste the token into Agegnda2 settings.

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/c3ceac14-3265-470d-b5bf-9725524be625)
<img width="1159" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/799912cd-7cd8-4624-a696-96b0c4b55845">

Clicking on this button in the logseq toolbar will pull tasks from Todoist.
<img width="255" alt="image" src="https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/e452f44a-5c5e-4701-ae5a-b8e3f4953ac4">

**Comment by RobertCheng-956** [comment]
I did it~ Thank you very much
