### ISSUE TITLE
Flickering Agenda 3 view

### ISSUE THREAD

**Issue by cbyrohl** [haydenull/logseq-plugin-agenda#257]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The Agenda 3 view of Tasks/Calendar menu entries are constantly flickering on my system. I attached a gif. Note that the sampling rate of the screen capture is much slower than this change occurring. In reality, the flickering of this view occurs many times a second. The stdout of logseq shows no output related to the plugin. Let me know what additional debug information I can provide. Thanks!

### Reproduce the Bug

(0. Uninstall Agenda)
1. Install Agenda (v3.6.3)
2. Click on yellow Agenda v3 button

### Screenshots

![bug](https://github.com/haydenull/logseq-plugin-agenda/assets/9221545/b8b014ba-79ba-4bd8-9f1f-edbbe1cd51b2)

### Environment Information

Debian 12 (GNOME 43.6 Wayland), Desktop version v0.9.20, Agenda v3.6.3

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Thank you for bringing up the issue. I have addressed it in the updated version 3.6.4. However, as I don't have access to a Linux device for testing, I would appreciate it if you could verify the solution for me.

**Comment by imJoshuaRice** [comment]
> Thank you for bringing up the issue. I have addressed it in the updated version 3.6.4. However, as I don't have access to a Linux device for testing, I would appreciate it if you could verify the solution for me.

I will chime in to say that 3.6.3 to 3.6.4 has introduced flickering tabs for Windows, Logseq 0.9.20

![](https://i.imgur.com/0HvxPGt.gif)

**Comment by cbyrohl** [comment]
@haydenull v3.6.4 fixed the issue for me on debian 12

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/9221545/421cd26a-b258-42fb-bcab-d097884ba6c1)

**Comment by haydenull** [comment]
@imJoshuaRice I will release a new version to address this issue tomorrow.

**Comment by haydenull** [comment]
@imJoshuaRice version 3.7.0 has been released, you can give it a try.

**Comment by imJoshuaRice** [comment]
> @imJoshuaRice version 3.7.0 has been released, you can give it a try.
> 
> <img alt="image" width="309" src="https://private-user-images.githubusercontent.com/17695989/285594683-961f04a3-c2f2-4120-a803-839d4b51e05a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjA3MjIsIm5iZiI6MTcwMDkyMDQyMiwicGF0aCI6Ii8xNzY5NTk4OS8yODU1OTQ2ODMtOTYxZjA0YTMtYzJmMi00MTIwLWE4MDMtODM5ZDRiNTFlMDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDEzNTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYWY2ZGJmYTQ2N2EwNWVjODAyZjFlOWNkMDhjMDEwY2YwMjkwZTA2NTExMDcwYzAyMmNmZjg5MmVhN2JhY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mRpinWJTfZuQiUNvq-7KpGrZ0nK5adGeOm1oBjR1Eog">

Hi @haydenull, I can confirm that 3.7.0 has resolved the flickering tabs issue on Windows, 0.9.20.
Thanks.
