### ISSUE TITLE
Legacy Agenda's Calendar shows tasks with deadlines but agenda 3 doesn't

### ISSUE THREAD

**Issue by rolsoft** [haydenull/logseq-plugin-agenda#260]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Tasks with set deadlines don't appear on the calendar of agenda 3, but on the legacy version the tasks appear just fine on the calendar. It seems like on the new calendar only tasks with schedules are shown.

### Reproduce the Bug

Create a task with a deadline, no scheduled date, observe how in the legacy calendar the task appears just fine, but on the new calendar (agenda 3) the task doesn't show up on the calendar.

### Environment Information

Agenda v3.6.4
Latest logseq version

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Thank you for your feedback, 'DEADLINE' represents the deadline of a task, while displaying it in on the calendar requires determining the start date of the task. We are still considering how to design this specific aspect.

**Comment by rolsoft** [comment]
Misclicked*

**Comment by haydenull** [comment]
Is your approach to set a DEADLINE when create a task, and then later setting a specify SCHEDULED based on that DEADLINE?

Would you remove the DEADLINE then setting up a SCHEDULED?

By the way, Agenda3 has a Plan feature that you might want to try out.

**Comment by rolsoft** [comment]
For me a schedule and a deadline are things that coexist together (with different dates). After planning my schedules (by looking at the deadlines), the deadline is left as a point of reference for when a task must be done already. I'm not on my computer right now, but when I get back to it I'll try the plan feature as well.

**Comment by haydenull** [comment]
If a task has both SCHEDULED and DEADLINE, how would you like it to be displayed on the calendar?

**Comment by rolsoft** [comment]
If it has both, I would like the schedule to show up in the calendar, and to be able to see the deadline by clicking it.

**Comment by e-zz** [comment]
> Thank you for your feedback, 'DEADLINE' represents the deadline of a task, while displaying it in on the calendar requires determining the start date of the task. We are still considering how to design this specific aspect.

Tracking the starting date is sometimes extra work for me.  A starting date might be good for some sort of visulization of the entire task, but in general case we tend to focus more on "how much time left". So maybe one idea is to **use today as default value** of starting dates. Another is to **visualize only those with a logbook** record, which means we already have an "actual" starting moment. But for those tasks no time recorded yet, it would be great if we can still find them (as the legacy version does)  in the calendar view.

Or I think it's already useful if there is **a countdown number** along side DEADLINEs. Of course, we could render the time span between some point in the past and the deadline it self. But in the end, a countdown might be more helpful even though much less fancy. It helps DEADLINE tasks stand out and easy to recognize and at the same time, it conveys the most important information of DEADLINEs in an obvious way. 

Anyway, forget what I said if you don't like it. Any form will be perfect as long as DEADLINEs are visible in the calendar : )  

PS: thanks again for the efforts you made so far to develop this plugin.

**Comment by rolsoft** [comment]
I think your ideas are great, thank you for your great work!
The countdown is very important, I already use a small plugin in Logseq that shows a countdown for deadlines/schedules on my queries, but having it on agenda will be great!
And the logbook idea is just perfect. Hopefully these are not too hard to implement.

**Comment by Lesstat** [comment]
Hey,
I just installed the plugin and I like what I see so far. Great job!

Just to put in another perspective. It is also an option to display a task more than once. So the deadline of a task could have a special format (color/design or just a "DEADLINE:" prefix") and appear as well on the calendar view. This way you can have all the info in the calendar and you don't have to decide for a single time to show the task.

**Comment by Kallang22** [comment]
Can we have the same way that Agenda 2 to handle the DEADLINE. This was great and I would love to see DEADLINE as the end of the task instead of the current implementation.

**Comment by haydenull** [comment]
> Can we have the same way that Agenda 2 to handle the DEADLINE. This was great and I would love to see DEADLINE as the end of the task instead of the current implementation.
@Kallang22 I took a look at Agenda2, and noticed that the deadline is not considered as the end time of the task. Its behavior is consistent with scheduled.

**Comment by Kallang22** [comment]
Okay understood.
But can we not make it so that the end date is the deadline. That would
alleviate the need for the xtra data and will use the native SCHEDULED and
DEADLINE references to point respectively to START and END dates?

**Comment by haydenull** [comment]
> Okay understood. But can we not make it so that the end date is the deadline. That would alleviate the need for the xtra data and will use the native SCHEDULED and DEADLINE references to point respectively to START and END dates?

@Kallang22 I understand that there is currently no end date function in logseq, and the deadline represents the task's due date. Agenda3 still hopes to be as consistent as possible with logseq's native syntax. After logseq supports the end date function, Agenda3 can provide the ability to convert with one click.

**Comment by haydenull** [comment]
https://github.com/haydenull/logseq-plugin-agenda/releases/tag/v3.13.0 added support for deadline, welcome to use.
