### ISSUE TITLE
Visulization period (month, week) in Calendar panel is reset by leaving the panel

### ISSUE THREAD

**Issue by e-zz** [haydenull/logseq-plugin-agenda#261]
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/37920155/e42827c1-3212-4f34-98c5-7b14e554d2a5)

Sorry to open an issue with this.
But one problem is that, the selection status of this period is always reset when we switch to `Tasks` panel. 
The option in the top is `Month`, which is a bit slow to open (especially when there are repeated tasks). So I use the `Week` view generally. Unluckily, this selected value, it's always reset to Month view if we click on `Tasks`, making each time switching back to Calendar lag for half a second.

I think this behavior might be possible to change. Maybe use a global variable to store which period we just selected? Or expose the default option in settings so users could select `Week` as the default period? Thanks!

**Comment by haydenull** [comment]
Version 3.7.1 has resolved this issue, you can give it a try.

**Comment by e-zz** [comment]
Bravo!
