### ISSUE TITLE
LogSeq 0.10.0 causes 'task id not found' when trying to move tasks

### ISSUE THREAD

**Issue by imJoshuaRice** [haydenull/logseq-plugin-agenda#265]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

This morning I seemingly can no longer move a task through the Agenda 3 task manager. If I try, I get a 'task id not found' error.

I can still mark tasks as complete and create new ones as normal, just cannot move them.

Agenda v3.7.2
LogSeq 0.10.0

The only change made since it last worked, is a LogSeq update, as I was previously using Agenda v3.7.2 on LogSeq 0.9.20 but am now on 0.10.0 - I have now disabled the auto updater due to this.

### Reproduce the Bug

v0.10.0, try to move task

### Environment Information

Agenda v3.7.2
LogSeq 0.10.0

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
You can refresh the webpage and try again.

**Comment by imJoshuaRice** [comment]
> You can refresh the webpage and try again.

Excellent, that has resolved the problem.
Thank you.
