### ISSUE TITLE
adgeda3 建立中跨多天任务，为什么不能显示在每天日记中直到多天任务的最后一天。

### ISSUE THREAD

**Issue by lzg0419** [haydenull/logseq-plugin-agenda#269]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

adgeda3 建立中跨多天任务，为什么不能显示在每天日记中直到多天任务的最后一天。

### Reproduce the Bug

adgeda3 建立中跨多天任务，为什么不能显示在每天日记中直到多天任务的最后一天。

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
每天日记指的是 logseq 的日记页吗

因为 logseq 自己并没有支持多天任务，所以 logseq 无法识别。Agenda 能够识别是因为加了一些自定义的数据。

**Comment by haydenull** [comment]
加上 deadline 可以显示是因为 logseq 默认有个 query 可以显示大概是 14 天内的 deadline 和 schedule，这个数值可以修改。不过这个并不是多天任务，因为所有任务都是共用的这一个天数设置。

是否有必要出现在日记看你自己的工作流了，我自己是将任务都交给插件管理，每天需要做哪些任务都直接去插件看。我日常用的网页版，所以基本上我是将 Agenda 当作一个独立的任务管理应用，只不过它的数据会存储在 logseq。

如果你希望在 logseq 里完成任务闭环，Agenda 只是辅助任务可视化。建议将多天任务拆分为单天任务，计划的时候可以是多天，但是在任务当天或者任务前几天，可以拆成独立的单天小任务。
