### ISSUE TITLE
Plugin takes too long to load on app startup

### ISSUE THREAD

**Issue by BravishkaSkytano** [haydenull/logseq-plugin-agenda#278]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I open Logseq, I get a notification about the agenda plugin taking too long to load and possibly blocking other plugins from loading.

### Reproduce the Bug

1. Open Logseq

### Environment Information

Linux, NixOS 23.11, Desktop App v0.9.20, Agenda v3.8.0

### Additional Context

I do have a personal opinion that may or may not solve this issue. Perhaps you should split versions 2 and 3 into two different plugins. That way, people can install the version they want, and it may reduce lagging.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
As far as I know, this is an occasional phenomenon, and I'm not sure if it's really a problem with the Agenda plugin, because sometimes another very small plugin of mine can trigger this notification also.

Will there be a problem with your plugin when you encounter this notification?

**Comment by BravishkaSkytano** [comment]
I've only ever encountered this problem with Agenda installed. But I stopped using Logseq recently (too buggy on my main platform) so I can't test this further.
