### ISSUE TITLE
Unable to use Agenda plugin due to retrieve task failure

### ISSUE THREAD

**Issue by GirishPatel** [haydenull/logseq-plugin-agenda#281]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Retreive task failed due to a rogue block reference. I think an old entry existed in my graph and original block go deleted. In previous versions [v3.8.0](https://github.com/haydenull/logseq-plugin-agenda/releases/tag/v3.8.0) issue was non existing.

### Reproduce the Bug

Just create an entry like this: `DONE ((13131212312))`
Inside paranthesis, it can be any random number.

### Screenshots

Sample block:
<img width="251" alt="Screenshot 2024-01-12 at 1 57 06 PM" src="https://github.com/haydenull/logseq-plugin-agenda/assets/6829830/6b3b8b80-3186-4639-bfda-2df93f9cb0f3">

Error screenshot:
<img width="1680" alt="Screenshot 2024-01-12 at 1 57 24 PM" src="https://github.com/haydenull/logseq-plugin-agenda/assets/6829830/ee4c2bfb-dc3c-470b-b6f6-24a10d2dae2a">

### Environment Information

Agenda V3.9.0

### Additional Context

I have debugged and the issue is in error handling.
```typescript
index.tsx:35 retrieve tasks failed TypeError: Cannot read properties of undefined (reading 'split')
    at task.ts:464:41
    at Array.forEach (<anonymous>)
    at replaceBlockReference (task.ts:462:17)
    at async formatTaskTitle (task.ts:478:44)
    at async transformBlockToAgendaEntity (task.ts:165:21)
    at async task.ts:119:18
    at async Promise.all (:5173/index 1231)
    at async getAgendaEntities (task.ts:138:17)
```
For the block `DONE ((64d2a3f7-e8ac-4c62-a76b-42adbb433bc3))`, I am getting the following content:
```json
{
    "id": 643,
    "uuid": "64d2a3f7-e8ac-4c62-a76b-42adbb433bc3",
    "children": []
}
```
We just need to handle undefined content in [task.ts](https://github.com/haydenull/logseq-plugin-agenda/blob/a7ff5cc3eb5d021c39f1edb8a57eee8b31c2a099/src/Agenda3/helpers/task.ts#L464C1-L467C6)
```diff
- if (content) {
+ if (content && content.content) {
```

It is a minor issue and a corner case, so we don't need a separate PR for this. Take it with any existing code changes.
The workaround is to delete all such blocks from Logseq notes.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by e-zz** [comment]
Immediately got this error just now after upgrading to v3.9.0

**Comment by pdarmas** [comment]
Same here. Just updated to v3.9.0 just now and got exactly the same error: 
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/50215689/b31fad08-bb9e-4edd-ad46-5d94ce67058a)

**Comment by daveplummermd1** [comment]
This is Wonderfully useful plugin.
I have the same error since upgrading to 3.9 .0.
Is it possible to re-install 3.8.0 to use until the bug is fixed?

**Comment by GirishPatel** [comment]
One workaround is to delete all invalid block references. You can find them using following query:
```
#+BEGIN_QUERY
{:title "Broken References"
:query [:find (pull ?b [*])
		:where
		[?b :block/refs ?t]
		[(missing? $ ?t :block/name)]
		[(missing? $ ?t :block/content)]]
}
#+END_QUERY
```
Or list all block reference `{{query "(("}} `, those which highlighted are invalid.
