### ISSUE TITLE
【功能请求】“实际用时”记录的起止时间单位不匹配 Actual Time Log Start Time Intervals Don't Match End Time Invervals

### ISSUE THREAD

**Issue by Saltyor** [haydenull/logseq-plugin-agenda#285]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

添加实际用时记录时，起始时间单位是30分钟，希望改为15分钟，与终止时间匹配。
When you add a log of actual time-spending to a task, the start time intervals (30m) and the end time intervals (15m) don't match. Could you please match the intervals so that I can add a log from 10:15 to10:45 directly?

### Reproduce the Bug

1. Agenda 3
2. click on one task
3. add a log
4. click on the start time of the log

### Screenshots

![logseq-agenda3 9 2-bug report](https://github.com/haydenull/logseq-plugin-agenda/assets/157209786/847c923f-008f-42a7-b0a3-68a57529db73)

### Environment Information

Win10
logseq 0.10.3
agenda 3.9.1
(Updated in the logseq plugin market to 3.9.2 but About in the Settings of agenda3 itself shows 3.9.1)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
这里的输入框可以手动输入任意时间，如果将时间间隔改为 15分钟的话，这里的下拉框内容就太多了，不方便选择
