### ISSUE TITLE
How to support calendar synchronization to iPhone's calendar 

### ISSUE THREAD

**Issue by michael88wen** [haydenull/logseq-plugin-agenda#288]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

How to support calendar synchronization to iPhone's calendar so that interaction can take place

Is this included in the follow-up plan?

### Reproduce the Bug

How to support calendar synchronization to iPhone's calendar so that interaction can take place

Is this included in the follow-up plan?

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
‌‌‌‌‌Currently, we can publish our own calendar and then subscribe to it using the iPhone calendar.

**Comment by bootids** [comment]
https://haydenut.notion.site/0de652cd8d5b46518c4522b0e3f6f0e0#a5e85f04dcfa483c89a071ab633d0cec
