### ISSUE TITLE
Supports tasks for journal pages controlled by plugins

### ISSUE THREAD

**Issue by haydenull** [haydenull/logseq-plugin-agenda#29]
是不是还是只能在具体某个页面上用呀，还是想加在日记里

_Originally posted by @SeyeeL in https://github.com/haydenull/logseq-plugin-agenda/issues/5#issuecomment-1075853175_

**Comment by haydenull** [comment]
你好，感谢反馈，可以在这个 issue 里讨论在 journal 页面新建日历事件。

我这边希望了解下：
1. 创建了一个 3 天后的事件，你希望这个 task 文本存在今天的 journal 还是 3 天后的 journal 呢
2. 如果任务是持续多天的，那么会造成只能在一个 journal 页面中存在
3. 在 journal 中保存日历事件是出于什么需求呢，或者说你通常在什么情况下希望 task 被存在 journal 中呢

**Comment by SeyeeL** [comment]
1. 希望出现在三天后
23. 我目前的用法主要是记录一天做了什么，事后回顾，如果是一个长期项目多次做，我应该会把具体做了什么描述一下加上这个项目名的 tag

**Comment by haydenull** [comment]
明白了，会加入开发计划的

**Comment by haydenull** [comment]
1.13.0 版本支持了创建编辑 journal 事件，这里是[文档](https://haydenull.github.io/logseq-plugin-agenda/zh/event/journal.html#创建、编辑、删除-journal-日历事件)。

注意 journal 事件不支持跨天。

**Comment by SeyeeL** [comment]
太好了～～
