### ISSUE TITLE
Export to .ics format 

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#3]
Hi @haydenull 

Let me dream a little. It would be great to be able to export the agenda in .ics format so that it can be integrated in shared professional agendas (for example). Something like that... 

```
BEGIN:VCALENDAR
…
BEGIN:VEVENT
CREATED:20151219T021727Z
DTEND;TZID=America/Toronto:20170515T110000
DTSTAMP:20151219T021727Z
DTSTART;TZID=America/Toronto:20170515T100000
LAST-MODIFIED:20151219T021727Z
RRULE:FREQ=DAILY;UNTIL=20170519T035959Z
SEQUENCE:0
SUMMARY:Meeting
TRANSP:OPAQUE
UID:21B97459-D97B-4B23-AF2A-E2759745C299
END:VEVENT
END:VCALENDAR
```

**Comment by haydenull** [comment]
Thanks for your advice. I will consider this feature after the basic function of plugin is stable.

**Comment by bepolymathe** [comment]
> I will consider this feature after the basic function of plugin is stable.

Great 👍

**Comment by haydenull** [comment]
Agenda3 currently supports the sharing ICS file.
