### ISSUE TITLE
Best way to convert Daily Log?

### ISSUE THREAD

**Issue by TheFaither** [haydenull/logseq-plugin-agenda#305]
Hi,
I have been using Agenda2 for a while, mainly one feature of it, the Daily Log. I see that this is not supported anymore in Agenda3, as all my entries formatted as following do not appear anywhere

```
- [[Daily Log]]
	- Work
		- 09:30-13:00 Project on Vercel and meeting Stefan
		- 13:00-17:30 Project for Annika
```

What should I do with these entries? Is there any plan to support again Daily Log in the future? If not, I am interested in making a plugin that basically is only the Daily Log of Agenda2.

Thanks for your time

**Comment by haydenull** [comment]
Agenda3 is mainly designed to help users manage tasks. Daily Log is for scheduling records, with no specific plans in the short term.

Agneda2 will be maintained normally, and you are very welcome to write a new plugin if you want.
