### ISSUE TITLE
Recurring items

### ISSUE THREAD

**Issue by velardevines** [haydenull/logseq-plugin-agenda#31]
Any plans to add recurrence?

**Comment by haydenull** [comment]
Thank you for your suggestion, this has been put into the development plan, but the main focus is currently on the development of Gantt charts and timelines.

**Comment by joaosimuai** [comment]
@velardevines , how have you been using recurrence alongside the agenda? Thanks.

**Comment by haydenull** [comment]
Agenda3 supports this feature, you can give it a try.
