### ISSUE TITLE
Feature Request: Sort "Task-View" Entries by Time

### ISSUE THREAD

**Issue by TheFogSpirit** [haydenull/logseq-plugin-agenda#310]
Hello, I don't use Github much, so forgive me if I didn't set up this feature request properly. 

I was wondering if it were possible to, once a time is assigned to a task by dragging it into the "Time Box" that the items would be sorted within the "Tasks" view by the assigned time, rather than... some other order (I'm not sure the order that is chosen by default currently). 

Thank you for considering it.

**Comment by haydenull** [comment]
‌‌‌‌Currently, the tasks are sorted by time, but all completed tasks will be placed at the end regardless of their time.

What sorting rule do you want to use?
