### ISSUE TITLE
Todoist sync creating multiple of the same todos with every sync

### ISSUE THREAD

**Issue by gandalf34** [haydenull/logseq-plugin-agenda#312]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I click on the sync button on the logseq ba
![Screenshot 2024-05-08 105533](https://github.com/haydenull/logseq-plugin-agenda/assets/86377241/89608804-e6b8-4585-ac19-b7be76905ad3)
r it brings in the todos taht are already in logseq.

### Reproduce the Bug

1. Go to agenda plugin todoist icon on nav bar
2. Click on it ....doesnt respond after waiting some time 5-10 seconds click again
3. It fetches the tasks for every click but doesnt sync already created or updated tasks

### Environment Information

logseq 0.10.9 Windows 11

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
‌‌Will it be reproduced every time? I guess it might be that the first button was clicked, and the network request had not been successful yet when the second button was clicked, resulting in the same task being requested twice.

**Comment by gandalf34** [comment]
Well probably but a considerable time passes with no notification so as a result its clicked again. So yes it will be reproduced every time

**Comment by haydenull** [comment]
‌‌‌‌‌‌Version 3.10.5 added prompts during synchronization, welcome to test.

**Comment by gandalf34** [comment]
Updated now and will revert with feedback in the coming days. Thanks for  this
