### ISSUE TITLE
Tasks disappear in Tasks view

### ISSUE THREAD

**Issue by turtaf** [haydenull/logseq-plugin-agenda#313]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Since a few weeks, I can't see some tasks in the tasks view, while I keep seeing (correctly) them in the calendar view

Agenda ver 3.10.2, 
Agenda 3 view

### Reproduce the Bug

Open Agenda3, switch between tasks and calendar view

### Screenshots

# Calendar view with all the current activities
![immagine](https://github.com/haydenull/logseq-plugin-agenda/assets/11139231/b0cc9a2b-eedd-48da-8e01-e45bf4b0361e)

# Tasks view with only one task
![immagine](https://github.com/haydenull/logseq-plugin-agenda/assets/11139231/3a077100-ef16-4a58-bd08-ff9dceaff79b)

### Environment Information

Windows 10, Logseq 0.10.9, Agenda 3.10.2

### Additional Context

It seems, maybe, that only the tasks in the journals are presented in tasks, while the ones in the other pages are not shown...but it may be a case...
Tried to reindex the graph,  nothing happened...

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
‌‌‌Can you duplicate a specific task and hide the private information in the task name?

**Comment by turtaf** [comment]
Do you mean like this?

# Calendar view
![immagine](https://github.com/haydenull/logseq-plugin-agenda/assets/11139231/7e7af699-aadd-403e-8e76-80bbf163e9c1)

# Task view
 
![immagine](https://github.com/haydenull/logseq-plugin-agenda/assets/11139231/3feb2a2a-7306-457b-a068-535742807403)

**Comment by haydenull** [comment]
I mean the original text of the task in logseq, such as

```
TODO Dummy item only calendar
SCHEDULED: <2024-05-20 Mon>
```

**Comment by turtaf** [comment]
# Task only on calendar
TODO Only on Calendar.
SCHEDULED: <2024-04-17 Wed>
:AGENDA:
end: 2024-05-31
:END:

# Task on both
TODO On Both
SCHEDULED: <2024-05-13 Mon>
:AGENDA:
end: 2024-05-31
:END:

**Comment by haydenull** [comment]
![CleanShot 2024-05-22 at 10 00 36@2x](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/28da9c0e-11f5-46f8-bea9-f7a5444e7142)

I tested and confirmed that this task can be displayed correctly. Is this task not displaying properly on your computer?

**Comment by turtaf** [comment]
This is the one that was displaying correctly on both tasks and calendar.The other one showed only on calendar

**Comment by haydenull** [comment]
‌‌‌‌‌This issue should have been fixed in 3.10.4, you can try again

**Comment by turtaf** [comment]
Confirmed to be working, now on 3.10.4.

All my tasks are back!

Thanks a lot for the good work.
Cheers,
e.
