### ISSUE TITLE
Current week tasks not showing in calendar view

### ISSUE THREAD

**Issue by turtaf** [haydenull/logseq-plugin-agenda#316]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Since last update 3.10.4, and possibly connected to my previous request #313, in calendar view I don't see the tasks that take more than one day in the current week (bit I see them in the adjacent ones), while I see the daily tasks set on journal pages.

### Reproduce the Bug

open agenda3, calendar view, with tasks taking more than one week

### Screenshots

![immagine](https://github.com/haydenull/logseq-plugin-agenda/assets/11139231/c4c8328b-88d5-40d1-8270-7433318d7b3f)

### Environment Information

Windows 10, Logseq 0.10.9, Agenda 3.10.2

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
Could you provide the original text of the task in logseq?

**Comment by turtaf** [comment]
Here it is,

```
TODO Analisi
SCHEDULED: <2024-04-17 Wed>
:AGENDA:
end: 2024-05-31
:END:
```
If I may make a guess, could it be more of an aestetic matter? I did some tests and if I reduce the number of tasks, they do appear again. They disappear in bulk when they are enough to saturate the vertical space of the calendar cell. 
To replicate it, you could try adding more todos untill you fill all the available space.

I hope it helps.
Thanks

**Comment by haydenull** [comment]
Can the task displayed after click "+1 more" button?

**Comment by haydenull** [comment]
‌Can you send me the original text of all tasks that need to be displayed this week? I still haven't reproduced this issue on my end.

![CleanShot 2024-05-24 at 17 51 24@2x](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/eb34ee83-52f1-4eb0-a5cd-02b791092aa2)
