### ISSUE TITLE
Unscheduled recurring tasks shouldn't be shown on the calendar.

### ISSUE THREAD

**Issue by rolsoft** [haydenull/logseq-plugin-agenda#318]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

# What works well:
Usually in logseq, if you create a task that is **scheduled** (with a time set) and also has a **repeater set**, for example every _two days_, it makes sense that it appears on the calendar like this:

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/127045317/500e0b9c-0f36-46bf-8783-9a2286368ab6)
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/127045317/0a42c467-6a8a-4e4a-a63c-55ca9d5c9cc5)

# What doesn't work so well

The issue is that, usually if you create a task that is **not scheduled** (scheduled but no time set) that has a **repeater set**, for example _everyday_, it is probably sort of like a checklist (something you have to remember to do at a not specific timeframe), like in the example:
![image](https://github.com/haydenull/logseq-plugin-agenda/assets/127045317/9e7beecc-e5bb-4987-aac5-5949677ca536)

But you really do not need to have your calendar cluttered with daily tasks to water your plants obviously:

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/127045317/cd848be4-9bbb-4ca9-a20d-f8aecc6c5eec)

# Proposed solution
Make it so that the tasks that have a **schedule** and **repeater** set, show up on the calendar as they have always been. (stay as they are)
And make the **not scheduled** (scheduled without the time set) tasks that have a **repeater** set _only appear on the calendar on today's day_. Like this:

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/127045317/fc0e67b4-237a-4706-b064-a9f1563dde67)

Hopefully this is not difficult to do in the code and I explained myself correctly. This plugin is truly amazing and has a lot of hard work put into it.

### Reproduce the Bug

Create tasks that have repeaters, and one that has a schedule (with time) and the other that has a schedule timed.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
‌‌‌‌‌Whether the recurring task is assigned a specific time only affects whether the task is an all-day task.

If there are too many recurring tasks that affect reading, you can try opening this option.

![CleanShot 2024-05-28 at 10 36 52@2x](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/5ad80229-8bca-4ab0-b5c3-eae942fc6189)

**Comment by rolsoft** [comment]
That works, thank you, would love a tooltip next to the option that explains it in more detail, as it is I wouldn't have found that was what I wanted

**Comment by haydenull** [comment]
> That works, thank you, would love a tooltip next to the option that explains it in more detail, as it is I wouldn't have found that was what I wanted

Very good suggestion, I think it will be added in the next version.
