### ISSUE TITLE
Sync todolist failure in upload side

### ISSUE THREAD

**Issue by jackyliu16** [haydenull/logseq-plugin-agenda#320]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

useing agenda2.0, settings API, Successfully synchronize data from TodoList to LogSeq

### Reproduce the Bug

1. click plugins-agenda-todolist
2. automatic sync the todolist item to logseq
3. but the schedule in logseq(format with agenda 2.0) will not automatically upload to todolist, which should be possible to do with api 

### Screenshots

![image](https://github.com/haydenull/logseq-plugin-agenda/assets/50787361/39ba6ac4-a145-4ed2-9e08-0c71e742a48a)

### Environment Information

os: win11 latest, 0.10.9-alpha+nightly.20240528, agenda 2.0

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
The role of the "plugins-agenda-todolist" button is to synchronize the tasks of Todoist to Logseq, and it does not have the function of uploading tasks to Todoist.

If a task is associated with todoist, after editing in logseq, it will be automatically synchronized to totoist.

**Comment by jackyliu16** [comment]
Can you definitude what's the means of task associated with todoist ?
It is like some tags or others defined elsewhere ? Sorry but I don't seems to see any descriptions about it.

**Comment by haydenull** [comment]
![CleanShot 2024-06-13 at 14 11 36@2x](https://github.com/haydenull/logseq-plugin-agenda/assets/17695989/12da7c0e-699c-4e00-9fa9-944062703259)

When a task has the property of todoist-id, it means that modifying this task will be synchronized to Todoist.

https://x.com/haydenull/status/1545987056593096704

**Comment by jackyliu16** [comment]
Thanks for the video, 
I found that there is an upload option in the context menu that solves my current problem

**Comment by jackyliu16** [comment]
Thanks for the video, 
I found that there is an upload option in the context menu that solves my current problem
