### ISSUE TITLE
web端同步失败，api设置成功，但是网页还是显示连接失败让刷新

### ISSUE THREAD

**Issue by rchqi** [haydenull/logseq-plugin-agenda#322]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

web打开agenda失败

### Reproduce the Bug

打开web端
添加token: 名称agenda 值123  显示成功
点击web提示的refresh，失败，继续提示这个弹窗

### Screenshots

![Snipaste_2024-07-13_16-50-32](https://github.com/user-attachments/assets/b89d7898-4d6d-4e47-bb67-9dde056ba8c2)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
![CleanShot 2024-07-17 at 11 01 15@2x](https://github.com/user-attachments/assets/b8aa3288-18b7-4d54-81c4-0abc10fc99c7)

可以看下网页端的配置

**Comment by rchqi** [comment]
![image](https://github.com/user-attachments/assets/47ed147c-92c7-4f8e-94c1-e7928a670b8e)
这样的

**Comment by haydenull** [comment]
![CleanShot 2024-07-17 at 17 13 43@2x](https://github.com/user-attachments/assets/c213460f-ccc9-4307-80c5-e6f5386b5292)

token 设置呢

**Comment by rchqi** [comment]
好了，就是logseq里面的token没设置成功，应该是当时设置这一步的时候哪里点错了，谢谢！
