### ISSUE TITLE
问题：如何在其他日历软件或者手机日历上使用上传到github的ics文件

### ISSUE THREAD

**Issue by ChasingZenith** [haydenull/logseq-plugin-agenda#324]
现在我希望能够在agenda上面规划了日程之后，手机日历上同步出现，以完成提醒功能。但是不是很清楚怎么利用推荐的上传到github私有仓库的方式完成。

**Comment by haydenull** [comment]
可以参考这个文档

https://www.notion.so/haydenut/0de652cd8d5b46518c4522b0e3f6f0e0#a5e85f04dcfa483c89a071ab633d0cec

**Comment by ChasingZenith** [comment]
感谢，现在使用滴答清单能够同步到手机上了。
非常感谢你的插件，几乎就是因为这个插件，所以才用的logseq。
