### ISSUE TITLE
Feature to use agenda with logseq web 

### ISSUE THREAD

**Issue by shakeabi** [haydenull/logseq-plugin-agenda#325]
Hey, huge fan of the plugin here.
I was wondering if there's any way to use this with the web version. I'm down for doing any kinda hackery.
Issue is, my company doesn't allow installing any software and hence I'm using the web version to manage my notes. I would love to use this plugin along with it.
Thanks!

**Comment by haydenull** [comment]
The plugin requires services provided by the Logseq desktop to access data, so it cannot be used in Logseq web.
