### ISSUE TITLE
请教如何离线安装agenda3插件 how to install plugin offline

### ISSUE THREAD

**Issue by raymondelf** [haydenull/logseq-plugin-agenda#329]
我在单位内网上无法通过插件市场安装agenda3。
我按照以下步骤离线加载了插件包，但无法正常启动该插件，请问我需要如何完成配置呢？

我的步骤：
1. 从release中下载了压缩包
2. 将压缩包解压到用户.logseq/plugins文件夹
3. 在logseq中打开开发者模式后，在plugins中装载该插件
4. 从插件菜单中，确认插件已加载。

我仿照B站的指导视频，尝试在设置中打开了api功能，并设置了agenda的123……因为我缺乏相关知识，不清楚这些操作的含义，所以最终我失败了，无法通过网页访问该插件。

请问，我需要通过哪些设置，能够让我在离线环境下安装运行这个插件。

**Comment by haydenull** [comment]
自己手动安装的插件不建议放在 .logseq/plugins 文件夹中，之前有遇到一些莫名其妙的 bug 是因为安装位置引起的，随便在电脑上找个位置就行。然后装载插件的时候找到文件夹即可。

建议你先卸载当前的插件，删掉 .logseq/plugins 内的 agenda。然后找一个普通的地方重新装载再试试。

**Comment by raymondelf** [comment]
> 自己手动安装的插件不建议放在 .logseq/plugins 文件夹中，之前有遇到一些莫名其妙的 bug 是因为安装位置引起的，随便在电脑上找个位置就行。然后装载插件的时候找到文件夹即可。
> 
> 建议你先卸载当前的插件，删掉 .logseq/plugins 内的 agenda。然后找一个普通的地方重新装载再试试。

感谢答复。
上班后尝试一下，看看是否能够解决问题。

**Comment by raymondelf** [comment]
卸载后，在其他目录加载，插件正常工作，问题解决，感谢。
