### ISSUE TITLE
在时间轴上新建事件时日历值有个默认值或者默认第一个

### ISSUE THREAD

**Issue by seyeeL** [haydenull/logseq-plugin-agenda#33]
rt

**Comment by haydenull** [comment]
是指默认选一个日历？

**Comment by SeyeeL** [comment]
是的





------------------ 原始邮件 ------------------
From: Hayden Chen ***@***.***&gt;
发送时间: 03/26/2022, 20:59
To: haydenull/logseq-plugin-agenda ***@***.***&gt;
抄送: SeyeeL ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [haydenull/logseq-plugin-agenda] 在时间轴上新建事件时日历值有个默认值或者默认第一个 (Issue #33)

**Comment by haydenull** [comment]
Agenda3 has a brand new calendar, you can give it a try.
