### ISSUE TITLE
时间轴上建事件可以选择默认任务还是普通时段事件

### ISSUE THREAD

**Issue by seyeeL** [haydenull/logseq-plugin-agenda#34]
rt

**Comment by haydenull** [comment]
默认任务指的是什么

**Comment by SeyeeL** [comment]
就是非TODO，就是普通的11:00-12:00





------------------ 原始邮件 ------------------
From: Hayden Chen ***@***.***&gt;
发送时间: 03/26/2022, 21:01
To: haydenull/logseq-plugin-agenda ***@***.***&gt;
抄送: SeyeeL ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [haydenull/logseq-plugin-agenda] 时间轴上建事件可以选择默认任务还是普通时段事件 (Issue #34)

**Comment by haydenull** [comment]
这个目前可能不会做，因为不是todo任务，默认日历就不会收集。

等几个大功能完成了，再加吧。

**Comment by SeyeeL** [comment]
坐等大功能~



------------------ 原始邮件 ------------------
From: Hayden Chen ***@***.***&gt;
发送时间: 03/26/2022, 21:10
To: haydenull/logseq-plugin-agenda ***@***.***&gt;
抄送: SeyeeL ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [haydenull/logseq-plugin-agenda] 时间轴上建事件可以选择默认任务还是普通时段事件 (Issue #34)
