### ISSUE TITLE
全屏时宽度全屏了，高度没有占满全屏（logseq是全屏的前提）

### ISSUE THREAD

**Issue by SeyeeL** [haydenull/logseq-plugin-agenda#36]
rt

**Comment by haydenull** [comment]
1.13.1 版本修复了这个问题

**Comment by SeyeeL** [comment]
![image](https://user-images.githubusercontent.com/71479570/160263343-91042dec-9476-4c4c-ac73-35c9a4c19291.png)
外框全屏啦，日历内容没有

**Comment by haydenull** [comment]
请问下如何复现的，logseq 版本以及电脑操作系统是什么版本呢？我这没复现出来

**Comment by SeyeeL** [comment]
logseq 0.6.4
电脑 mac M1 最新版
我设置了时段不展示0-8不知道有没有这个原因

**Comment by haydenull** [comment]
默认周视图。然后进入插件，点击全屏就出现了吗，logseq 是什么版本

**Comment by haydenull** [comment]
可以打开控制台看下 id为 calendar 的div，style 100% 有没有设置上，以及它的父元素高度是全屏的吗
![image](https://user-images.githubusercontent.com/17695989/160263868-747e4b67-d699-4f39-90ad-6c9c34648714.png)

**Comment by haydenull** [comment]
1.13.2 已发布，可以再试试
