### ISSUE TITLE
Getting timeouts since about a week

### ISSUE THREAD

**Issue by ajk68** [haydenull/logseq-plugin-agenda#39]
Your amazing plugin worked like a charm for one or two weeks. Also, very fast. But since about a week my logseq freezes and after about 10 seconds it looks like i'm getting a timeout error. My graph is fairly large with almost 40,000 blocks and 600 Todo's. But didn't grow significantly in the past weeks. So could be either update of logseq or update of this plugin.

Hope this helps you figure out the problem. Would be awesome to start using it again!

Query Exec Error:
calendar: journal
query:
[:find (pull
?block
[:block/uuid
:block/parent
:block/left
:block/collapsed?
:block/format
:block/_refs
:block/path-refs
:block/tags
:block/content
:block/marker
:block/priority
:block/properties
:block/pre-block?
:block/scheduled
:block/deadline
:block/repeated?
:block/created-at
:block/updated-at
:block/file
:block/heading-level
{:block/page
[:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])
:where
[?block :block/page ?page]
[?page :block/journal? true]
[?block :block/marker ?marker]
[(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]
[(missing? $ ?block :block/scheduled)]
[(missing? $ ?block :block/deadline)]]

message: [deferred timeout] async call #905

**Comment by haydenull** [comment]
Can it be executed normally in the DevTools？

https://haydenull.github.io/logseq-plugin-agenda/other/testQuery.html

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/17695989/161380893-339fab53-7e28-410a-83f0-c849cec98e75.png">

**Comment by ajk68** [comment]
Hey Hayden, 

I'm using plugin v 1.14.0 and logseq 0.65. Each of the 4 calendar queries runs quick (under 1 second) in devtools. 

Below is the full log from the regular query timeout from the devtools.

index.832eb22b.js:96 [faiz:] === search blocks by query:  
[:find (pull ?block [*])
  :where
  [?block :block/marker ?marker]
  [(missing? $ ?block :block/deadline)]
  (not [(missing? $ ?block :block/scheduled)])
  [(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]]
           (11) [Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1)]
index.832eb22b.js:96 [faiz:] === search blocks by query:  
[:find (pull ?block [*])
  :where
  [?block :block/marker ?marker]
  [(missing? $ ?block :block/scheduled)]
  (not [(missing? $ ?block :block/deadline)])
  [(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]]
           (2) [Array(1), Array(1)]
index.832eb22b.js:96 [faiz:] === search blocks by query:  
[:find (pull
  ?block
  [:block/uuid
    :block/parent
    :block/left
    :block/collapsed?
    :block/format
    :block/_refs
    :block/path-refs
    :block/tags
    :block/content
    :block/marker
    :block/priority
    :block/properties
    :block/pre-block?
    :block/scheduled
    :block/deadline
    :block/repeated?
    :block/created-at
    :block/updated-at
    :block/file
    :block/heading-level
    {:block/page
    [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])
  :where
  [?block :block/page ?page]
  [?page :block/journal? true]
  [?block :block/marker ?marker]
  [(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]
  [(missing? $ ?block :block/scheduled)]
  [(missing? $ ?block :block/deadline)]]
           (1932) [Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), …]
index.832eb22b.js:96 [faiz:] === search blocks by query:  
[:find (pull ?block [*])
  :where
  [?rp :block/name "milestone"]
  [?block :block/refs ?rp]]
           []
index.832eb22b.js:98 [faiz:] === scheduleRes error:  {calendarConfig: {…}, query: {…}} {status: 'rejected', reason: Error: [deferred timeout] async call #9958
    at file:///Users/arthur/.logseq/plugins/logseq-agend…}reason: Error: [deferred timeout] async call #9958
    at file:///Users/arthur/.logseq/plugins/logseq-agenda/dist/assets/vendor.fc5aacf1.js:10:14148status: "rejected"[[Prototype]]: Object
(anonymous) @ index.832eb22b.js:98
Zt @ index.832eb22b.js:98
async function (async)
Zt @ index.832eb22b.js:98
Ie @ index.832eb22b.js:106
(anonymous) @ index.832eb22b.js:106
setTimeout (async)
(anonymous) @ index.832eb22b.js:106
jB @ vendor.fc5aacf1.js:43
e.unstable_runWithPriority @ vendor.fc5aacf1.js:28
Zl @ vendor.fc5aacf1.js:39
dl @ vendor.fc5aacf1.js:43
yC @ vendor.fc5aacf1.js:41
(anonymous) @ vendor.fc5aacf1.js:39
e.unstable_runWithPriority @ vendor.fc5aacf1.js:28
Zl @ vendor.fc5aacf1.js:39
tO @ vendor.fc5aacf1.js:39
ko @ vendor.fc5aacf1.js:39
JO @ vendor.fc5aacf1.js:41
iv @ vendor.fc5aacf1.js:43
ja.render @ vendor.fc5aacf1.js:43
Qe @ index.832eb22b.js:107
show @ index.832eb22b.js:107
(anonymous) @ vendor.fc5aacf1.js:10
postMessage (async)
call @ lsplugin.core.js:2
_callUserModel @ lsplugin.core.js:2
callUserModel @ lsplugin.core.js:2
(anonymous) @ lsplugin.core.js:2
u @ helpers.js:156
instrument.js:190 "Datascript query: " [:find (pull ?b [:db/id :block/uuid :block/parent :block/left :block/collapsed? :block/format :block/refs :block/_refs :block/path-refs :block/tags :block/content :block/marker :block/priority :block/properties :block/pre-block? :block/scheduled :block/deadline :block/repeated? :block/created-at :block/updated-at :block/file :block/heading-level {:block/page [:db/id :block/name :block/original-name :block/journal-day]} {:block/_parent ...}]) :in $ % :where (page-ref ?b "daily log")]
index.832eb22b.js:53 
index.832eb22b.js:53 [faiz:] === start exec your query:
index.832eb22b.js:54 
[:find (pull ?block [*])
  :where
  [?block :block/marker ?marker]
  [(missing? $ ?block :block/deadline)]
  (not [(missing? $ ?block :block/scheduled)])
  [(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]]
          
index.832eb22b.js:53 [faiz:] === exec your query success:
index.832eb22b.js:55 (11) [Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1)]
index.832eb22b.js:56 
index.832eb22b.js:53 
index.832eb22b.js:53 [faiz:] === start exec your query:
index.832eb22b.js:54 
[:find (pull ?block [*])
  :where
  [?block :block/marker ?marker]
  [(missing? $ ?block :block/scheduled)]
  (not [(missing? $ ?block :block/deadline)])
  [(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]]
          
index.832eb22b.js:53 [faiz:] === exec your query success:
index.832eb22b.js:55 (2) [Array(1), Array(1)]
index.832eb22b.js:56 
index.832eb22b.js:53 
index.832eb22b.js:53 [faiz:] === start exec your query:
index.832eb22b.js:54 
[:find (pull
  ?block
  [:block/uuid
    :block/parent
    :block/left
    :block/collapsed?
    :block/format
    :block/_refs
    :block/path-refs
    :block/tags
    :block/content
    :block/marker
    :block/priority
    :block/properties
    :block/pre-block?
    :block/scheduled
    :block/deadline
    :block/repeated?
    :block/created-at
    :block/updated-at
    :block/file
    :block/heading-level
    {:block/page
    [:db/id :block/name :block/original-name :block/journal-day :block/journal?]}])
  :where
  [?block :block/page ?page]
  [?page :block/journal? true]
  [?block :block/marker ?marker]
  [(contains? #{"TODO" "DOING" "NOW" "LATER" "WAITING" "DONE"} ?marker)]
  [(missing? $ ?block :block/scheduled)]
  [(missing? $ ?block :block/deadline)]]
          
index.832eb22b.js:53 [faiz:] === exec your query success:
index.832eb22b.js:55 (1932) [Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), Array(1), …][0 … 99][100 … 199][200 … 299][300 … 399][400 … 499][500 … 599][600 … 699][700 … 799][800 … 899][900 … 999][1000 … 1099][1100 … 1199][1200 … 1299][1300 … 1399][1400 … 1499][1500 … 1599][1600 … 1699][1700 … 1799][1800 … 1899][1900 … 1931]length: 1932
index.832eb22b.js:56 
index.832eb22b.js:53 
index.832eb22b.js:53 [faiz:] === start exec your query:
index.832eb22b.js:54 
[:find (pull ?block [*])
  :where
  [?rp :block/name "milestone"]
  [?block :block/refs ?rp]]
          
index.832eb22b.js:53 [faiz:] === exec your query success:
index.832eb22b.js:55 []
index.832eb22b.js:56

**Comment by haydenull** [comment]
If you don't have important Settings, you can reset them.
![image](https://user-images.githubusercontent.com/17695989/161422293-cf400eaf-57a7-446d-9f6c-1e2d1455d5d1.png)

Or manually add a line of code under this query script: `:db/id`.
![image](https://user-images.githubusercontent.com/17695989/161422344-a482fd7e-251b-48a3-a83d-bd0353938045.png)

Can you test the effect after you have changed it? Also, do you have a lot of block references in your task?

**Comment by ajk68** [comment]
Wow Hayden, that worked. Wasn't aware that  i made any setting changes.
Very happy to be able to use it again! Thanks for your help! Arthur

**Comment by haydenull** [comment]
Version 1.15.0 optimizes loading speed
