### ISSUE TITLE
Logseq Marketplace

### ISSUE THREAD

**Issue by hdansou** [haydenull/logseq-plugin-agenda#4]
Is there a plan to publish this plugin in Logseq marketplace?

**Comment by benjaffe** [comment]
https://github.com/logseq/marketplace

**Comment by haydenull** [comment]
This plugin has been published to the marketplace. You can try refreshing the list of plugins in logseq.

**Comment by benjaffe** [comment]
Ah yes, caches strike again. Thanks, and great work on the plugin!

**Comment by hdansou** [comment]
Thank you
