### ISSUE TITLE
Moving block to another day loses intended blocks

### ISSUE THREAD

**Issue by gkwiatk** [haydenull/logseq-plugin-agenda#42]
If I move an event block to another day through Agenda interface, it loses children blocks. Moving to another hour in the same day works fine.

Example:
Apr 22nd, 2022
- TODO 09:00-10:00 An event
   - Some important notes about event
   
Then I open the Agenda plugin. Move it to Apr 23rd, 2022. The result is:
- TODO 09:00-10:00 An event

Notes are missing.

**Comment by haydenull** [comment]
This problem is fixed in version 1.15.2. You can try again.

**Comment by gkwiatk** [comment]
Now moving between days is not working at all. It doesn't save changes.

**Comment by haydenull** [comment]
What version of your logseq?

**Comment by gkwiatk** [comment]
I use 0.6.6. I'll downgrade the plugin in the next days or patiently wait for the next beta of Logseq. Thanks for the advice and for a great plugin!

**Comment by gkwiatk** [comment]
It works with Logseq 0.6.7. Thanks a lot!
