### ISSUE TITLE
暗色主题可否再升级一下？

### ISSUE THREAD

**Issue by hdg8087** [haydenull/logseq-plugin-agenda#43]
【1】字体不是很清楚，看起来有点点累。
【2】暗色背景、文字之类的配色，能否与Logseq的墨绿主题保持一致？
【3】假如event3是一个 [[ ]] 页面双链，agenda上就不能识别了。
感谢！

**Comment by haydenull** [comment]
感谢返回，暗色模式优化在计划中了

**Comment by haydenull** [comment]
2.0 版本重新适配了暗色模式

> 【3】假如event3是一个 [[ ]] 页面双链，agenda上就不能识别了。

这个可以举个例子吗。

**Comment by hdg8087** [comment]
意思是，表格里面只能是纯文字，不能是双链页面。

**Comment by haydenull** [comment]
这个表格指的是？
