### ISSUE TITLE
Emoji in Log Key is not supported

### ISSUE THREAD

**Issue by danieltomasz** [haydenull/logseq-plugin-agenda#44]
I could use logkey [[Planner]] but not [[✎Planner]] or [[✎ Planner]] (the second is with space).

**Comment by haydenull** [comment]
I tested [[✎ Planner]] works. You can confirm that there are no more spaces before and after the input box.
![image](https://user-images.githubusercontent.com/17695989/164889743-f30ff42b-bf3f-4068-85b3-9f73a67c3e7e.png)

**Comment by danieltomasz** [comment]
Yes it was my fault ( I wasnt always saving the setting, because the setting button was invisible when logseq window was smaller :P )
