### ISSUE TITLE
Render tasks on a page

### ISSUE THREAD

**Issue by prashantsengar** [haydenull/logseq-plugin-agenda#47]
Hi, I love using the agenda plugin! Thanks a lot for building it.

Is it possible to add a feature to render the tasks for today? Something like this:
- have a command `/today's agenda`
- it shows the tasks (as block references) for today (same as shown in calendar).

I can essentially achieve the same functionality by running the queries used by the plugin on the journal, but I believe the plugin is using the dates and filtering out based on that as well.
For example, if I schedule a TODO for May 6 on the journal page of May 5, agenda plugin will show it only on May 6. However, the query will show it on May 5 as well.

**Comment by haydenull** [comment]
The area on the right side of the dashboard now shows today's and overdue tasks.
Do you want to embed today's tasks in the specified notes?

**Comment by prashantsengar** [comment]
Correct yes, embedding them in a note would be perfect

**Comment by haydenull** [comment]
Version 2.2.0 added slash command: insert today's task.
It will insert new block(today's task block reference).
