### ISSUE TITLE
请问可以直接在试图里面操作吗

### ISSUE THREAD

**Issue by bemofan** [haydenull/logseq-plugin-agenda#5]
如题

**Comment by haydenull** [comment]
因为现在的日历事件是根据query查出来的，用户的block内容无法预知，所以暂时没办法做到在视图里编辑。
可以先使用 navigate to block跳转去编辑。
暂时还没想好怎么规划这一块。

**Comment by SeyeeL** [comment]
同希望可以直接在视图编辑，放在journal文件里就好了。

**Comment by haydenull** [comment]
刚刚发布的1.10.2支持了在日历视图中创建编辑。但是只局限于由插件创建的事件。

文档明天会补上。

![image](https://user-images.githubusercontent.com/17695989/159126076-a40672e2-fe10-4768-81f6-664cc21f0bbf.gif)

**Comment by SeyeeL** [comment]
只局限于由插件创建的事件。是什么意思呀，这个是必须指定一条笔记吗

**Comment by SeyeeL** [comment]
好像没找到有 GitHub 的response 或者 buymeacoffee？求贴个链接啥的插件很好用，谢谢

**Comment by haydenull** [comment]
> 只局限于由插件创建的事件。是什么意思呀，这个是必须指定一条笔记吗

是这样的，需要先创建自定义日历，并且在创建时选中 control by agenda，这样创建日历的同时插件会新建一个页面。￼

之后在日历视图中新建的事件会写入到这个页面中。

这种事件可以支持编辑删除等操作。

**Comment by SeyeeL** [comment]
@haydenull 是由于软件限制么，好想直接建到日历页面里啊😭

**Comment by haydenull** [comment]
> 好像没找到有 GitHub 的response 或者 buymeacoffee？求贴个链接啥的插件很好用，谢谢

感谢你的肯定，一个原因是之前没申请这些，一个原因是插件功能还不稳定。未来可能会放。

**Comment by haydenull** [comment]
> @haydenull 是由于软件限制么，好想直接建到日历页面里啊😭

这么设计的原因是有的用户不使用日记功能，还有这个事件是用 start end 自定义属性记录时间，在笔记里不太好看。

你可以创建两个事件跳到对应page看看样式。

**Comment by SeyeeL** [comment]
噢噢我在日历里用了那种样式的可以接受，要不然弄个选项哈哈哈，用户选择在日记或者新建一条笔记

**Comment by haydenull** [comment]
最新版已支持在视图中操作，如果有问题欢迎沟通

**Comment by SeyeeL** [comment]
是不是还是只能在具体某个页面上用呀，还是想加在日记里

**Comment by haydenull** [comment]
> 是不是还是只能在具体某个页面上用呀，还是想加在日记里

新开了 issue 来讨论这个哈。https://github.com/haydenull/logseq-plugin-agenda/issues/29
