### ISSUE TITLE
I can't find dashboard

### ISSUE THREAD

**Issue by Ben9706** [haydenull/logseq-plugin-agenda#50]
This plugin works well and has a very close experience with NotePlan, but I'm sorry I didn't find how to turn on the Dashboard, can someone remind me about it🙏.

**Comment by haydenull** [comment]
The dashboard is a new function in version 2.x, what version of your plugin?

**Comment by Ben9706** [comment]
You are right, my version is v1.15.0.Now it works,Thanks!
