### ISSUE TITLE
org-mode time spans should be handled correctly

### ISSUE THREAD

**Issue by wuqui** [haydenull/logseq-plugin-agenda#51]
It would be great it this plugin could correctly handle org-mode time spans.

These are conventionally specified in this format:

```
* TODO heading
SCHEDULED: <2022-05-18 Wed 15:30-21:30>
```

Unfortunately, this plugin currently doesn't recognize this. What is worse, it even fails to recognize the start time as soon as one specifies an end time by adding something like `-21:00`.

This plugin is great by the way, thanks a lot for your work!

**Comment by CavalloneChen** [comment]
Much needed!

**Comment by haydenull** [comment]
Logseq can not display `SCHEDULED: <2022-05-18 Wed 15:30-21:30>` correctly. The existing design of the plugin is to split the start and end into two fields.

In addition, the plugin is coming soon with a new calendar type that doesn't require scheduled or block properties.
