### ISSUE TITLE
[FR] New metadata associated with each event : dur (duration)

### ISSUE THREAD

**Issue by icytree** [haydenull/logseq-plugin-agenda#52]
Would it be possible to add a new metadata to indicate the duration of each event (end - start). I am having quite some difficulty to build queries to achieve this and I thought it could be a simpler solution. By the way, thank you for the plugin it is very nice !

**Comment by haydenull** [comment]
Sorry, we have ultimately decided not to implement this feature. In Agenda3, our goal is to minimize custom syntax as much as possible.
