### ISSUE TITLE
Calendar event creation does not work when logseq use org-mode

### ISSUE THREAD

**Issue by sleepyeye** [haydenull/logseq-plugin-agenda#53]
Hi!
I found that the custom calendar would not work with the default settings of **logseq-plugin-agenda**.
Precisely, I can make a custom calendar and assign events. 
However,  **logseq-plugin-agenda** does not display the event in both of calendar and dashboard.

For instance, I have following org mode page in `dev.org`.
Here I added two events under agenda block.
The event **Event with start_time and end_time** has properties `start_time`, `end_time`  where default properties that I made to demonstrate the example.
The other 
event has properties `start` and `end` where default properties which are inserted by  **logseq-plugin-agenda**.
```org
:PROPERTIES:
:agenda: true
:END:

* Agenda
** TODO Event with start_time and end_time
:PROPERTIES:
:start_time: 2022-05-27 23:59
:end_time: 2022-05-30 23:59
:END:
** TODO Event with start and end
:PROPERTIES:
:start: 2022-05-27 23:59
:end: 2022-06-02 23:59
:END:
```
The calendar and dashboard looks as follows 
![image](https://user-images.githubusercontent.com/37354487/170812387-4d621f4f-aa62-4d10-93d6-ae95ba6d04af.png)

![image](https://user-images.githubusercontent.com/37354487/170812416-c57caecf-84f2-4a47-aef6-53953e6b056f.png)

If I change the custom calendar query 
from
`(and (page "dev") (property end) (property start))`
to 
`(and (page "dev") (property end_time) (property start_time))`
![image](https://user-images.githubusercontent.com/37354487/170812497-52b6d58b-2513-4532-9e35-a50c7c5021a6.png)

![image](https://user-images.githubusercontent.com/37354487/170812491-18f3431e-a1d8-47cb-afca-8330aecbc8f3.png)

I guess it is because `end` keyword is reserved by **org-mode** so the logseq query would be failed. 
It shows that to properly use **logseq-plugin-agenda** with org-mode documents, I need to change the default time property names from `start`,`end` to something else. 
Currently, I can freely adjust queries but I cannot adjust the `start`,`end` keyword which is inserted by  **logseq-plugin-agenda** using calendar view.
Is there any way so that I can change the property block name?

**Comment by haydenull** [comment]
Custom calendars are no longer needed in version 2.3.0. 

The plugin collects todos from all pages and supports multiple ways to set dates.

[https://haydenull.github.io/logseq-plugin-agenda/introduction/events.html#journal](https://haydenull.github.io/logseq-plugin-agenda/introduction/events.html#journal)

**Comment by sleepyeye** [comment]
@haydenull 

Thanks! I have tested with version 2.3.2 and it works without any problem.
