### ISSUE TITLE
Time is ignored when priority is assigned to task

### ISSUE THREAD

**Issue by Xemnas0** [haydenull/logseq-plugin-agenda#56]
If a priority is assigned to a task, then the time specified is not taken into account and the task is displayed as "All day"

![image](https://user-images.githubusercontent.com/26822543/170863364-f8db4d53-c9da-4d62-9b5b-06a10a7d8fe0.png)

**Comment by haydenull** [comment]
Version 2.3.0 should fix this, so you can try it again.
