### ISSUE TITLE
Feature - Allow for Calendars to be Joint

### ISSUE THREAD

**Issue by koconder** [haydenull/logseq-plugin-agenda#57]
Feature to mix all the calendars on output into one node rather then separated as a feature.

**Comment by haydenull** [comment]
I'm sorry, I don't understand. Could you elaborate?

**Comment by koconder** [comment]
So say the output is:

- Calendar 1
	- 14:00 Management Meeting
	- 17:30 Team Meeting
- Calendar 2
	- 10:00 Stand Up

We should have the option to have:

- Calendars
 	- 10:00 Stand Up
	- 14:00 Management Meeting
	- 17:30 Team Meeting

So we have a joint boolean setting, should be relatively easy to do by joining the output objects and re-ordering.

**Comment by haydenull** [comment]
Do you mean gantt view here?

**Comment by koconder** [comment]
No, this is when you press the calendar button from the plugin in the journal and it pastes the agenda (_fetching from calendar_)
