### ISSUE TITLE
Feature - Skip words or Regex

### ISSUE THREAD

**Issue by koconder** [haydenull/logseq-plugin-agenda#58]
Allow for certain calendar items to be skipped using stop words/sentences or regex

**Comment by haydenull** [comment]
Can I know what the usage scenarios of this feature are?

**Comment by koconder** [comment]
@haydenull this would be for placeholder stuff people use in thier calendar or not real items they need to put notes/agenda against. Again a simple-ish thing to add to reduce noise in LogSeq for large calendars like mine.
