### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#6]
Hi @haydenull 

A suggestion. It could be interesting to put the calendar in full screen. On small laptop screens it would be useful. 
Thanks ;-)

**Comment by haydenull** [comment]
Thanks for your suggestion, I will adding this feature in the future.

**Comment by haydenull** [comment]
Version 1.4.0 already supports full screev mode.

**Comment by haydenull** [comment]
Due to no reply for a long time, I will close this issue, please reopen it if there is any problem.
