### ISSUE TITLE
Display calendar events in Agenda and Dashboard

### ISSUE THREAD

**Issue by JakobBruenker** [haydenull/logseq-plugin-agenda#65]
I really like this plugin, it's the main reason I'm able to transition tracking of tasks from Amazing Marvin to Logseq.

One thing I'm missing, though, is an option to be able to see today's calendar events either in the "/Agenda: Insert task list" blocks or somewhere in the dashboard (Ideally I'd like to see them in both).

It's possible that such an option exists already, though I couldn't find one.

**Comment by haydenull** [comment]
Both of these are currently showing today's tasks taken from the notes.

Do you mean to display the events from the subscription calendar in these two places?

**Comment by JakobBruenker** [comment]
Yes, I'm asking for an option to show events from subscriptions in addition to the tasks.

**Comment by haydenull** [comment]
Ok, that's in the development plan.

**Comment by JakobBruenker** [comment]
Works! Thank you
