### ISSUE TITLE
在agenda视图通过拖动鼠标建立event直接变成milestone event 退出agenda视图 再进去就OK了

### ISSUE THREAD

**Issue by louisw00** [haydenull/logseq-plugin-agenda#66]
开发者你好 辛苦了
我发现有一个小bug
如标题所描述
复现:
1. 进入agenda plugin试图并选择calendar
2. 在某一天某个时间用鼠标拖动形成event
3. event直接跳转到顶部milestone 但是根据b站视频 milestone event必须要 tag milestone
4. 退出agenda 再进入 就OK了
5. daily log 显示正常

如果我表述还不够清楚 我可以上传视频到某一网盘 谢谢
![image](https://user-images.githubusercontent.com/28638524/173172518-418a78a7-c659-411a-a434-a2bcdd2e8453.png)

**Comment by haydenull** [comment]
2.3.2 版本修复了这个问题，可以再试一下
