### ISSUE TITLE
Not listed in marketplace

### ISSUE THREAD

**Issue by felixdollack** [haydenull/logseq-plugin-agenda#68]
Seems like a stupid question to ask, but I don't see this plugin in marketplace.
Is there a trick to find it or do I need to install it manually?

Logseq Version 0.7.4
macOS 12.3.1 (x86_64)

**Comment by haydenull** [comment]
You can try searching in the market.

**Comment by felixdollack** [comment]
Yes, I tried that. But the available list (out of all plugins) just get's filtered and I see no matching plugin.

**Comment by hugows** [comment]
Same, thought logseq-agenda was another plugin...
