### ISSUE TITLE
Calendar import TypeError

### ISSUE THREAD

**Issue by Gadwood** [haydenull/logseq-plugin-agenda#69]
When I add school and iCloud calendar link I get flooded with 403 error or TypeError: it.search is not a function

School https://monportail.ulaval.ca/communication/v1/ical/fb2885013fbd3ebd9ebc9efa887cc447
Dummy Icloud test ('subscriptionList.3.url' is not a valid url)
webcal://p110-caldav.icloud.com/published/2/MTcxOTQyNDQ3NTAxNzE5NL9_bN4mMucAGwjH_bPb7tP6hv0BIJYXWKjVADPU604hJPFRTQDjp0byAhXJ2OhjKzBgHLgg9cLqhcXE7hRfjE8

**Comment by haydenull** [comment]
Just need to replace webcal with https.

Such as `https://p110-caldav.icloud.com/published/2/MTcxOTQyNDQ3NTAxNzE5NL9_bN4mMucAGwjH_bPb7tP6hv0BIJYXWKjVADPU604hJPFRTQDjp0byAhXJ2OhjKzBgHLgg9cLqhcXE7hRfjE8`

**Comment by haydenull** [comment]
The issue of the school calendar failing will be fixed in the next release.
