### ISSUE TITLE
Custom queries for projects?

### ISSUE THREAD

**Issue by pigmej** [haydenull/logseq-plugin-agenda#73]
Would that be possible to have custom queries that would yield the tasks for project?

**Comment by pigmej** [comment]
Hey the problem is my workflow. I tend links on one level above my todos to not repeat mentioning `#foo` or `[[foo]]` on every todo. So my structure is usually:

```
* [[Foo]]
  * TODO one
  * TODO two
  * TODO three
*#Bar
   * TODO one one
```

so far from what I see that confuses your cool plugin and makes it all land under ~wrong project.

**Comment by haydenull** [comment]
Sorry, this may not be supported, the plug-in plans support using custom property to set the owning project.

**Comment by haydenull** [comment]
Agenda3 supports custom filters, you can give it a try.
