### ISSUE TITLE
TODOs belong to other projects than Journal are not shown in dashboard.

### ISSUE THREAD

**Issue by Creling** [haydenull/logseq-plugin-agenda#75]
Hi,

Suppose I have a project named `Project/foo` with a TODO like following:

![image](https://user-images.githubusercontent.com/43109504/177032355-7a0f5740-7941-4019-b460-2d20751a39fa.png)

This TODO is displayed in `Dashboard -> Project/foo -> List`:

![image](https://user-images.githubusercontent.com/43109504/177032160-d3cd0275-bdc0-4365-b01f-04ded2cb2413.png)

But not `Dashboard`:

![image](https://user-images.githubusercontent.com/43109504/177032218-a5f48433-e4ca-4569-8ff9-8b641dfe83e3.png)

PS: I use the latest version of both the Logseq and the plugin and I have restart Logseq for several times.

**Comment by haydenull** [comment]
Thanks to the feedback, task with no date has been filtered. This is a bug. The next version will fix it.

**Comment by haydenull** [comment]
Version 2.6.6 has fixed this bug, you can try it again.
