### ISSUE TITLE
Overdue Tasks

### ISSUE THREAD

**Issue by andupaz** [haydenull/logseq-plugin-agenda#76]
Hi,

I saw the earlier enhancement post (#71) where the duplicate overdues are mentioned. I partially agree with the solution suggestion.  Depending on which calendar view you use you will oversee overdue tasks due to this. I use the weekly view and overdue tasks from last week are not displayed anymore. Sure I can manually drag them now, but the risk of forgetting something persists. 

I think the standard behaviour should be to display overdue tasks **only** on today's date, therefore avoiding duplicates and the risk of overseeing/forgetting to drag a task. #71's suggestion should be kept as an additional option though - this way we can drag selected overdue tasks to some point in the future (though this was something that I was doing simply by changing the deadline/schedule).

Let me know what you think! Cheers

**Comment by haydenull** [comment]
Thanks for the feedback, dashboard and sidebar will always show overdue tasks to avoid omission. Will this meet your needs?

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/17695989/177241708-5c65b0bf-428a-47f2-9d8f-e74db758f823.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/17695989/177241784-4fff8ce7-b3b1-48c4-9218-5fda9b8e5424.png">

**Comment by andupaz** [comment]
It's true that overdue tasks are shown in the dashboard, but don't you think there should also be some overview in the calendar view? I personally only use the calendar view, that's why I ask, but of course the dashboard does the job.
