### ISSUE TITLE
Assigning colors to events ?

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#8]
Hi @haydenull 

I think this plugin is so great that I plan to manage my professional and personal calendars in it. But for that I would need to be able to visually distinguish the colors depending on the type of calendar. My idea would be the following: use "daily logs" to act as a diary **and** a calendar... it could look like this.

Imagine we are the 2022-03-08

```
[[daily logs]]
 - 08:30-08:45 Go to school with my daughter
 - 09:00-10:30 Meeting with my boss
 - 13:00-13:30 Call with Bob about his report
   - TODO Read Bob’s report before
     DEADLINE: <2022-03-07 Mon>
 - 15:30 Call Alice
```

I would like personal events to appear in green and professional events in red. What solution could we imagine? 

1. using `#green` or `#red` tags at the end of the lines could be interpreted as a color parameter in the calendar. 
2. use or hijack the create a new calendar function? But how ? Currently, it is rather to think to have separate calendars per project. Here I would like to do the opposite, to have different types of events or tasks in the same calendar. I already manage for example tasks with tags `#pro` `#perso` to be able to filter in normal time. 

What do you say about all this?

**Comment by haydenull** [comment]
Are you referring to the distinction between `13:00-13:30 Call with Bob about his report` and `TODO Read Bob’s report before`?
I have add style configurations to the logKey in version 1.2.0.

![image](https://user-images.githubusercontent.com/17695989/157347175-2904f681-170f-4bb1-8399-2e54bc1b20dd.png)
![image](https://user-images.githubusercontent.com/17695989/157347333-248900c7-645c-4474-bcae-708edb5a4642.png)

At present, the color is bound to the calendar, if you want to use a different color, it is recommended to customize a new calendar.
If use different styles in the same calendar, we must also fill in the rules to let the plug-in know how to apply, and the final complexity is similar to creating a new calendar, so this feature may not be supported for the time being.

**Comment by haydenull** [comment]
welcome to reopen issue if you still have questions
