### ISSUE TITLE
Timeline页面无法跳转到块，并且不显示每日已完成的TODO

### ISSUE THREAD

**Issue by zhuoqun-chen** [haydenull/logseq-plugin-agenda#82]
开发大大您好：

我之前安装使用您这个插件是通过手动方式导入的，今天卸载了之后，在插件市场中重新安装Agenda插件，重启Logseq后遇到了两个问题：

1. 在Agenda的Timeline页面，Navigate to block功能失效，不能跳转
2. Timeline页面中也无法显示每日已经完成的TODO事项，原先完成的TODO项，左边都有绿色对勾提示

![image](https://user-images.githubusercontent.com/73287160/177751024-046574ff-4abb-4eb2-a5b3-1ec7b7d03565.png)

请问是哪里出了问题呢？期待您的回复！

**Comment by haydenull** [comment]
你好，查了下代码
1. 无法跳转是新版本的 bug，下个版本会修复
2. 新版本取消了✅，下个版本会加上更明显的样式区分

一切顺利的话本周会发一个版本。

**Comment by zhuoqun-chen** [comment]
好滴，非常感谢！❤
这个Timeline页面和是否完成的样式区分对我真是太有帮助了！

**Comment by haydenull** [comment]
2.6.0 版本已经发布，可以试一下是否还有问题

**Comment by zhuoqun-chen** [comment]
测试了[v2.6.4](https://github.com/haydenull/logseq-plugin-agenda/releases/tag/v2.6.4)，跳转已经正常。😎
