### ISSUE TITLE
Duration of the synchronization

### ISSUE THREAD

**Issue by bepolymathe** [haydenull/logseq-plugin-agenda#85]
Hi @haydenull 

Thanks for this wonderful plugin ! 
What is the synchronization frequency of the external calendars to which we subscribe?
Cheers

**Comment by haydenull** [comment]
Each time you click the icon in toolbar to open the plug-in, the latest subscription calendar is requested.

**Comment by bepolymathe** [comment]
Great ! Thanks for reply !
