### ISSUE TITLE
Changing date of task in calendar broke task

### ISSUE THREAD

**Issue by dmytrodubinin** [haydenull/logseq-plugin-agenda#86]
When I try to move task in calendar, date in the task broken.

https://user-images.githubusercontent.com/8066458/178117427-d64f3d72-c611-4da8-86a3-8e8529914ee0.mp4

**Comment by dmytrodubinin** [comment]
As far as I can see, changing the date in the calendar removes the TODO mark. 
If you reset the mark manually, then the problem is solved. But in any case, this complicates the change of the date, because the change through the calendar breaks the task

**Comment by haydenull** [comment]
2.6.4 has been released, you can try again.

**Comment by dmytrodubinin** [comment]
It works well! Thanks for perfect plugin!
