### ISSUE TITLE
toolbar-plugins-manager button show above the agenda window

### ISSUE THREAD

**Issue by dmytrodubinin** [haydenull/logseq-plugin-agenda#87]
New plugins button in Logseq is visible above the agenda plugin window:

https://user-images.githubusercontent.com/8066458/178135080-e57b66f8-449d-4b86-9a2c-058de4629af8.mp4

**Comment by haydenull** [comment]
It seems that this icon is used by logseq to manage toolbar.

This icon is not controlled by plug-ins. What version of logseq and plug-ins do you use?

**Comment by dmytrodubinin** [comment]
Logseq 0.7.6 AppImage in Fedora
Plugins on screenshot:
![image](https://user-images.githubusercontent.com/8066458/178139585-783beba8-8afa-42cc-9a28-a4268ad93248.png)

**Comment by dmytrodubinin** [comment]
Found the reason. Yes, it is a problem in logseq. Container of this icon has z-index 999:
`<div class="relative ui__dropdown-trigger toolbar-plugins-manager-trigger" style="z-index: 999;"><div class="toolbar-plugins-manager"><a class="button"><i class="ti ti-puzzle"></i></a></div></div>` 
I close issue, but you can fix it by add z-index more:
![image](https://user-images.githubusercontent.com/8066458/178140393-4abba365-cd67-4c24-b870-89ceef3e6001.png)

**Comment by haydenull** [comment]
Will it still appear after closing the agenda plug-in or use the default theme? After reading your previous [issue](https://github.com/haydenull/logseq-plugin-agenda/issues/86), this problem appeared before 2.6.4.

Maybe the banner plugin conflicts with the theme you use.

**Comment by dmytrodubinin** [comment]
No, I reset to default theme:

https://user-images.githubusercontent.com/8066458/178143197-14d0f704-8260-4b4c-8e4e-b3f91443a332.mp4

You can try to install Logseq Markmap plugin to test it

**Comment by haydenull** [comment]
I see, this is a normal performance, the markmap plugin registration place is the pagebar, agenda plugin registration location is the toolbar, they are not the same.

The document is [here](https://logseq.github.io/plugins/interfaces/IAppProxy.html#registerUIItem).

**Comment by haydenull** [comment]
I see. The next version will fix this problem.

**Comment by dmytrodubinin** [comment]
Thanks for perfect plugin!

**Comment by haydenull** [comment]
Version 2.6.6 was just released, you can try it again.

**Comment by dmytrodubinin** [comment]
Perfect! Thanks!
