### ISSUE TITLE
Accepts Namespace in the project page name的具体含义？

### ISSUE THREAD

**Issue by rdrd0023** [haydenull/logseq-plugin-agenda#89]
Hi，
https://haydenull.github.io/logseq-plugin-agenda/settings/project.html
这里写了`The plugin accepts Namespaces in the project page name.`，想确认一下这句话的意思是，显示的是只有当前子页面的所有todo是吗？
比如我有页面`fruits/apple`，如果我在project page填`fruits`的话，好像不会显示`fruits/apple`中的todo？

想问一下如果可以的话，可以做成新的feature吗？如果在project中显示所有子页面中的todo会很方便。
谢谢

**Comment by haydenull** [comment]
现在任务是以page为维度区分的，fruits 是一个 page，`fruits/apple` 也是一个 page，这两个 page 都是独立的，只不过有一些特殊的关联。
所以 todo 属于哪个 page，就会显示在哪个 project 里。

如果以后 logseq 把 fruits 和 `fruits/apple` 之间的关联关系能告诉插件，就可以做这个功能了。

**Comment by rdrd0023** [comment]
了解，谢谢告知！

**Comment by haydenull** [comment]
Agenda3 支持自定义 Filter，可以使用 query 将多个页面的任务自由组合，应该可以实现这个功能了
