### ISSUE TITLE
【Bug】30min的Start延迟

### ISSUE THREAD

**Issue by TITC** [haydenull/logseq-plugin-agenda#92]
很感谢您提供了如此便捷且高效的插件

## 版本信息
OS&version: windows11 21H2
logseq version：0.7.6
agenda version: https://github.com/haydenull/logseq-plugin-agenda/compare/v2.6.3...v2.6.4 https://github.com/haydenull/logseq-plugin-agenda/compare/v2.6.4...v2.6.5 

## 问题描述&复现
1. 在Calendar界面，双击一个时间段
2. 在弹出的Modify Schedule界面上All day设置为No
3. 点击Start时间框后，在弹出的日期时间界面点击左下角的Now。

该操作预期是将Start设置为当前时间，而实际发生的是将时间设置为了30min之后。

![image](https://user-images.githubusercontent.com/35098797/178846190-ed02d715-fb19-4e89-a825-6e4e0bb269c6.png)

**Comment by haydenull** [comment]
2.6.6 版本已发布，可以再试试
