### ISSUE TITLE
能不能加个循环任务？

### ISSUE THREAD

**Issue by rebron1900** [haydenull/logseq-plugin-agenda#94]
如题，某些周期性的计划需要用到。

**Comment by haydenull** [comment]
感谢反馈，这个功能是有计划做的，但是目前还没想好技术方案，需要一点时间。

**Comment by Zhaotianzheng** [comment]
我现在是自己手写一堆todo，也算是勉强能用。。如果能直接传入循环参数不新建todo只在界面中显示就好了，但是不新建todo（或者其他能搜索的）感觉应该会对其他的一些query操作有影响，这样改动感觉会比较大，
还有一个想法是利用当前像是Daily log这样的关键字在循环的时间的journal中把todo创建好，当然要支持批量取消可能还需要增加接口。我之前是用日记的template做的这样的操作但是由于没办法限定时间范围所以放弃这种方式了。

**Comment by huanhuanqiongqiong** [comment]
解析logseq自带的logbook是否可行呢？虽然这功能logseq还有些bug。。。

**Comment by haydenull** [comment]
logbook 不太好编辑，也没有 api 可以直接修改，感觉不太满足需求。

目前的想法是参考插件番茄钟部分的实现，自定义一个新语法来记录。不过这样一来就不能和 logseq 自己的功能打通。
logseq 本身没有很好地支持循环任务，也是没办法的选择。

**Comment by proItheus** [comment]
现在Logseq好像是支持循环任务的
https://docs.logseq.com/#/page/648d85b0-9101-496a-87f6-5c90917556a3

**Comment by haydenull** [comment]
> 现在Logseq好像是支持循环任务的 https://docs.logseq.com/#/page/648d85b0-9101-496a-87f6-5c90917556a3

链接打不开，是指 logseq 目前那个像 org mode 的吗，那个感觉跟目前市面上的日历里的循环任务差异比较大，也不太灵活

**Comment by haydenull** [comment]
Agenda3 支持 logseq 的周期任务了
