### ISSUE TITLE
Adding project tasks from journal page

### ISSUE THREAD

**Issue by mdmanurung** [haydenull/logseq-plugin-agenda#96]
Dear author,

Is it possible to add project tasks from the daily journal page? I usually add the tasks as I go through the day in my daily journal and then I can just click the project page to see tasks that I have/haven't completed. 

Thank you in advance for taking the time.

Regards,
Mikhael

**Comment by haydenull** [comment]
You can use the project custom property to specify which project the task should belong to.
![image](https://user-images.githubusercontent.com/17695989/179334375-b29f8ebe-63d1-47b2-985e-8983b0e0d358.png)

**Comment by mdmanurung** [comment]
Thank you!

**Comment by silvewheat** [comment]
This is a useful feature. It should be very helpful to add this information in the doc.
