### ISSUE TITLE
可以跟踪这个project所链接的所有页面的todo吗

### ISSUE THREAD

**Issue by Taoaozw** [haydenull/logseq-plugin-agenda#98]

**Comment by haydenull** [comment]
这个不行，一个页面就是一个 project，所以他们之间是互相独立的平级关系。

**Comment by haydenull** [comment]
你是指namespace吗，那倒是可以，之前有提过类似的issue。等官方支持查namespace api以后可以做。

**Comment by micl9** [comment]
> 你是指namespace吗，那倒是可以，之前有提过类似的issue。等官方支持查namespace api以后可以做。

嗯嗯 是这个概念 期待一波

**Comment by kinglion580** [comment]
支持，我时常是在日志页这样创建 task。 sample: `task 1 #project1` 。这样 project1 页面链接的所有 todo 都是属于该项目的。如果能支持 agenda 里显示链接的 todo 就好了。

**Comment by haydenull** [comment]
Agenda3 移除了 project 的概念，新增的 Filter 可以使用 query 自由组合任意页面，可以试试

**Comment by Taoaozw** [comment]
> Agenda3 removes the concept of project, and the new Filter can use query to freely combine any page, you can try it

好的谢谢，我现在主力目前已经切换到Tana了
